/* shots-ui.jsx — The Art Room ▸ Shot List (React).
   Scene-grouped shot list. Each shot is ONE beat, carrying cinematographer grammar
   (size · angle · movement · lens), the subjects/location/props in frame, an action
   line and an editable composition note. The frame is generated by composing the
   scene's Style Bible grade + the location plate + the character/prop sheets as
   reference images (see buildShotPrompt). Reuses SheetFrame, useImageGen and the
   shared batch engine so it behaves exactly like the other Art Room tabs. */

const _el = React.createElement;

/* a labelled grammar dropdown (size / angle / move / lens) */
function GrammarSelect({ label, value, options, onChange }){
  return _el("label",{className:"shot-gsel"},
    _el("span",{className:"shot-gsel-lab"},label),
    _el("select",{className:"prop-select",value:value,onChange:e=>onChange(e.target.value)},
      options.map(o=>_el("option",{key:o.id,value:o.id,title:o.desc||""},o.label))));
}

function CameraSettingSelect({ label, value, options, onChange }){
  return _el("label",{className:"shot-gsel"},
    _el("span",{className:"shot-gsel-lab"},label),
    _el("select",{className:"prop-select",value:value||"auto",onChange:e=>onChange(e.target.value)},
      options.map(o=>_el("option",{key:o.id,value:o.id,title:o.desc||""},o.label))));
}

function AdvancedCameraSettings({ sh, onUpdate }){
  const c = { camera:"auto", lensType:"auto", focalLength:"auto", aperture:"auto", shutter:"auto", iso:"auto", ...(sh.cameraSettings||{}) };
  const patch = (key,val)=> onUpdate(sh.id,{ cameraSettings:{ ...c, [key]:val } });
  const active = typeof shotHasCameraSettings==="function" && shotHasCameraSettings(sh);
  const reset = ()=> onUpdate(sh.id,{ cameraSettings:{ camera:"auto", lensType:"auto", focalLength:"auto", aperture:"auto", shutter:"auto", iso:"auto" } });
  return _el(CardFold,{label:"Advanced cinematography"+(active?" · custom camera":" · Auto"),defaultOpen:false},
    _el("div",{className:"shot-camera-panel"},
      _el("div",{className:"shot-camera-head"},
        _el("div",{className:"shot-camera-note"},
          _el(Icon.info,{s:12}),"Leave controls on Auto unless you want this shot to carry explicit camera language into the frame prompt."),
        active && _el("button",{className:"shot-camera-reset",onClick:reset,title:"Reset all advanced camera settings to Auto"},"Reset to Auto")),
      _el("div",{className:"shot-camera-grid"},
        _el(CameraSettingSelect,{label:"Camera",value:c.camera,options:SHOT_CAMERA_BODIES,onChange:v=>patch("camera",v)}),
        _el(CameraSettingSelect,{label:"Lens type",value:c.lensType,options:SHOT_LENS_TYPES,onChange:v=>patch("lensType",v)}),
        _el(CameraSettingSelect,{label:"Focal length",value:c.focalLength,options:SHOT_FOCAL_LENGTHS,onChange:v=>patch("focalLength",v)}),
        _el(CameraSettingSelect,{label:"Aperture",value:c.aperture,options:SHOT_APERTURES,onChange:v=>patch("aperture",v)}),
        _el(CameraSettingSelect,{label:"Shutter",value:c.shutter,options:SHOT_SHUTTERS,onChange:v=>patch("shutter",v)}),
        _el(CameraSettingSelect,{label:"ISO / grain",value:c.iso,options:SHOT_ISO_GRAIN,onChange:v=>patch("iso",v)})),
      active && _el("div",{className:"shot-camera-preview"},
        (typeof shotCameraSettingsClause==="function") ? shotCameraSettingsClause(sh) : "")));
}

/* a toggle chip row for choosing which cast / props are in frame */
function FrameToggles({ label, items, selected, onToggle, emptyHint }){
  if(!items.length) return _el("div",{className:"shot-frame-empty"},emptyHint);
  return _el("div",{className:"shot-frame-row"},
    _el("span",{className:"shot-frame-lab"},label),
    _el("div",{className:"shot-chips"},
      items.map(it=>{
        const on = selected.indexOf(it.id)>=0;
        return _el("button",{key:it.id,className:"shot-chip"+(on?" on":""),onClick:()=>onToggle(it.id)},
          on?_el(Icon.check,{s:11}):null, it.name);
      })));
}

function ShotCard({ sh, scene, ctx, characters, propsAvail, beatText, prevShot, laterShots, isHead, isFirst, onToggleHead, onUpdate, onDelete, onView, batchActiveId, onBatchDone, onGenerateShot, onRegenDownstream, onStopChain, subLabel, plan }){
  const loc = ctx.location;
  // who/what is in frame is DERIVED from the action text (single source of truth) — the
  // old manual tags are gone; this is what the prompt + references actually use.
  const _allChars = Object.values(ctx.charById||{});
  const inCastIds = (typeof inFrameCast==="function") ? inFrameCast(sh, scene, _allChars) : (sh.subjects||[]);
  const subjects = inCastIds.map(id=>ctx.charById[id]).filter(Boolean);
  const inPropIds = (typeof inFrameProps==="function") ? inFrameProps(sh, scene, ctx.charById, ctx.propById) : (sh.props||[]);
  // DRIFT FLAG: characters/props named in the micro-beats this shot COVERS but missing
  // from its action text. The render-time canon merge would try to rescue them — better
  // to surface the seam on the card so the director can re-include them deliberately.
  const dropped = (()=>{
    const micro = (plan && Array.isArray(plan.micro)) ? plan.micro
      : ((sh.beatPlan && Array.isArray(sh.beatPlan.micro)) ? sh.beatPlan.micro : null);
    if(!micro || !Array.isArray(sh.covers) || !sh.covers.length) return null;
    const covered = sh.covers.map(n=>micro[n-1]).filter(Boolean);
    if(!covered.length) return null;
    // scan the covered micro-beats as if they were an action, WITHOUT the scene-driver
    // fallback (a bare inFrameCast would claim the driver even when unnamed)
    const fakeScene = scene ? Object.assign({}, scene, { driver:null }) : scene;
    const fake = { action: covered.join(" ") };
    const wantChars = (typeof inFrameCast==="function") ? inFrameCast(fake, fakeScene, _allChars) : [];
    const wantProps = (typeof inFrameProps==="function") ? inFrameProps(fake, fakeScene, ctx.charById, ctx.propById) : [];
    const chars = wantChars.filter(id=> inCastIds.indexOf(id)<0)
      .map(id=>ctx.charById[id]).filter(Boolean).map(c=>c.name);
    const props = wantProps.filter(id=> inPropIds.indexOf(id)<0)
      .map(id=>ctx.propById[id]).filter(Boolean).map(p=>p.name);
    return (chars.length || props.length) ? chars.concat(props) : null;
  })();
  // apply the SAME dressing filter the real attach path uses (collectShotRefs /
  // buildShotPrompt) — set-dressing sheets only ride on tight shots or when the
  // object leads the action; the plate delivers them in wides. Without this the
  // thumbnail strip SHOWS sheets that never actually attach.
  const inProps = inPropIds.map(id=>ctx.propById[id]).filter(Boolean)
    .filter(p=> (typeof shotPropAttachable!=="function") || shotPropAttachable(p, sh));
  const locWeight = (typeof locWeightForSize==="function") ? locWeightForSize(sh.size) : "primary";
  // the "Shot prompt" preview reflects what WILL generate: a non-head shot chains from the
  // previous frame (continuity_anchor present); the head renders fresh from the sheets.
  const promptCtx = { ...ctx, prevShot:prevShot||null, laterShots:laterShots||[] };
  const finalPrompt = combinedShotPrompt(sh, promptCtx);
  const chainPrompt = (typeof buildShotPrompt==="function") ? buildShotPrompt(sh, { ...promptCtx, prevFrameRole:true }) : finalPrompt;
  const previewPrompt = isHead ? finalPrompt : chainPrompt;

  // THE COVERAGE SEED (user ruling 2026-08-01): a non-head shot generates as an
  // image-edit off the REFERENCE frame — within a beat that's the beat's FIRST shot
  // (its coverage anchor), so B/C/D all build on A instead of their immediate
  // predecessor; a beat opener chains from the previous beat's tail frame. The seed
  // carries the colour grade AND the progressive physical state (wetness, dirt,
  // damage, wardrobe wear) forward, while this shot stages its own action.
  // A chain head renders from the sheets alone. ASYNC on purpose: in cloud mode
  // the reference frame often isn't in the sync cache
  // right after a reload — falling back to nbLoadImage keeps the chain intact.
  const deriveBase = async (gopts)=>{
    if(!prevShot || (gopts && (gopts.fresh || gopts.editInstruction))) return null;
    let u = (typeof nbGetImage==="function") ? nbGetImage(prevShot.id) : "";
    if(!u && typeof nbLoadImage==="function"){ try{ u = await nbLoadImage(prevShot.id); }catch(e){} }
    return u || null;
  };

  // reference SHEETS (the locked canon) — the seed frame rides separately as the base image.
  // Ordered by location weight: a wide leads with the set plate (geography reads); a tight
  // leads with the cast and demotes the plate to a background/grade anchor.
  const collectShotRefs = async (gopts)=>{
    const grab = async (id)=>{ let u = (typeof nbGetImage==="function") ? nbGetImage(id) : "";
      if(!u && typeof nbLoadImage==="function"){ try{ u = await nbLoadImage(id); }catch(e){} } return u; };
    const _locPanel = (loc && typeof shotLocPanel==="function") ? shotLocPanel(sh) : null;
    const locSpec = loc
      ? ((typeof shotLocationCoverageSpecs==="function")
        ? shotLocationCoverageSpecs(loc, sh, scene, (window.turnContinuity||{}).drafts||{})
        : [{ id:loc.id, locPanelQ:(_locPanel?_locPanel.q:null),
          note:(loc.name||"location")+" — the set seen as its "+(_locPanel?_locPanel.label:"coverage view")+" (one full-frame view)" }])
      : [];
    // identity anchors for the cast & props actually in THIS frame — derived from the
    // action text (inFrameCast/inFrameProps), never the fragile manual tags.
    const _chars = Object.values(ctx.charById||{});
    const inCast = (typeof inFrameCast==="function") ? inFrameCast(sh, scene, _chars) : (sh.subjects||[]);
    const inPr   = (typeof inFrameProps==="function") ? inFrameProps(sh, scene, ctx.charById, ctx.propById) : (sh.props||[]);
    const castSpec = inCast.map(id=>{ const c=ctx.charById[id]; return c?{ id, note:c.name+" character sheet" }:null; }).filter(Boolean);
    // dressing sheets attach only on tight shots / when the object is the action's
    // subject (shotPropAttachable) — MUST mirror buildShotPrompt's filter exactly,
    // or the prompt's image-map numbering mislabels the attached files
    const propSpec = inPr.map(id=>{ const p=ctx.propById[id];
      if(!p || (typeof shotPropAttachable==="function" && !shotPropAttachable(p, sh))) return null;
      // STATE-AWARE: attach the active appearance-state variant when one exists —
      // MUST resolve identically in buildShotPrompt's image map and generateShotFrame.
      // CUSTODY-AWARE: the note names the scene's actual holder after a handover.
      const _scs = (ctx.scenes || ((window.turnContinuity||{}).scenes) || []);
      const so = (typeof shotPropSheetId==="function") ? shotPropSheetId(p, scene, _scs) : { id:p.id, state:null };
      const co = (typeof custodyOwnerAt==="function") ? custodyOwnerAt(p, scene, _scs) : { name:p.ownerName, handover:null };
      return { id:so.id, baseId:p.id, note:p.name+" prop sheet"+(so.state?(" \u2014 "+so.state.label):"")+(co.handover&&co.name?(" \u2014 "+co.name+" holds it now"):"") }; }).filter(Boolean);
    // same untick filter as generateShotFrame/buildShotPrompt — labels match files
    const _refOff = Array.isArray(sh.refOff) ? sh.refOff : [];
    const ordered = ((locWeight==="ambient") ? [...castSpec, ...locSpec, ...propSpec] : [...locSpec, ...castSpec, ...propSpec])
      .filter(s=> _refOff.indexOf(s.baseId||s.id)<0);
    const out = [];
    for(const s of ordered){ let u = await grab(s.id);
      if(u && s.locPanelQ!=null && typeof shotLocPanelCrop==="function"){ const cu=await shotLocPanelCrop(u, s.locPanelQ); if(cu) u=cu; }
      if(u) out.push({ url:u, note:s.note, refId:s.id }); }
    return out;
  };

  const gen = useImageGen({
    id: sh.id, slotId: "shot-"+sh.id,
    buildFinal: ()=> finalPrompt,
    buildSimple: ()=> buildShotPrompt(sh, ctx),
    referenceFallback: deriveBase,
    buildFromBase: ()=> chainPrompt,
    attachments: collectShotRefs,
    // buildShotPrompt now names the reference stack in-prose (the spine + staging + References
    // block), so we don't append a second reference sentence here — that would just duplicate it.
    attachmentsText: ()=> "",
    buildEdit: (instr)=>
      "Edit this film frame. Apply ONLY this change: "+instr+". Keep the same shot size, lens, staging, "
      +"the same characters (identical faces & wardrobe), the same location and the same colour grade. Do not re-imagine the frame.",
    // Shot frames commonly carry a rolling seed plus several canon sheets. A
    // 640px reference is ample for identity/composition and keeps GPT Image 2
    // comfortably inside the proxy window. These are input references only:
    // generated quality and resolution always follow the user's selected controls.
    referenceMaxDim: 640,
  });

  // Every manual Generate / Regenerate enters the scene's ordered runner. If an earlier
  // shot in the chain isn't rendered yet, the runner asks the user to generate it first
  // (it's the anchor) rather than rendering out of order. Raw gen.generate() runs when active.
  const guardedGenerate = (gopts)=>{
    // An edit operates on THIS already-generated frame in place — it isn't a new chain
    // request, so it bypasses the ordered runner and edits the current frame directly.
    if(gopts && gopts.editInstruction){
      if(sh.locked) onUpdate(sh.id,{locked:false});
      return gen.generate(gopts);
    }
    return onGenerateShot ? onGenerateShot(sh.id) : gen.generate(gopts);
  };
  const genGuarded = Object.assign({}, gen, { generate: guardedGenerate });

  // batch auto-generate when this card is the active queue member
  // If this card remounts off-screen while its generation is already running
  // (the user navigated to another scene), resume watching that same run instead
  // of accidentally starting it again when it finishes.
  const batchStarted = React.useRef(batchActiveId===sh.id && gen.gening);
  const wasGening = React.useRef(gen.gening);
  React.useEffect(()=>{
    const mine = batchActiveId===sh.id;
    if(!mine){ batchStarted.current=false; wasGening.current=gen.gening; return; }
    if(!batchStarted.current && !gen.gening){ batchStarted.current=true; wasGening.current=false; gen.generate(); return; }
    if(batchStarted.current && wasGening.current && !gen.gening){ batchStarted.current=false; onBatchDone && onBatchDone(sh.id); }
    wasGening.current = gen.gening;
  },[batchActiveId, gen.gening, sh.id]);

  const toggleIn = (key, id)=>{ const cur = sh[key]||[]; const next = cur.indexOf(id)>=0 ? cur.filter(x=>x!==id) : [...cur, id];
    const patch = { [key]: next }; if(key==="subjects") patch.subjectsSet = true; onUpdate(sh.id, patch); };

  // REFERENCE IMAGES that influence this shot's frame — the scene KEY FRAME it derives
  // from, the LOCATION coverage plate, and the in-frame CHARACTER & PROP sheets. Shown as
  // small thumbnails (click to enlarge) so it's clear what canon art the generation locks
  // to. Recomputed from the live entity sheets (always displayable), keyed off the ids.
  const [refImgs, setRefImgs] = React.useState([]);    // seed frame + the canon sheets, ordered by location weight
  // the SEED is the previous shot's frame, whose image isn't part of this card's props — so when
  // it commits (uploaded OR generated), bump on its nb-gen-done so the seed thumb appears without a reload.
  const [prevSeedBump, setPrevSeedBump] = React.useState(0);
  React.useEffect(()=>{
    if(!prevShot) return;
    const pid = prevShot.id;
    const onDone = (e)=>{ if(e && e.detail && e.detail.id===pid) setPrevSeedBump(b=>b+1); };
    window.addEventListener("nb-gen-done", onDone);
    return ()=>window.removeEventListener("nb-gen-done", onDone);
  },[prevShot && prevShot.id]);
  const _coverageKey = loc && Array.isArray(loc.coverageSheets) ? loc.coverageSheets.map(v=>v.id).join(",") : "";
  const _refKey = [sh.id, prevShot&&prevShot.id, prevShot&&prevShot.locked?1:0, prevSeedBump, loc&&loc.id, _coverageKey, locWeight,
    subjects.map(c=>c.id).join(","), inProps.map(p=>p.id).join(","), gen.genUrl||""].join("|");
  React.useEffect(()=>{
    let alive = true;
    (async ()=>{
      const grab = async (id)=>{ let u = (typeof nbGetImage==="function") ? nbGetImage(id) : "";
        if(!u && typeof nbLoadImage==="function"){ try{ u = await nbLoadImage(id); }catch(e){} } return u||""; };
      // the rolling SEED leads (the previous shot's frame), then the canon sheets ordered by weight
      const seedU = prevShot ? await grab(prevShot.id) : "";
      const seed = (prevShot && seedU) ? [{ url:seedU, label:"Previous shot · Beat "+(prevShot.beatN||"—"), kind:"seed", approved:!!prevShot.locked }] : [];
      const locItems = []; if(loc){
        const p = (typeof shotLocPanel==="function") ? shotLocPanel(sh) : null;
        const locSpecs = (typeof shotLocationCoverageSpecs==="function")
          ? shotLocationCoverageSpecs(loc, sh, scene, (window.turnContinuity||{}).drafts||{})
          : [{ id:loc.id, locPanelQ:(p?p.q:null), note:(loc.name||"Location")+" plate" }];
        for(const s of locSpecs){ let u=await grab(s.id);
          if(u && s.locPanelQ!=null && typeof shotLocPanelCrop==="function"){
            const cu=await shotLocPanelCrop(u, s.locPanelQ); if(cu) u=cu;
          }
          if(u) locItems.push({ url:u, label:String(s.note||"Location reference").replace(/\s+\([^)]*\)$/,""), kind:"location", refId:s.id });
        }
      }
      const castItems = []; for(const c of subjects){ const u=await grab(c.id); if(u) castItems.push({ url:u, label:c.name, kind:"character", refId:c.id }); }
      const propItems = []; for(const p of inProps){ const u=await grab(p.id); if(u) propItems.push({ url:u, label:p.name, kind:"prop", refId:p.id }); }
      const sheetOrder = (locWeight==="ambient") ? [...castItems, ...locItems, ...propItems] : [...locItems, ...castItems, ...propItems];
      if(alive) setRefImgs([...seed, ...sheetOrder]);
    })();
    return ()=>{ alive=false; };
  },[_refKey]);

  const beatLabel = "Beat "+(sh.beatN||"\u2014");
  const initials = (sizeOf(sh.size).label||"SH");
  const waitingForShot = !!(batchActiveId && batchActiveId!==sh.id);

  return _el("div",{className:"sheet-card shot-card"+(batchActiveId===sh.id?" batch-on":""),"data-shot-card":sh.id},
    _el(SheetFrame,{ gen:genGuarded, slotId:"shot-"+sh.id, name:beatLabel, avatarColor:"linear-gradient(135deg,#7a6cae,#2a2440)",
      initials, drafted:true, drafting:false, onDraft:()=>{}, entity:sh, onView,
      slotPlaceholder:"Generate or drop a frame", noun:"frame", dropToImport:true, onStop:onStopChain,
      generateDisabled:waitingForShot,
      generateDisabledLabel:"Wait for current shot",
      generateDisabledTitle:"Another shot is generating. Wait for it to finish before starting this frame.",
      menuExtra: [
        onRegenDownstream ? {
          label:"Regenerate downstream",
          title:"Re-render every later shot in this scene in order, re-seeding each from the one before — use after changing this frame so propagated state stays current.",
          onClick:()=>onRegenDownstream(sh),
        } : null,
      ].filter(Boolean),
      extraMeta:[
        { k:"Size",  v: sizeOf(sh.size).label + (sizeOf(sh.size).name?(" — "+sizeOf(sh.size).name):"") },
        { k:"Angle", v: angleOf(sh.angle).label },
        { k:"Move",  v: moveOf(sh.move).label },
        { k:"Lens",  v: lensOf(sh.lens).label },
      ],
      onDelete:()=>onDelete(sh.id), deleteLabel:"Delete shot" }),
    _el("div",{className:"sheet-body"},
      // reference images this frame is built from — the rolling SEED (the previous shot's
      // frame) leads, then the in-frame Character, Prop & Location sheets, ordered by weight.
      // Click a thumb to enlarge. Read-only: who/what is in frame is auto-read from the Action.
      refImgs.length>0 && _el("div",{className:"shot-refs"},
        _el("div",{className:"shot-refs-row"},
          refImgs.map((r,i)=>{
            // sheet refs are TICKABLE: unticked ids live on sh.refOff and drop out of the
            // attachment list + the prompt's image map together (the entity stays in the
            // staging text — only its sheet is withheld). The seed isn't tickable: skipping
            // the chain seed is what the "Fresh start" head toggle is for.
            const off = r.refId!=null && (sh.refOff||[]).indexOf(r.refId)>=0;
            return _el("div",{key:"a"+i,role:"button",tabIndex:0,
              className:"shot-ref-thumb "+r.kind+(r.kind==="seed"&&r.approved===false?" provisional":"")+(off?" off":""),
              title:(r.kind==="seed" ? (r.label+" — "+(r.approved?"approved seed":"provisional seed (not yet approved)")) : r.label)
                +(off?" — EXCLUDED from generation":"")+" — click to enlarge",
              onClick:()=>onView&&onView(r.url,{name:r.label}),
              onKeyDown:(e)=>{ if(e.key==="Enter"||e.key===" "){ e.preventDefault(); onView&&onView(r.url,{name:r.label}); } }},
              _el("img",{src:r.url,alt:r.label,loading:"lazy"}),
              r.kind==="seed" && _el("span",{className:"shot-ref-seedtag"+(r.approved?" ok":"")}, r.approved?"✓":"·"),
              r.refId!=null && _el("button",{className:"shot-ref-tick"+(off?"":" on"),
                title: off ? "Excluded — this sheet is NOT attached to the generation. Click to re-attach it."
                  : "Attached as a reference. Click to exclude this sheet from the generation (the "+(r.kind==="location"?"set":r.kind)+" stays in the prompt text; only the image is withheld).",
                onClick:(e)=>{ e.stopPropagation(); const cur=sh.refOff||[];
                  onUpdate(sh.id,{ refOff: off ? cur.filter(x=>x!==r.refId) : [...cur, r.refId] }); }},
                off ? "✕" : "✓")); }))),
      _el("div",{className:"shot-head"},
        // order, left-to-right: Beat · Clip · Head · (Approve, once a frame exists)
        _el("div",{className:"shot-head-right"},
          _el("div",{className:"shot-beat-tag"},beatLabel),
          subLabel && _el("div",{className:"shot-beat-tag sub",title:"This beat has multiple shots (coverage) — this is setup "+subLabel+" in cut order"},"Shot "+subLabel),
          sh.priority && _el("span",{className:"shot-priority-badge",
            title:"Priority — the setup carrying this beat's emotional core (the protected moment). Spend your regeneration attention here first, and approve it carefully as a seed."},
            _el(Icon.bolt,{s:10}),"Priority"),
          // chain head — the scene's first shot is always a head; flagging a later shot
          // starts a FRESH look (a hard cut that won't inherit the previous frame's state)
          _el("button",{className:"shot-anchor-btn"+(isHead?" on":""), disabled:isFirst,
            title: isFirst
              ? "This is the scene's first shot — always the chain head; the scene's whole look starts here."
              : (isHead
                ? "This shot is a FRESH START (chain break) — it won't be seeded by the previous frame. Click to rejoin the chain."
                : "Make this a fresh start — a hard cut that won't inherit the previous frame's look or state."),
            onClick:()=> !isFirst && onToggleHead && onToggleHead(sh)},
            _el(Icon.pin,{s:11}), isHead && _el("span",null, isFirst?"Head":"Fresh")),
          // approve / lock — marks this frame as the APPROVED seed the next shot chains from
          gen.genUrl && _el("button",{className:"shot-lock-btn"+(sh.locked?" on":""),
            title: sh.locked
              ? "Approved — this frame is the locked coverage reference this beat's shots build on. Click to unlock."
              : "Approve this frame as the coverage reference this beat's shots build on.",
            onClick:()=>onUpdate(sh.id,{ locked: !sh.locked })},
            _el(Icon.check,{s:11}), _el("span",null, sh.locked?"Approved":"Approve")),
          window.QaCheckButton && _el(window.QaCheckButton,{ gen, name:beatLabel, noun:"shot frame", className:"shot-lock-btn",
            specFields:()=>({ action:(sh.action||""), composition:(sh.composition||"") }),
            onApplySpec:(patch)=>onUpdate(sh.id, patch) }))),

      // the SCRIPT BEAT this shot covers — straight from the scene's beat map, so the
      // shot's source text is on the card (read-only; edit beats in the Writers' Room)
      beatText && _el("div",{className:"shot-beat-script",
        title:"This beat's SCREENPLAY text — the canon these shots film (until the scene is drafted, the beat summary stands in). Read-only here — edit the script in the Writers' Room."},
        _el("span",{className:"shot-beat-script-lab"},"Scripted"),
        _el("span",{className:"shot-beat-script-body"},beatText)),

      // WHY this shot exists (the designer's purpose) + which micro-beats it covers
      (sh.purpose || (Array.isArray(sh.covers)&&sh.covers.length>0)) && _el("div",{className:"shot-purpose"},
        (Array.isArray(sh.covers)&&sh.covers.length>0) && _el("span",{className:"shot-covers-chip",
          title:"The micro-beats of this beat that this shot covers (see the numbered rail above the shots)"},
          "covers "+sh.covers.map(_circ).join(" ")),
        sh.purpose && _el("span",{className:"shot-purpose-t"},sh.purpose)),

      // cinematographer grammar
      _el("div",{className:"shot-grammar-grid"},
        _el(GrammarSelect,{label:"Size",value:sh.size,options:SHOT_SIZES,onChange:v=>onUpdate(sh.id,{size:v})}),
        _el(GrammarSelect,{label:"Angle",value:sh.angle,options:SHOT_ANGLES,onChange:v=>onUpdate(sh.id,{angle:v})}),
        _el(GrammarSelect,{label:"Move",value:sh.move,options:SHOT_MOVES,onChange:v=>onUpdate(sh.id,{move:v})}),
        _el(GrammarSelect,{label:"Lens",value:sh.lens,options:SHOT_LENSES,onChange:v=>onUpdate(sh.id,{lens:v})})),

      _el(AdvancedCameraSettings,{sh,onUpdate}),

      // the action — what we see in this frame
      _el(SheetField,{label:"Action \u2014 what we see in this frame",value:sh.action,multiline:true,
        placeholder:"One vivid present-tense beat of on-screen action\u2026",onCommit:v=>onUpdate(sh.id,{action:v})}),
      dropped && _el("div",{className:"shot-dropped",
        title:"Named in the micro-beats this shot covers, but missing from its Action text. The render will try to merge them back in via the scripted canon, but the frame may still drop them — edit the Action to re-include them deliberately."},
        "\u26a0 Dropped from action: ", _el("b",null, dropped.join(", ")),
        " \u2014 named in covered micro-beats, missing from the action"),

      // composition (the depth-grid "vary" layer) + dialogue
      _el(SheetField,{label:"Composition \u2014 framing, blocking, depth, eyeline",value:sh.composition,multiline:true,
        placeholder:"Where subjects sit in frame, foreground/background, eyeline\u2026",onCommit:v=>onUpdate(sh.id,{composition:v})}),
      // multiline: dialogue lines routinely outgrow a single-line input, which clipped
      // them visually (the full text was stored, just unreadable/uneditable)
      _el(SheetField,{label:"Dialogue (optional)",value:sh.dialogue,multiline:true,
        placeholder:"A short line spoken in this beat\u2026",onCommit:v=>onUpdate(sh.id,{dialogue:v})}),

      // the director's own prompt words — compiled into the spec as custom_directives
      // on every rebuild, so they survive sheet/style changes and never fork the prompt
      _el(SheetField,{label:"Director's notes \u2014 extra prompt directives (optional)",value:sh.directives,multiline:true,
        placeholder:"Your own words for the generator \u2014 atmosphere, camera nuance, performance notes\u2026 These compose INTO the prompt; the derived spec (references, cast, style) stays intact.",
        onCommit:v=>onUpdate(sh.id,{directives:v})}),

      _el(CardFold,{label:"In frame",defaultOpen:false},
        // read-only: derived from the action text, the single source the prompt uses —
        // no manual toggles to drift out of sync. Edit the ACTION to change who's in frame.
        _el("div",{className:"shot-inframe-auto"},
          _el("div",{className:"shot-inframe-row"},
            _el("span",{className:"shot-frame-lab"},"Characters"),
            subjects.length
              ? subjects.map(c=>_el("span",{key:c.id,className:"shot-inframe-chip"},c.name))
              : _el("span",{className:"shot-inframe-none"},"none named in the action")),
          _el("div",{className:"shot-inframe-row"},
            _el("span",{className:"shot-frame-lab"},"Props"),
            inProps.length
              ? inProps.map(p=>_el("span",{key:p.id,className:"shot-inframe-chip prop"},p.name))
              : _el("span",{className:"shot-inframe-none"},"none named in the action")),
          _el("div",{className:"shot-inframe-hint"},
            _el(Icon.sparkles,{s:11}),"Auto-read from the action — edit the Action line to change who/what is in frame.")),
        _el("div",{className:"shot-loc-note"},
          _el(Icon.globe,{s:12}),
          loc ? _el("span",null,"Location: ",_el("b",null,loc.name),(typeof stagingHasContent==="function"&&stagingHasContent(loc))?" \u00b7 depth grid inherited":" \u00b7 no depth grid staged")
              : _el("span",null,"No location resolved for this scene \u2014 set the scene's slugline / pull locations."))),

      _el(CardFold,{label:"Shot prompt",defaultOpen:false},
        _el(CopyBox,{label: isHead ? "Final frame prompt \u2014 master + grade + references" : "Final frame prompt \u2014 master + grade + reference frame + sheets",text:previewPrompt}),
        _el(SheetField,{label:"Negative prompt \u2014 exclude",value:sh.negativePrompt||"",multiline:true,
          placeholder:shotNegativePrompt({}),onCommit:v=>onUpdate(sh.id,{negativePrompt:v})}))));
}

const CONF_LABELS = ["Inner","Personal","Extra-personal"];
function SceneCtxItem({ k, v }){
  if(!v) return null;
  return _el("div",{className:"ssx-item"}, _el("div",{className:"ssx-k"},k), _el("div",{className:"ssx-v"},v));
}

function SceneStyleChip({ project, sceneId }){
  // Keep this live: Shots should never cache a scene's style on the shot card.
  // The Styles tab owns the scene→preset map, so every Shots render resolves the
  // current assignment from project.styleBible.
  const preset = (typeof scenePreset==="function") ? scenePreset(project, sceneId) : null;
  if(!preset) return _el("span",{className:"shot-style-chip empty",title:"No Style Bible preset assigned to this scene yet. Use the Styles tab / Light the film."},
    _el(Icon.layers,{s:11}),"No style preset");
  const pal = (preset.palette||[]).slice(0,3);
  const title = [
    preset.name || "Scene style",
    preset.grade,
    preset.lighting ? ("Lighting: "+preset.lighting) : "",
    preset.lens ? ("Lens: "+preset.lens) : "",
    preset.texture ? ("Texture: "+preset.texture) : "",
  ].filter(Boolean).join("\n");
  return _el("span",{className:"shot-style-chip",title},
    _el(Icon.layers,{s:11}),
    _el("span",{className:"shot-style-chip-text"},"Style: "+(preset.name||"Scene preset")),
    !!pal.length && _el("span",{className:"shot-style-swatches"},
      pal.map((c,i)=>_el("span",{key:i,className:"shot-style-swatch",style:{background:c}}))));
}

/* the beat's SCREENPLAY text (action lines + cued dialogue) — the canon the
   shots film. Empty when the scene isn't drafted yet (callers fall back to the
   beat-map summary). Blocks are beat-tagged by the drafters. */
function beatScriptText(sceneId, n){
  const C=window.turnContinuity||{}; const d=(C.drafts||{})[sceneId];
  if(!d||!Array.isArray(d.blocks)) return "";
  const parts=[]; const blocks=d.blocks.filter(b=>Number(b.beat)===Number(n));
  for(let i=0;i<blocks.length;i++){ const b=blocks[i]; const t=String(b.text||"").replace(/\s+/g," ").trim(); if(!t) continue;
    if(b.type==="scene"||b.type==="trans"||b.type==="paren"||b.type==="dia") continue;
    if(b.type==="char"){ const nx=blocks[i+1]; if(nx&&nx.type==="dia"&&String(nx.text||"").trim()){ parts.push(t+": \u201c"+String(nx.text).replace(/\s+/g," ").trim()+"\u201d"); i++; } continue; }
    parts.push(t); }
  return parts.join("  ");
}

/* legacy micro-beats were clipped to 180 chars with a baked-in "\u2026" at drafting.
   Heal them against the beat's SCREENPLAY canon (where the micro-beat text was derived
   from): find the clipped prefix in the canon and extend to the end of that sentence.
   Never invents — if the canon no longer contains the prefix, the clipped text stands. */
function microHealText(text, canon){
  const t = String(text||"").trim();
  if(!/\u2026\s*$/.test(t)) return t;
  const prefix = t.replace(/\u2026\s*$/,"").trim();
  if(prefix.length < 12) return t;
  const cn = String(canon||"");
  if(!cn) return t;
  const words = prefix.split(/\s+/).filter(Boolean).slice(0, 12)
    .map(w=>w.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"));
  if(!words.length) return t;
  let m = null;
  try{ m = (new RegExp(words.join("\\W+"), "i")).exec(cn); }catch(e){ return t; }
  if(!m) return t;
  const from = m.index + m[0].length;
  // sentence end: punctuation optionally followed by a closing quote/bracket, then
  // whitespace or end-of-text — plain /[.!?](?=\s|$)/ over-extends past ." or .”
  const stop = cn.slice(from).search(/[.!?][\u201D\u201C"')\]\u2019]*(?=\s|$)/);
  const end = stop>=0 ? from + stop + 1 : cn.length;
  return cn.slice(m.index, end).replace(/\s+/g," ").trim();
}
window.microHealText = microHealText;
function _circ(n){ return (n>=1&&n<=20) ? String.fromCharCode(0x245F+n) : ("#"+n); }
/* MICRO-BEAT COVERAGE \u2014 which micro-beats each shot films.
   A shot's explicit `covers` array is the truth and always wins. A shot WITHOUT covers is
   only inferred when the rest of the beat IS mapped (so this shot is the anomaly \u2014 a
   hand-added shot, or one the designer left untagged): geometric-mean token overlap (the
   same similarity realignBlockBeats uses) with a 2-token floor, so one shared common word
   can never "cover" a micro-beat, and NO best-match fallback \u2014 a shot that matches nothing
   covers nothing rather than silently claiming micro-beat 1.
   When NO shot in the beat carries covers, the beat predates the micro-beat layer and we
   have no coverage data at all: `mapped:false` tells the UI to claim NEITHER covered nor
   uncovered, instead of inventing a signal in one direction.
   Returns { map: {shotId -> Set(1-based micro numbers)}, mapped: boolean }. */
const _MB_STOP = new Set(("the and a an of to in on at as is are was were be been being for with into from over under this that it its his her hers him she they them their then out off up down back again while when where who how not no one two has had have does did doing goes go get gets"
  ).split(" "));
function _mbToks(s){ const set=new Set(); String(s||"").toLowerCase().replace(/[^a-z0-9 ]+/g," ").split(/\s+/).forEach(w=>{ if(w.length>=3 && !_MB_STOP.has(w)) set.add(w); }); return set; }
/* is a micro-beat VISUALLY described by a shot? Same token test microCoverage uses, but
   restricted to the frame-facing fields (action + composition — not dialogue), so it
   measures what the frame would SHOW rather than what the story covers. */
function _mbShown(sh, microText){
  const st = _mbToks((sh.action||"")+" "+(sh.composition||""));
  const rt = _mbToks(microText);
  let hit=0; st.forEach(w=>{ if(rt.has(w)) hit++; });
  return hit>=2 && (hit/Math.sqrt((st.size||1)*(rt.size||1))) >= 0.34;
}
function microCoverage(shots, microTexts, opts){
  const rowToks = (microTexts||[]).map(_mbToks);
  const list = shots || [];
  // no shots at all → nothing films anything, so the uncovered flags ARE the right signal.
  // opts.force (Stage's text resolver): run fuzzy inference even when NO shot carries
  // explicit covers — the mapped gate exists so the UI never invents a coverage signal,
  // but a best-effort text match is exactly right when deriving prompt canon for legacy
  // shots. Per-shot thresholds (hit>=2, cosine>=0.34) are list-independent, so a
  // singleton call under force yields the same set a beat-wide call would.
  const mapped = !!((opts&&opts.force) || !list.length || list.some(sh=>Array.isArray(sh.covers) && sh.covers.length>0));
  const map = {};
  list.forEach(sh=>{
    if(Array.isArray(sh.covers) && sh.covers.length){ map[sh.id] = new Set(sh.covers); return; }
    const set = new Set();
    if(mapped){
      const st = _mbToks((sh.action||"")+" "+(sh.dialogue||"")+" "+(sh.composition||""));
      rowToks.forEach((rt,i)=>{
        let hit=0; st.forEach(w=>{ if(rt.has(w)) hit++; });
        if(hit>=2 && (hit/Math.sqrt((st.size||1)*(rt.size||1))) >= 0.34) set.add(i+1);
      });
    }
    map[sh.id] = set;
  });
  return { map, mapped };
}
window.microCoverage = microCoverage;
/* live keyframe url for a shot id: sync cache, async IDB hydrate, adopt fresh gens */
function useShotKeyframe(shotId){
  const [url,setUrl]=React.useState(()=> shotId && (typeof nbGetImage==="function") ? nbGetImage(shotId) : "");
  React.useEffect(()=>{ let alive=true;
    if(!shotId) return;
    setUrl((typeof nbGetImage==="function")?nbGetImage(shotId):"");
    if(typeof nbLoadImage==="function") nbLoadImage(shotId).then(u=>{ if(alive&&u) setUrl(u); });
    const onDone=(e)=>{ if(alive&&e.detail&&e.detail.id===shotId&&e.detail.url) setUrl(e.detail.url); };
    const onPre=(e)=>{ if(alive&&e.detail&&e.detail.ids&&e.detail.ids.indexOf(shotId)>=0){ const u=(typeof nbGetImage==="function")?nbGetImage(shotId):""; if(u) setUrl(u); } };
    window.addEventListener("nb-gen-done",onDone); window.addEventListener("nb-prefetched",onPre);
    return ()=>{ alive=false; window.removeEventListener("nb-gen-done",onDone); window.removeEventListener("nb-prefetched",onPre); };
  },[shotId]);
  return url;
}

/* one compact row per shot inside a BEAT CARD — click to expand the full editor */
function BeatShotRow({ sh, letter, open, onToggle, isNext }){
  const url = useShotKeyframe(sh.id);
  return _el("div",{className:"bc-shot-row"+(open?" on":"")+(isNext?" next":""),role:"button",tabIndex:0,onClick:onToggle,
    title:open?"Collapse this shot":"Open this shot (frame, references, grammar, action)"},
    url ? _el("img",{className:"bc-shot-thumb",src:url,alt:""}) : _el("span",{className:"bc-shot-thumb ph"}),
    _el("span",{className:"bc-shot-letter"},letter),
    isNext && _el("span",{className:"bc-next-chip",
      title:"NEXT IN THE ROLLING CHAIN \u2014 this frame renders next; later shots seed from it. Open it and Generate, or use 'Render Scene in order'."},"\u25b8 next"),
    sh.priority && _el("span",{className:"bc-shot-pri",title:"Priority — carries the beat's protected moment"},"\u2605"),
    _el("span",{className:"bc-shot-gram"},String(sh.size||"")+" \u00b7 "+String(sh.angle||"")+" \u00b7 "+String(sh.lens||"")+"mm"),
    _el("span",{className:"bc-shot-act"},String(sh.action||"")),
    (Array.isArray(sh.covers)&&sh.covers.length>0) && _el("span",{className:"bc-shot-covers"},"covers "+sh.covers.map(_circ).join(" ")),
    _el("span",{className:"bc-shot-chev"+(open?" open":"")},_el(Icon.chevR,{s:13})));
}

/* ONE CARD PER BEAT (user ruling 2026-07-21): the beat's first-shot keyframe as the
   card image, then Protect, the micro-beat checklist, and compact shot rows that
   expand into the full ShotCard editor. The Stage keeps consuming these shots for
   video clips — nothing about clip packing changes. */
function BeatCard({ L, lanesLen, bm, scene, ctx, characters, propsAvail, ordered, firstId, toggleHead,
  onAddShot, onUpdate, onDelete, onView, onGenerateShot, onRegenDownstream, onStopChain, onBatchDone,
  batchActiveId, openShotId, setOpenShotId, sceneStart, onRenderScene, renderBusy, nextShotId }){
  const beatRow = (bm.rows||[]).find(r=>String(r.n)===String(L.n));
  // the card quotes the SCREENPLAY (canon) for this beat; the beat-map summary
  // only stands in until the scene is drafted
  const beatText = beatScriptText(scene.id, L.n)
    || (beatRow ? [ (beatRow.drive&&beatRow.drive.d||"").trim(), (beatRow.react&&beatRow.react.d||"").trim() ].filter(Boolean).join(" \u2014 ") : "");
  const vDrive = beatRow ? String((beatRow.drive&&beatRow.drive.a)||"").trim() : "";
  const vReact = beatRow ? String((beatRow.react&&beatRow.react.a)||"").trim() : "";
  const isTurn = String(bm.turnAt||"")===String(L.n);
  const chg = beatRow && beatRow.charge!=null && beatRow.charge!=="" ? Number(beatRow.charge) : null;
  const plan = L.shots.map(x=>x.beatPlan).find(Boolean);
  // per-shot micro-beat coverage: explicit `covers` wins; untagged shots inside an
  // already-mapped beat are inferred conservatively. microMapped=false means the beat has
  // NO coverage data at all (pre-micro-beat draft) — the UI then claims neither way.
  const _mc = (plan && Array.isArray(plan.micro))
    ? microCoverage(L.shots, plan.micro.map(t=>String(t).replace(/^\s*\d+[\.\)]\s*/,"")))
    : { map:{}, mapped:true };
  const microCov = _mc.map, microMapped = _mc.mapped;
  const kf = useShotKeyframe(L.shots[0] ? L.shots[0].id : "");
  const letterOf = (i)=>String.fromCharCode(65+i);
  return _el("div",{className:"beat-card"+(isTurn?" turn":"")},
    kf
      ? _el("img",{className:"beat-card-img",src:kf,alt:"Beat "+L.n+" keyframe",
          title:"This beat's opening keyframe (its first shot's frame) — click to enlarge",
          onClick:()=>onView&&onView(kf,{name:scene.title+" \u2014 Beat "+L.n})})
      : (sceneStart && onRenderScene
        // THE tab's "start here": an unrendered scene's FIRST card carries the
        // primary action right where the missing image is
        ? _el("div",{className:"beat-card-img ph cta"},
            _el("div",{className:"bc-cta-t"},"This scene's frames haven't been rendered yet"),
            _el("button",{className:"char-draft-btn primary bc-cta-btn",disabled:!!renderBusy,
              title:"Render every shot in this scene in chain order, each seeded by its beat's coverage reference, auto-approving each as it goes",
              onClick:()=>onRenderScene(scene)},
              _el(Icon.sparkles,{s:13}),"Render Scene "+String(scene.no).padStart(2,"0")+" in order"),
            _el("div",{className:"bc-cta-d"},"Renders every frame in chain order \u2014 or open the \u25b8 next shot below and generate just its frame."))
        : _el("div",{className:"beat-card-img ph"},
            "Renders with the scene chain \u2014 or open a shot below to generate its frame")),
    _el("div",{className:"beat-card-body"},
      _el("div",{className:"beat-card-head"},
        _el("span",{className:"beat-lane-no"},"Beat "+L.n+(lanesLen>1?(" of "+lanesLen):"")),
        (vDrive||vReact) && _el("span",{className:"beat-lane-verbs",
          title:"Driver / reactor verbs for this beat \u2014 the BOLD verb is the side that carries the beat's charge (positive = the drive lands, negative = the reaction dominates)"},
          vDrive && _el("span",{className:"bv"+(chg!=null&&chg>0?" lead":"")},vDrive),
          (vDrive&&vReact) && " / ",
          vReact && _el("span",{className:"bv"+(chg!=null&&chg<0?" lead":"")},vReact)),
        isTurn && _el("span",{className:"beat-lane-turn"},_el(Icon.bolt,{s:10}),"Turning point"),
        (chg!=null) && _el("span",{className:"beat-lane-chg "+(chg>0?"pos":chg<0?"neg":"")},(chg>0?"+":"")+chg),
        _el("span",{className:"beat-lane-count"},L.shots.length+" shot"+(L.shots.length!==1?"s":"")),
        onAddShot && _el("button",{className:"beat-lane-btn ghost bc-add",
          title:"Add one manual shot to this beat — it joins the rolling chain after the beat's last shot",
          onClick:()=>onAddShot(scene.id, L.n)},_el(Icon.plus,{s:11}),"Add shot")),
      // the BEAT itself (from the Writers' Room beat map): driver action | reactor
      // reaction — the dramatic exchange these shots film. Read-only; edit in Beats.
      beatRow && ((beatRow.drive&&beatRow.drive.d)||(beatRow.react&&beatRow.react.d)) && _el("div",{className:"bc-beat",
        title:"This beat from the Writers' Room beat map — the driver's action and the reactor's reaction. Read-only here; edit it on the Beats tab."},
        _el("div",{className:"bc-beat-grid"},
          _el("div",{className:"bc-beat-cell"},
            _el("div",{className:"bc-beat-name"},bm.driverLabel||"Driver"),
            (beatRow.drive&&beatRow.drive.a) && _el("div",{className:"bc-beat-verb"},beatRow.drive.a),
            _el("div",{className:"bc-beat-d"},(beatRow.drive&&beatRow.drive.d)||"")),
          _el("div",{className:"bc-beat-cell"},
            _el("div",{className:"bc-beat-name"},bm.reactorLabel||"Reactor"),
            (beatRow.react&&beatRow.react.a) && _el("div",{className:"bc-beat-verb"},beatRow.react.a),
            _el("div",{className:"bc-beat-d"},(beatRow.react&&beatRow.react.d)||"")))),
      plan && plan.protect && _el("div",{className:"beat-protect",
        title:"The beat's emotional core — the moment the coverage is built to protect. The \u2605 Priority shot carries it."},
        _el(Icon.bolt,{s:10}), _el("b",null,"Protect:"), " "+plan.protect),
      plan && Array.isArray(plan.micro) && plan.micro.length>0 && _el("div",{className:"bc-micro"},
        _el("div",{className:"bc-sec-lab"},"Micro-beats \u00b7 "+plan.micro.length),
        // this beat's shots carry no coverage data (drafted before the micro-beat layer):
        // say so ONCE, honestly, instead of flagging every row either way
        !microMapped && _el("div",{className:"bc-micro-nomap-note",
          title:"These shots were drafted before shots recorded which micro-beats they film, so the mapping is unknown. Re-draft this scene's shots to map them."},
          "Coverage for this beat isn't mapped \u2014 re-draft the scene's shots to map them."),
        plan.micro.map((m,i)=>{ const n=i+1;
          const covering = L.shots.map((sh,idx)=>({sh,idx})).filter(x=> microCov[x.sh.id] && microCov[x.sh.id].has(n));
          const flag = microMapped && !covering.length;   // genuinely unfilmed
          // SHOWN vs IMPLIED: coverage marks STORY coverage — a micro-beat is only SHOWN
          // when some covering shot's action/composition actually describes it (same
          // token test microCoverage uses); otherwise the frame will likely just imply it.
          const mTxt = String(m).replace(/^\s*\d+[\.\)]\s*/,"");
          const implied = covering.length>0 && !covering.some(x=>_mbShown(x.sh, mTxt));
          return _el("div",{key:n,className:"bc-micro-row"+(flag?" uncovered":"")},
            _el("span",{className:"bc-micro-t"},_circ(n)+" "+microHealText(mTxt, beatText)),
            covering.length
              ? _el("span",{className:"bc-micro-shots"},covering.map(x=>_el("button",{key:x.sh.id,className:"bc-micro-shotlink",
                  title:"Filmed in Shot "+letterOf(x.idx)+" \u2014 click to open it",
                  onClick:()=>setOpenShotId(x.sh.id)},letterOf(x.idx))),
                  implied && _el("span",{className:"bc-micro-implied",
                    title:"Story-covered, but no covering shot's Action describes it \u2014 the frame will likely only imply it. Put it in a shot's Action text to SHOW it."},"implied"))
              : flag
                ? _el("button",{className:"bc-micro-none",
                    title:"No shot films this action yet \u2014 click to ADD A SHOT pre-filled with this action (it joins the chain after the beat's last shot; the frame renders separately)",
                    onClick:()=> onAddShot && onAddShot(scene.id, L.n, { action:mTxt, covers:[n] })},
                    "uncovered \u2014 add shot")
                : _el("span",{className:"bc-micro-unknown",title:"Unknown \u2014 these shots don't record which micro-beats they film"},"\u2014"));
        })),
      _el("div",{className:"bc-shots"},
        _el("div",{className:"bc-sec-lab"},"Shots \u00b7 "+L.shots.length),
        L.shots.map((sh,i)=> _el(React.Fragment,{key:sh.id},
          _el(BeatShotRow,{sh,letter:letterOf(i),open:openShotId===sh.id,isNext:(sh.id===nextShotId),
            onToggle:()=>setOpenShotId(openShotId===sh.id?null:sh.id)}),
          openShotId===sh.id && _el("div",{className:"bc-shot-expand"},
            (()=>{ const prevShot=(typeof seedShotOf==="function")?seedShotOf(sh,ordered)
                :((typeof prevShotOf==="function")?prevShotOf(sh,ordered):null);
              const _si=ordered.findIndex(x=>x.id===sh.id);
              return _el(ShotCard,{sh,scene,ctx,characters,propsAvail,beatText,prevShot,plan,
                laterShots:(_si>=0?ordered.slice(_si+1):[]), isHead:!prevShot, isFirst:(sh.id===firstId), onToggleHead:toggleHead,
                onUpdate,onDelete,onView,batchActiveId,onBatchDone,onGenerateShot,onRegenDownstream,onStopChain,
                subLabel:(L.shots.length>1?letterOf(i):null)}); })()))))));
}

function SceneShotGroup({ scene, shots, ctx, characters, propsAvail, beatsMap, pager, onUpdate, onDelete, onView,
  onAddShot, onSplitBeat, splittingBeat, onDraftScene, draftingScene, batchActiveId, onBatchDone, open, onToggle, onGenerateShot, onRegenDownstream,
  onRenderScene, renderBusy, queueMode, onStopChain }){
  const loc = ctx.location;
  const driver = scene.driver ? ctx.charById[scene.driver] : null;
  // scene-level context (driver/reactor/antagonism/goal/conflict) — driver+goal+conflict from the
  // Scene inspector, reactor+antagonism from the beat-map, exactly as the Writers' Room shows them.
  const bm = (beatsMap||{})[scene.id] || {};
  const driverName = driver ? driver.name : (bm.driverLabel||"");
  const confLab = scene.conf ? CONF_LABELS[scene.conf-1] : "";
  // the rolling chain: shots render in order, each seeding from its predecessor. The first
  // shot is always the chain HEAD; a shot flagged .anchor is an explicit FRESH START (a hard
  // cut mid-scene that won't inherit the previous frame). toggleHead flips that flag.
  const ordered = (typeof sceneShotsOrdered==="function") ? sceneShotsOrdered(shots) : shots;
  // BEAT LANES model: one card for EVERY Writers' Room beat, even if the shot
  // designer missed it. Orphan/manual shots with non-map beat numbers are kept
  // after the canonical beat cards instead of silently disappearing.
  const lanes = (()=>{
    const rows = Array.isArray(bm.rows) ? bm.rows : [];
    const byBeat = {};
    // dedupe by shot id: a duplicated shots array (stale local doc / merge hiccup) must
    // not double-render rows or collide React keys — the first occurrence wins
    const seenShotIds = new Set();
    let dupShots = 0;
    ordered.forEach(sh=>{
      if(!sh || seenShotIds.has(sh.id)){ if(sh) dupShots++; return; }
      seenShotIds.add(sh.id);
      const n = Number(sh.beatN)||0; (byBeat[n]=byBeat[n]||[]).push(sh); });
    const seen = new Set();
    const Ls = [];
    let dupRows = 0;
    rows.forEach((r,i)=>{
      const n = Number(r && r.n)||i+1;
      // dedupe beat rows by number: a stale/merged beat map with the same beat listed
      // twice must not render the beat's card twice (duplicate React keys + flicker)
      if(seen.has(n)){ dupRows++; return; }
      seen.add(n);
      Ls.push({ n, shots:byBeat[n]||[], canonical:true });
    });
    // diagnostic trail: if the dedupe ever actually drops something, say so — this
    // confirms WHERE upstream state churn is duplicating (stale local doc, sync merge)
    if((dupRows||dupShots) && typeof console!=="undefined" && console.warn){
      console.warn("[shots] dropped duplicate lane content for scene "+(scene && scene.id)
        +": "+dupRows+" duplicate beat row(s), "+dupShots+" duplicate shot(s). "
        +"The beat map / shot list arrived duplicated (stale local doc or sync merge) — the dedupe kept the grid single.");
    }
    Object.keys(byBeat).map(Number).sort((a,b)=>a-b).forEach(n=>{
      if(!seen.has(n)) Ls.push({ n, shots:byBeat[n]||[], canonical:false });
    });
    if(!Ls.length && ordered.length){
      ordered.forEach(sh=>{ const n=Number(sh.beatN)||0;
        let L=Ls[Ls.length-1]; if(!L || L.n!==n){ L={ n, shots:[] }; Ls.push(L); } L.shots.push(sh); });
    }
    return Ls;
  })();
  // ONE CARD PER BEAT (user ruling 2026-07-21): all beats list vertically as cards —
  // and STAY as cards through queue renders (user ruling 2026-08-01): the queue's
  // active ShotCard mounts off-screen as the runner's driver (see the grid render
  // below). openShotId = the one shot expanded into its full editor.
  const [openShotId, setOpenShotId] = React.useState(null);
  const batchMode = !!queueMode;
  // merged scene navigator: the click-to-jump scene list in this card's header
  const [jumpOpen, setJumpOpen] = React.useState(false);
  React.useEffect(()=>{ if(!jumpOpen) return;
    const close=(e)=>{ if(!e.target.closest || !e.target.closest(".ssg-jump")) setJumpOpen(false); };
    document.addEventListener("mousedown", close); return ()=>document.removeEventListener("mousedown", close); },[jumpOpen]);
  const firstId = ordered[0] && ordered[0].id;
  const toggleHead = (target)=> { if(target && target.id!==firstId) onUpdate(target.id, { anchor: !target.anchor }); };
  // the scene's clip sequences (shared partition — Storyboard clip boards + the Stage);
  // the per-clip budget comes from the project FORMAT (clipMaxFor)
  const clipMax = (typeof clipMaxFor==="function") ? clipMaxFor(ctx.project) : 15;

  // WHOLE-SCENE video prompt — the shared builder (shots.jsx sceneVideoPromptText):
  // the same text the Stage's whole-scene packing mode auto-fills its prompt box with.
  // Speaker attribution rides the Stage's resolver (no script drafts in this scope,
  // so it leans on the beat map + action-order fallback).
  const sceneVideoPrompt = ()=> (typeof window.sceneVideoPromptText==="function")
    ? window.sceneVideoPromptText(scene, ordered, { location:loc, project:ctx.project,
        speakerOf:(sh)=> (typeof stageDialogueSpeaker==="function")
          ? ((stageDialogueSpeaker(scene, null, beatsMap, sh, { characters, charById:ctx.charById })||{}).name||"")
          : "" })
    : "";
  const copyScenePrompt = async ()=>{
    const t = sceneVideoPrompt();
    if(!t){ if(window.appToast) window.appToast("No shot actions yet — draft this scene's shots first."); return; }
    // belt & braces: async clipboard API first, execCommand fallback second (covers
    // non-secure contexts), manual dialog last — and the toast only claims success
    // when a copy REALLY landed.
    let ok = false;
    try{ if(navigator.clipboard && navigator.clipboard.writeText){ await navigator.clipboard.writeText(t); ok = true; } }catch(e){}
    if(!ok){ try{
      const ta = document.createElement("textarea"); ta.value = t;
      ta.style.position = "fixed"; ta.style.opacity = "0";
      document.body.appendChild(ta); ta.select();
      ok = document.execCommand("copy");
      document.body.removeChild(ta);
    }catch(e){} }
    if(ok){ if(window.appToast) window.appToast("Scene "+String(scene.no).padStart(2,"0")+" video prompt copied — "+ordered.length+" shot"+(ordered.length===1?"":"s")+" combined"); }
    else window.prompt("Copy the scene video prompt:", t);
  };
  return _el("div",{className:"shot-scene-group"+(open?"":" collapsed")},
    // ONE merged card (user ruling 2026-07-19): scene navigator + title/style/meta +
    // context grid, redundancy removed (number/driver/location each said once).
    // "Copy video prompt" retired (clips live on the Stage); scene-level "Add shot"
    // retired (every beat lane header has its own "Add shot").
    _el("div",{className:"shot-scene-card"},
    _el("div",{className:"shot-scene-head merged"},
      pager && _el("button",{className:"scene-pager-arrow",disabled:pager.idx<=0,onClick:pager.onPrev,
        title:"Previous scene (\u2190)","aria-label":"Previous scene"},_el(Icon.chevL,{s:18})),
      _el("div",{className:"shot-scene-meta"},
        pager && _el("span",{className:"scene-pager-no ssg-jump",role:"button",tabIndex:0,title:"Jump to a scene",
          onClick:()=>setJumpOpen(o=>!o)},
          "Scene "+(pager.idx+1)+" of "+pager.total, _el(Icon.chevD,{s:10}),
          jumpOpen && _el("div",{className:"scene-pager-menu",onClick:(e)=>e.stopPropagation()},
            pager.scenes.map((sx,i)=>_el("button",{key:sx.id||i,className:"scene-pager-menu-item"+(i===pager.idx?" on":""),
              onClick:()=>{ pager.onJump(i); setJumpOpen(false); }},
              _el("span",{className:"scene-pager-menu-no"},String(sx.no||(i+1)).padStart(2,"0")),
              _el("span",{className:"scene-pager-menu-t"},sx.title||"Untitled scene"),
              i===pager.idx && _el(Icon.check,{s:13}))))),
        _el("div",{className:"shot-scene-title"},scene.title||"Untitled scene"),
        _el("div",{className:"shot-scene-style-row"},_el(SceneStyleChip,{project:ctx.project,sceneId:scene.id})),
        _el("div",{className:"shot-scene-sub"},
          (loc?("Location: "+loc.name+"   \u00b7   "):"")+shots.length+" shot"+(shots.length!==1?"s":"")),
        // shots-per-beat strip: coverage distribution at a glance (widths ∝ shot counts)
        (lanes.length>1) && _el("div",{className:"ssx-beat-strip",
          title:"Shots per beat \u2014 how this scene's coverage is distributed"},
          lanes.map(L=>_el("span",{key:"bb"+L.n,className:"ssx-beat-seg",
            style:{flexGrow:Math.max(1,L.shots.length)},
            title:"Beat "+L.n+" \u2014 "+L.shots.length+" shot"+(L.shots.length!==1?"s":"")},
            L.shots.length)))),
      _el("div",{className:"shot-scene-acts"},
        onRenderScene && _el("button",{className:"char-draft-btn primary",disabled:!!renderBusy,onClick:()=>onRenderScene(scene),
          title:"Render this scene in order, each shot seeded by its beat's coverage reference (a beat's opener chains from the previous beat), auto-approving each. Approved frames are retained as seeds."},
          _el(Icon.sparkles,{s:12}), renderBusy?"Rendering\u2026":("Render Scene "+String(scene.no).padStart(2,"0")+" in order")),
        _el("button",{className:"char-draft-btn ghost"+(draftingScene?" busy":""),disabled:!!draftingScene,onClick:()=>onDraftScene(scene),
          title:"Re-derive this scene's shot list from its beats (replaces the current shots)"},
          _el(Icon.layers,{s:12}), draftingScene?"Drafting\u2026":"Re-draft shots")),
      pager && _el("button",{className:"scene-pager-arrow",disabled:pager.idx>=pager.total-1,onClick:pager.onNext,
        title:"Next scene (\u2192)","aria-label":"Next scene"},_el(Icon.chevR,{s:18}))),
    open && _el("div",{className:"shot-scene-ctx"},
      scene.summary && _el("div",{className:"ssx-desc"},scene.summary),
      _el("div",{className:"ssx-grid"},
        _el(SceneCtxItem,{k:"Driver",v:driverName}),
        _el(SceneCtxItem,{k:"Reactor",v:bm.reactorLabel}),
        _el(SceneCtxItem,{k:"Driver's goal",v:scene.objective}),
        _el(SceneCtxItem,{k:"Antagonism",v:bm.obstacle}),
        scene.conf && _el("div",{className:"ssx-item"},
          _el("div",{className:"ssx-k"},"Conflict level"),
          _el("div",{className:"ssx-conf"},
            confLab && _el("span",{className:"ssx-conf-lab"},confLab),
            _el("div",{className:"ssx-pips"},
              [1,2,3].map(i=>_el("span",{key:i,className:"ssx-pip"+(i<=scene.conf?" on":"")})))))))),
    // BEAT CARDS — one card per beat (all beats listed), kept through queue renders
    // too (user ruling 2026-08-01: "Render Scene in order" must NOT swap the grid back
    // to the legacy full-card lanes). The chain runner still needs the ACTIVE shot's
    // ShotCard MOUNTED — it fires and confirms each generation — so during a queue
    // that one card mounts off-screen (display:none) alongside the grid.
    open && (()=>{
      const _kf=(id)=> (typeof nbGetImage==="function") ? !!nbGetImage(id) : false;
      const _sceneRendered = ordered.some(sh=>_kf(sh.id));
      const _nextShotId = (ordered.find(sh=>!_kf(sh.id))||{}).id || null;
      // the queue's off-screen driver: the active shot's full card — UNLESS the user
      // already has THAT shot expanded (an expanded card drives its own run; two
      // mounted cards for one shot would fire the same generation twice)
      const _drv = (batchMode && batchActiveId && openShotId!==batchActiveId)
        ? ordered.find(x=>x.id===batchActiveId) : null;
      let driverCard = null;
      if(_drv){
        const _dLane = lanes.find(L=>L.shots.some(x=>x.id===_drv.id)) || { n:Number(_drv.beatN)||0, shots:[_drv] };
        const beatRow=(bm.rows||[]).find(r=>String(r.n)===String(_dLane.n));
        const beatText=beatScriptText(scene.id, _dLane.n) || (beatRow?[ (beatRow.drive&&beatRow.drive.d||"").trim(), (beatRow.react&&beatRow.react.d||"").trim() ].filter(Boolean).join(" — "):"");
        const prevShot=(typeof seedShotOf==="function")?seedShotOf(_drv,ordered)
          :((typeof prevShotOf==="function")?prevShotOf(_drv,ordered):null);
        const _si=ordered.findIndex(x=>x.id===_drv.id);
        const _plan=_dLane.shots.map(x=>x.beatPlan).find(Boolean);
        driverCard = _el("div",{key:"drv-"+_drv.id,style:{display:"none"},"aria-hidden":"true"},
          _el(ShotCard,{sh:_drv,scene,ctx,characters,propsAvail,beatText,prevShot,plan:_plan,
            laterShots:(_si>=0?ordered.slice(_si+1):[]), isHead:!prevShot, isFirst:(_drv.id===firstId), onToggleHead:toggleHead,
            onUpdate,onDelete,onView,batchActiveId,onBatchDone,onGenerateShot,onRegenDownstream,onStopChain,
            subLabel:(_dLane.shots.length>1?String.fromCharCode(65+Math.max(0,_dLane.shots.findIndex(x=>x.id===_drv.id))):null)}));
      }
      return _el(React.Fragment,null,
        driverCard,
        _el("div",{key:"beat-grid",className:"beat-grid-wrap"+(draftingScene?" drafting":"")},
          // REDRAFT IN PROGRESS — visible on the canvas, not just the button: the
          // current cards dim (they stay until the new list lands) under a status card
          draftingScene && _el("div",{className:"beat-redraft-note"},
            _el("span",{className:"ns-spin"}),
            _el("div",{className:"brn-txt"},
              _el("div",{className:"brn-t"},"MUSE is re-designing Scene "+String(scene.no).padStart(2,"0")+"'s shots"),
              _el("div",{className:"brn-d"},"Beat-by-beat coverage from the beats + script — about a minute. The current shots stay until the new list lands (a failed draft changes nothing)."))),
          _el("div",{className:"beat-card-grid"},
            lanes.map((L,Li)=> _el(BeatCard,{key:"bc"+(L.canonical?"c":"o")+L.n, L, lanesLen:lanes.length, bm, scene, ctx, characters, propsAvail,
              ordered, firstId, toggleHead, onAddShot, onUpdate, onDelete, onView,
              onGenerateShot, onRegenDownstream, onStopChain, onBatchDone, batchActiveId, openShotId, setOpenShotId,
              sceneStart:(!_sceneRendered && Li===0), onRenderScene, renderBusy, nextShotId:_nextShotId })))));
    })());
}

function ShotList({ project, scenes, characters, props, locations, shots, beatsMap,
  onUpdateShot, onAddShot, onDeleteShot, onSplitBeat, splittingBeat, onDraftSceneShots, draftingSceneShots, onDraftAllShots, draftingAllShots, onShoot }){
  const [view, setView] = React.useState(null);
  const batch = useBatchGen();
  const batchActiveId = batch.activeId;
  // the rolling-keyframe CHAIN: render a scene's shots in order, each seeded by the previous
  // frame. Each rendered frame auto-locks (becomes the approved seed) and the chain continues.
  const [chain, setChain] = React.useState(null);   // { ids, idx, total } | null while running
  const chainRef = React.useRef(null); chainRef.current = chain;
  const chainStartingRef = React.useRef(false);
  // small centered popup — e.g. "generate the earlier shot first" when a chain is clicked
  // out of order. Auto-dismisses; click X/the scrim or press Esc to close sooner.
  const [notice, setNotice] = React.useState("");
  React.useEffect(()=>{
    if(!notice) return;
    const t = setTimeout(()=>setNotice(""), 4000);
    const onKey = (e)=>{ if(e.key==="Escape"){ e.preventDefault(); setNotice(""); } };
    window.addEventListener("keydown", onKey, true);
    return ()=>{ clearTimeout(t); window.removeEventListener("keydown", onKey, true); };
  },[notice]);
  // "Design all shots" is non-destructive — it only breaks down scenes that have NO shots yet.
  // Track how many it set out to do so we can show a live progress bar (and tell the user when
  // there's nothing to do, instead of the click appearing to do nothing).
  const scenesNeedingShots = ()=>{ const have = new Set((shots||[]).map(s=>s.sceneId)); return (scenes||[]).filter(s=>!have.has(s.id)); };
  const [designTotal, setDesignTotal] = React.useState(0);
  React.useEffect(()=>{ if(!draftingAllShots) setDesignTotal(0); },[draftingAllShots]);   // clear the bar when the run ends
  const handleDesignAll = ()=>{
    if(draftingAllShots) return;
    const need = scenesNeedingShots().length;
    if(!need){ setNotice("Every scene already has shots. Open a scene and use ‘Re-draft shots’ to redesign just that one."); return; }
    setDesignTotal(need);
    onDraftAllShots && onDraftAllShots();
  };
  // per-scene fold state (persisted). DEFAULT: everything folded except the first
  // scene — a long shot list opens scannable, not as one endless scroll.
  const [collapsed, setCollapsed] = React.useState(()=>{ try{ return JSON.parse(localStorage.getItem("turn_shots_collapsed")||"{}")||{}; }catch(e){ return {}; } });
  React.useEffect(()=>{ try{ localStorage.setItem("turn_shots_collapsed", JSON.stringify(collapsed)); }catch(e){} },[collapsed]);
  const toggleScene = (id)=> setCollapsed(c=>({ ...c, [id]: !c[id] }));
  // seed the default fold once scenes hydrate (an empty saved map = never touched)
  const foldSeeded = React.useRef(false);
  React.useEffect(()=>{
    if(foldSeeded.current || !(scenes||[]).length) return;
    foldSeeded.current = true;
    if(Object.keys(collapsed).length) return;   // the user has a real fold state already
    const m = {};
    scenesInStoryOrder(scenes).forEach((s,i)=>{ if(i>0) m[s.id]=true; });
    setCollapsed(m);
  },[(scenes||[]).length]);

  const charById = React.useMemo(()=>{ const m={}; (characters||[]).forEach(c=>m[c.id]=c); return m; },[characters]);
  const propById = React.useMemo(()=>{ const m={}; (props||[]).forEach(p=>m[p.id]=p); return m; },[props]);
  const shotById = React.useMemo(()=>{ const m={}; (shots||[]).forEach(s=>m[s.id]=s); return m; },[shots]);

  // one-time sanity pass: re-anchor each shot's subjects to the cast NAMED in its
  // action/composition text (earlier drafts could drift to background cast — e.g. a
  // beat about Amara getting tagged with other characters). Skips shots the user has
  // set by hand (subjectsSet), and only changes a shot when the text clearly names a
  // DIFFERENT set, so valid/pronoun-only shots are left alone.
  const subjFixed = React.useRef(false);
  React.useEffect(()=>{
    if(subjFixed.current || typeof scanTextForChars!=="function" || !(shots||[]).length) return;
    subjFixed.current = true;
    const beatActionOf = (sh)=>{ const b=(beatsMap||{})[sh.sceneId];
      const row = b && (b.rows||[]).find(r=>String(r.n)===String(sh.beatN));
      return row ? ((row.drive&&row.drive.d)||(row.react&&row.react.d)||"") : ""; };
    (shots||[]).forEach(sh=>{
      const patch = {};
      // backfill an empty action from its originating beat (a draft can leave it blank)
      let action = sh.action;
      if(!String(action||"").trim()){ const ba = beatActionOf(sh); if(ba){ action = ba; patch.action = ba; } }
      // re-anchor subjects to the (possibly backfilled) action text, unless set by hand
      if(!sh.subjectsSet){
        const named = scanTextForChars((action||"")+" "+(sh.composition||""), characters);
        if(named.length){ const cur = sh.subjects||[];
          const same = named.length===cur.length && named.every(id=>cur.indexOf(id)>=0);
          if(!same) patch.subjects = named; }
      }
      if(Object.keys(patch).length) onUpdateShot(sh.id, patch);
    });
  },[(shots||[]).length]);
  const ctxFor = (scene)=>({ scene, location:(typeof locationForScene==="function")?locationForScene(locations,scene.id):null,
    charById, propById, project, locations:locations||[] });

  const ordered = React.useMemo(()=> scenesInStoryOrder(scenes),[scenes]);
  const shotsByScene = React.useMemo(()=>{ const m={}; (shots||[]).forEach(s=>{ (m[s.sceneId]=m[s.sceneId]||[]).push(s); });
    Object.values(m).forEach(arr=>arr.sort((a,b)=>(a.order||0)-(b.order||0) || (a.beatN||0)-(b.beatN||0))); return m; },[shots]);
  const scenesWithShots = ordered.filter(s=>(shotsByScene[s.id]||[]).length);

  // "Export shot list" moved into the top bar's ⋮ menu (user ruling 2026-07-19).
  // Register the trigger while this tab is mounted — no deps, so the closure
  // always sees the current shots; the menu shows the item only when this exists.
  React.useEffect(()=>{ window.turnExportShotList = ()=>exportShotList(scenesWithShots, shotsByScene, ctxFor, project, beatsMap);
    return ()=>{ delete window.turnExportShotList; }; });

  // Always show ONE user-selected scene. A generating scene may remain mounted
  // off-screen so its request can finish while the arrows browse elsewhere.
  const [pIdx, setPIdx] = useScenePager(scenesWithShots.length);
  const shotsForGroup = (sid)=> shotsByScene[sid]||[];
  const pIdxC = Math.min(pIdx, Math.max(0, scenesWithShots.length-1));
  const activeShotId = batchActiveId || (chain && chain.ids && chain.ids[chain.idx]) || null;
  const activeShot = activeShotId ? shotById[activeShotId] : null;
  const activeSceneIdx = activeShot ? scenesWithShots.findIndex(s=>s.id===activeShot.sceneId) : -1;
  const visibleIdx = pIdxC;
  const curScene = scenesWithShots[visibleIdx];
  const visibleScenes = [curScene].filter(Boolean);
  const renderBusy = !!batchActiveId || !!chain;
  // a SOLO run (chain of exactly one — a card's Regenerate / QA apply-and-regenerate)
  // is driven by its expanded card. QUEUE runs (Render Scene in order / Generate all
  // shots) mount only the ACTIVE shot's card — off-screen — as the runner's driver.
  const queueMode = (chain && chain.total===1) ? false : (!!batchActiveId || !!chain);
  const runnerScene = activeSceneIdx>=0 && activeSceneIdx!==visibleIdx ? scenesWithShots[activeSceneIdx] : null;
  const sceneNoOf = (sid)=>{ const s=(scenes||[]).find(x=>x.id===sid); return s ? s.no : sid; };

  // ---- the rolling-keyframe CHAIN runner ----------------------------------------
  // Render a scene's shots IN ORDER, each seeded by the previous one's frame. A LOCKED
  // (approved) shot is treated as done \u2014 it seeds the next but isn't re-rendered. Gate ON \u2192
  // pause after each shot for approval; OFF \u2192 auto-lock and continue. Drives the existing
  // sequential batch one shot at a time (useBatchGen is shared, so it isn't modified).
  const chainOrderIds = (list)=> ((typeof sceneShotsOrdered==="function")?sceneShotsOrdered(list):(list||[])).map(s=>s.id);
  const chainKeyOk = ()=> !(typeof nbHasKeyForCurrent==="function") || nbHasKeyForCurrent();
  // A shot counts as DONE (skipped on a non-forced run) only if it's locked AND actually has a
  // committed frame. A locked-but-FRAMELESS shot \u2014 e.g. one whose generation errored or timed
  // out before being approved \u2014 must still render, never be silently skipped as "done".
  const shotHasFrame = (id)=> (typeof nbGetImage==="function") ? !!nbGetImage(id) : false;
  const shotIsDone = (s)=> !!(s && s.locked && shotHasFrame(s.id));
  // Advance to the next shot. Normal scene/all runs retain shots that are already done
  // (locked + framed); manual card runs use force=true so the clicked frame can be regenerated.
  const stepChain = (ids, fromIdx, force)=>{
    let i = fromIdx;
    while(i<ids.length){ const s=shotById[ids[i]]; if(s && (force || !shotIsDone(s))) break; i++; }
    if(i>=ids.length){ setChain(null); batch.setMsg("Chain complete \u2014 every shot rendered in order."); return; }
    // remember what frame (if any) the shot had BEFORE this run — the self-heal below can
    // then tell "the run committed a NEW frame" apart from "the old frame is still there".
    const preFrame = (typeof nbGetImage==="function") ? (nbGetImage(ids[i])||"") : "";
    setChain({ ids, idx:i, total:ids.length, force:!!force, preFrame });
    batch.run([ids[i]]); batch.setMsg("Rendering shot "+(i+1)+" of "+ids.length+" in order\u2026");
  };
  // a chain step finished. Did it actually produce a frame? A FAILED / timed-out / cancelled
  // render commits nothing (nbGetImage stays empty).
  const handleBatchDone = (id, opts)=>{
    batch.advance(id);
    const c = chainRef.current;
    if(!c || c.ids[c.idx]!==id) return;           // a lone (non-chain) generation \u2014 just advance
    const _u = (typeof nbGetImage==="function") ? (nbGetImage(id)||"") : "";
    // STRICT mode (the self-heal): the card never confirmed the run, so an unchanged frame
    // proves nothing — the old frame merely survived a failed re-render. Only a NEW frame
    // counts as success; anything else fail-safes to a stop, never an auto-lock/advance.
    const hasFrame = (opts && opts.strict)
      ? (!!_u && _u !== (c.preFrame||""))
      : ((typeof nbGetImage==="function") ? !!_u : true);
    if(!hasFrame){
      // STOP the chain here \u2014 do NOT advance. Every later shot is seeded by THIS frame as its
      // continuity anchor, so we can't render the next one without it. The shot is left UNLOCKED
      // so a re-run retries it; the frame's own card shows why it failed.
      setChain(null);
      const more = (c.idx+1) < c.ids.length;
      batch.setMsg("Stopped at shot "+(c.idx+1)+" \u2014 it didn't generate"
        + (more ? ", and the next shot needs it as its anchor. Fix the issue on that frame, then render again." : ". See the frame's error and try again."));
      return;
    }
    onUpdateShot(id, { locked:true });            // it's the approved seed for the next shot
    stepChain(c.ids, c.idx+1, c.force);
  };
  // Stop: abort the frame currently rendering (clears its spinner + discards its result),
  // then halt the queue so no further shots start.
  const stopChain = ()=>{
    if(batchActiveId && typeof nbCancelGen==="function") nbCancelGen(batchActiveId);
    setChain(null); batch.cancel();
  };
  // SELF-HEAL a stuck chain. The batch queue advances itself even when the active card is
  // unmounted (global nb-gen-done listener + watchdog in useBatchGen) — but the CHAIN only
  // advances through the card's onBatchDone callback. If the batch moves on without us
  // (watchdog fired on a dead render, card unmounted mid-run), `chain` stays set forever
  // while the batch sits idle — and every Generate button silently ignores clicks. Detect
  // that state (chain set, batch idle for a beat) and reconcile exactly like handleBatchDone
  // would have: advance past a shot that DID commit a frame, stop the chain if it didn't.
  React.useEffect(()=>{
    if(!chain || batchActiveId) return;
    const t = setTimeout(()=>{
      const c = chainRef.current;
      if(!c) return;
      handleBatchDone(c.ids[c.idx], { strict:true });
    }, 800);
    return ()=>clearTimeout(t);
  },[chain, batchActiveId]);

  const chainBusyNotice = ()=> setNotice("A render is already in progress \u2014 wait for it to finish, or press Stop on the running shot first.");
  const startScene = (scene)=>{ if(batchActiveId||chain){ chainBusyNotice(); return; } if(!chainKeyOk()){ batch.setMsg("Set your image-model API key first (top of this tab)."); return; }
    const ids = chainOrderIds(shotsByScene[scene.id]); if(!ids.length) return;
    setCollapsed(c=>({ ...c, [scene.id]:false }));   // keep the scene's cards mounted through the run
    stepChain(ids, 0, false); };
  const startAll = ()=>{ if(batchActiveId||chain){ chainBusyNotice(); return; } if(!chainKeyOk()){ batch.setMsg("Set your image-model API key first (top of this tab)."); return; }
    const ids = scenesWithShots.flatMap(s=>chainOrderIds(shotsByScene[s.id]));
    if(!ids.length){ batch.setMsg("Draft the shots first \u2014 nothing to generate yet."); return; }
    setCollapsed({});   // expand all so each card is mounted as the chain reaches it
    stepChain(ids, 0, false); };
  // re-run a scene's chain from the shot AFTER `sh` \u2014 used after re-rolling a frame so the
  // propagated state stays current. Unlocks the downstream shots so they actually re-render.
  const onRegenDownstream = (sh)=>{ if(!sh) return; if(batchActiveId||chain){ chainBusyNotice(); return; } if(!chainKeyOk()){ batch.setMsg("Set your image-model API key first (top of this tab)."); return; }
    const ids = chainOrderIds(shotsByScene[sh.sceneId]); const at = ids.indexOf(sh.id);
    if(at<0 || at>=ids.length-1){ batch.setMsg("No later shots in this scene to regenerate."); return; }
    ids.slice(at+1).forEach(id=> onUpdateShot(id,{ locked:false }));
    setCollapsed(c=>({ ...c, [sh.sceneId]:false }));
    stepChain(ids, at+1, true); };
  // Manual card generation. A shot seeds off its COVERAGE REFERENCE frame (user ruling
  // 2026-08-01: within a beat, the beat's FIRST shot; a beat opener chains from the
  // previous beat's tail), so that reference — and any seed the reference itself builds
  // on — must already be rendered. If one is missing we DON'T silently render it \u2014 we
  // ask the user to generate the earlier shot first, so they stay in control of the
  // chain order. Only the clicked shot renders here.
  const startShot = async (id)=>{
    if(!id) return;
    // never swallow the click silently — say WHY nothing is starting
    if(batchActiveId || chain || chainStartingRef.current){
      setNotice("A render is already in progress \u2014 wait for it to finish, or press Stop on the running shot first.");
      return;
    }
    if(!chainKeyOk()){ batch.setMsg("Set your image-model API key first (top of this tab)."); return; }
    chainStartingRef.current=true;
    try{
      const target=shotById[id];
      if(!target){ setNotice("That shot can't be found any more \u2014 the shot list may have changed. Refresh and try again."); return; }
      const orderedShots=(typeof sceneShotsOrdered==="function")?sceneShotsOrdered(shotsByScene[target.sceneId]):(shotsByScene[target.sceneId]||[]);
      const at=orderedShots.findIndex(s=>s.id===id);
      if(at<0){ setNotice("That shot isn't in its scene's running order \u2014 refresh and try again."); return; }
      // walk the SEED ANCESTRY: this shot's coverage reference, that reference's own
      // seed, and so on up to a head. Nearest-first; a rendered seed's own ancestry is
      // already baked into its frame, so the walk stops there.
      const missing=[]; const seen={};
      let cur=target;
      while(cur){
        const seed=(typeof seedShotOf==="function")?seedShotOf(cur,orderedShots)
          :((typeof prevShotOf==="function")?prevShotOf(cur,orderedShots):null);
        if(!seed || seen[seed.id]) break;
        seen[seed.id]=true;
        let u=(typeof nbGetImage==="function")?nbGetImage(seed.id):"";
        if(!u && typeof nbLoadImage==="function"){ try{ u=await nbLoadImage(seed.id); }catch(e){} }
        if(!u){ missing.push(seed); cur=seed; continue; }
        break;
      }
      if(missing.length){
        const shotNo = (s)=> Math.max(1, orderedShots.findIndex(x=>x.id===s.id)+1);
        const shotLab = (s)=> "Shot "+shotNo(s)+(s.beatN ? " (Beat "+s.beatN+")" : "");
        const near=missing[0];                    // the reference this shot builds on
        const first=missing[missing.length-1];    // the earliest missing link
        setNotice(missing.length===1
          ? shotLab(target)+" depends on "+shotLab(near)+". Generate "+shotLab(near)+" first so it can become the coverage reference."
          : shotLab(target)+" depends on "+shotLab(near)+", but its own seed chain is incomplete. Generate the chain in order starting with "+shotLab(first)+".");
        return;
      }
      setCollapsed(c=>({ ...c, [target.sceneId]:false }));
      stepChain([id],0,true);
    } finally {
      chainStartingRef.current=false;
    }
  };

  // ---- empty state ----
  if(!scenesWithShots.length){
    return _el("div",{className:"art-scroll"},
      _el(NbKeyBar,null), _el(NbControls,null),
      _el("div",{className:"art-intro"},
        _el("div",{className:"art-intro-row"},
          _el("div",{style:{flex:1}},
            _el("div",{className:"art-intro-t",style:{display:"flex",alignItems:"center",gap:9}},"Shot List",
              _el(window.InfoTip,{label:"About the Shots tab",
                text:"Every beat becomes a shot. \u201cDesign all shots\u201d breaks each scene into coverage \u2014 size, angle, movement and lens \u2014 then composes each frame from the scene's grade, the location plate and the character & prop sheets. Generate the frames here; the Storyboards tab lays them out next."}))),
          _el("div",{className:"art-intro-actions"},
            _el("button",{className:"art-draftall",disabled:draftingAllShots||!ordered.length,onClick:handleDesignAll,
              title:"Break every scene into a shot list from its beats"},
              _el(Icon.sparkles,{s:14}), draftingAllShots?"Designing\u2026":"Design all shots")))),
      _el("div",{className:"prop-empty"},
        _el("div",{className:"art-soon-ic"},_el(Icon.film,{s:30})),
        _el("div",{className:"art-soon-t"},"No shots yet"),
        _el("div",{className:"art-soon-d"},"Break your scenes into shots \u2014 one shot per beat, with full coverage \u2014 then generate a frame for each."),
        _el("button",{className:"art-draftall",style:{marginTop:16},disabled:draftingAllShots||!ordered.length,onClick:handleDesignAll},
          _el(Icon.sparkles,{s:14}), draftingAllShots?"Designing\u2026":"Design all shots")));
  }

  return _el("div",{className:"art-scroll"},
    view && _el(ImageLightbox,{url:view.url,character:view.character,onClose:()=>setView(null)}),
    notice && _el("div",{className:"shot-notice-scrim",onMouseDown:()=>setNotice("")},
      _el("div",{className:"shot-notice",role:"status",onMouseDown:e=>e.stopPropagation()},
        _el(Icon.info,{s:17,className:"shot-notice-ic"}),
        _el("div",{className:"shot-notice-msg"},notice),
        _el("button",{type:"button",className:"shot-notice-x","aria-label":"Close message",
          title:"Close",onClick:()=>setNotice("")},"\u00d7"))),
    _el(NbKeyBar,null), _el(NbControls,null),
    _el("div",{className:"art-intro"},
      _el("div",{className:"art-intro-row"},
        _el("div",{style:{flex:1}},
          _el("div",{className:"art-intro-t",style:{display:"flex",alignItems:"center",gap:9}},"Cinematographer (Shot Designer)",
            _el(window.InfoTip,{label:"About the Shot List",
              text:"A BEAT owns 1\u2013N shots (coverage): every scene starts at one shot per beat, and any beat can be SPLIT INTO COVERAGE from its lane header \u2014 one shot per distinct visual event, labelled 3A/3B/3C in cut order. Shots are grouped by beat lane inside each scene. Every frame generation follows a chain in scene order: the scene's first shot renders from the locked sheets; within a beat every later shot is seeded by the beat's FIRST frame (its coverage reference), and each beat's first shot chains from the previous beat's tail frame. Generate the shots in order — if you click Generate on a later shot before an earlier one is rendered, TURN asks you to generate the earlier shot first (it's the anchor this frame builds on). 'Generate all shots' and 'Render Scene X in order' render the whole chain straight through, auto-approving each frame as the next shot's seed. Stage video clips are packed automatically from these shots \u2014 there is no manual clip grouping here; clips live on the Stage."}))),
        _el("div",{className:"art-intro-actions"},
          // "Export shot list" lives in the top bar's ⋮ menu now (window.turnExportShotList)
          _el("button",{className:"art-draftall ghost",disabled:draftingAllShots||!ordered.length,onClick:handleDesignAll,
            title:"Break any scene that has no shots yet into full coverage \u2014 size, angle, move and lens per beat"},
            _el(Icon.sparkles,{s:14}), draftingAllShots?"Designing\u2026":"Design all shots"),
          _el("button",{className:"art-draftall",disabled:!!batchActiveId||!!chain||!shots.length,onClick:startAll,
            title:"Render every shot in chain order, each seeded by its beat's coverage reference. Locked (approved) frames are kept and used as seeds; the rest render."},
            _el(Icon.sparkles,{s:14}), (batchActiveId||chain)?"Rendering\u2026":"Generate all shots", typeof window.nbCostChip==="function" && window.nbCostChip(1))))),
    // A chain already has its own progress + Stop bar below. Hiding the generic
    // batch bar here avoids duplicate Cancel/Stop controls for the same request.
    !chain && BatchBar && _el(BatchBar,{batch,noun:"shot"}),
    // "Design all shots" progress — determinate, driven by how many scenes still lack shots
    (draftingAllShots && designTotal>0) && (()=>{
      const remaining = scenesNeedingShots().length;
      const done = Math.max(0, designTotal - remaining);
      const pct = Math.round((done/designTotal)*100);
      return _el("div",{className:"shot-design-bar"},
        _el("div",{className:"shot-design-row"},
          _el("span",{className:"ns-spin"}),
          _el("span",{className:"shot-design-lab"},"Designing shots — scene "+Math.min(done+1,designTotal)+" of "+designTotal+"…")),
        _el("div",{className:"shot-design-track"}, _el("div",{className:"shot-design-fill",style:{width:pct+"%"}})));
    })(),
    // (standalone ScenePager removed — the navigator is merged into each scene card head)
    visibleScenes.map(scene=>_el(SceneShotGroup,{key:scene.id,scene,shots:shotsForGroup(scene.id),
      pager:{ idx:visibleIdx, total:scenesWithShots.length, scenes:scenesWithShots, onJump:setPIdx,
        onPrev:()=>setPIdx(i=>Math.max(0,i-1)), onNext:()=>setPIdx(i=>Math.min(scenesWithShots.length-1,i+1)) },
      ctx:ctxFor(scene),characters:characters||[],beatsMap,propsAvail:(typeof propsForScene==="function")?propsForScene(props,scene.id):[],
      onUpdate:onUpdateShot,onDelete:onDeleteShot,onView:(url,e)=>setView({url,character:e}),
      onAddShot,onSplitBeat,splittingBeat,onDraftScene:onDraftSceneShots,draftingScene:draftingSceneShots===scene.id,
      batchActiveId,onBatchDone:handleBatchDone,onGenerateShot:startShot,onRegenDownstream,
      onRenderScene:startScene,renderBusy,queueMode,onStopChain:stopChain,
      open:true,onToggle:()=>toggleScene(scene.id)})),
    // Keep only the active runner mounted when the user browses away. display:none
    // preserves its generation/completion effects without showing a second scene.
    runnerScene && _el("div",{style:{display:"none"},"aria-hidden":"true"},
      _el(SceneShotGroup,{key:"runner-"+runnerScene.id,scene:runnerScene,shots:shotsForGroup(runnerScene.id),
        ctx:ctxFor(runnerScene),characters:characters||[],beatsMap,
        propsAvail:(typeof propsForScene==="function")?propsForScene(props,runnerScene.id):[],
        onUpdate:onUpdateShot,onDelete:onDeleteShot,onView:(url,e)=>setView({url,character:e}),
        onAddShot,onSplitBeat,splittingBeat,onDraftScene:onDraftSceneShots,draftingScene:draftingSceneShots===runnerScene.id,
        batchActiveId,onBatchDone:handleBatchDone,onGenerateShot:startShot,onRegenDownstream,
        onRenderScene:startScene,renderBusy,queueMode,onStopChain:stopChain,open:true,onToggle:()=>{}})));
}
window.ShotList = ShotList;

/* ---- export: a printable shot-list table (open in a new tab → Save as PDF) ---- */
function exportShotList(scenesWithShots, shotsByScene, ctxFor, project, beatsMap){
  const esc = (s)=> String(s==null?"":s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
  const title = (project && project.title) || "Shot List";
  let rows = "";
  scenesWithShots.forEach(scene=>{
    const ctx = ctxFor(scene);
    const loc = ctx.location ? ctx.location.name : "";
    const beatRows = ((beatsMap||{})[scene.id]||{}).rows || [];
    rows += '<tr class="scenehdr"><td colspan="7"><b>SC '+esc(String(scene.no).padStart(2,"0"))+'</b> &nbsp; '
      + esc(scene.title||"")+(loc?(' &nbsp;&middot;&nbsp; '+esc(loc)):"")+'</td></tr>';
    (shotsByScene[scene.id]||[]).forEach((sh,i)=>{
      const subs = (sh.subjects||[]).map(id=>ctx.charById[id]).filter(Boolean).map(c=>c.name).join(", ");
      // the SCRIPT BEAT this shot covers (drive — reaction) rides under the action,
      // so the printed list carries the source text the coverage answers to
      const br = beatRows.find(r=>String(r.n)===String(sh.beatN));
      const beatText = br ? [ (br.drive&&br.drive.d||"").trim(), (br.react&&br.react.d||"").trim() ].filter(Boolean).join(" — ") : "";
      rows += '<tr>'
        + '<td class="num">'+esc(scene.no)+'.'+esc(i+1)+(sh.beatN?('<span class="bn">b'+esc(sh.beatN)+'</span>'):'')+'</td>'
        + '<td>'+esc(shotSizeOf(sh.size).label)+'</td>'
        + '<td>'+esc(shotAngleOf(sh.angle).label)+'</td>'
        + '<td>'+esc(shotMoveOf(sh.move).label)+' &middot; '+esc(shotLensOf(sh.lens).label)+'</td>'
        + '<td>'+esc(subs)+'</td>'
        + '<td class="act">'+esc(sh.action||"")+(sh.dialogue?(' <span class="dlg">&ldquo;'+esc(sh.dialogue)+'&rdquo;</span>'):"")
        + (beatText?('<div class="beat"><span class="beatlab">Beat '+esc(sh.beatN||"")+'</span> '+esc(beatText)+'</div>'):"")+'</td>'
        + '<td class="comp">'+esc(sh.composition||"")+'</td>'
        + '</tr>';
    });
  });
  const html = '<!doctype html><html><head><meta charset="utf-8"><title>'+esc(title)+' \u2014 Shot List</title>'
    + '<style>'
    + 'body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#16181d;margin:40px;}'
    + 'h1{font-size:20px;margin:0 0 4px;} .sub{color:#666;font-size:12px;margin-bottom:20px;}'
    + 'table{border-collapse:collapse;width:100%;font-size:11.5px;}'
    + 'th,td{border:1px solid #d7dae0;padding:6px 8px;vertical-align:top;text-align:left;}'
    + 'th{background:#f3f4f6;font-size:10px;letter-spacing:.06em;text-transform:uppercase;color:#555;}'
    + 'tr.scenehdr td{background:#1b1e26;color:#fff;font-size:12px;padding:7px 8px;}'
    + 'td.num{font-variant-numeric:tabular-nums;white-space:nowrap;color:#666;} td.act{width:30%;} td.comp{width:24%;color:#444;}'
    + '.dlg{color:#7a5; font-style:italic;}'
    + '.beat{margin-top:5px;padding:4px 7px;background:#f6f6f3;border-left:2px solid #c9ccd3;color:#555;font-style:italic;font-size:10.5px;line-height:1.4;}'
    + '.beatlab{font-style:normal;font-size:8.5px;letter-spacing:.07em;text-transform:uppercase;color:#999;margin-right:4px;}'
    + '.bn{margin-left:5px;font-size:8.5px;color:#aaa;}'
    + '@media print{body{margin:14mm;}}'
    + '</style></head><body>'
    + '<h1>'+esc(title)+' &mdash; Shot List</h1>'
    + '<div class="sub">'+(project&&project.format?esc(project.format)+' &middot; ':'')+'Generated by Cinema Machine</div>'
    + '<table><thead><tr><th>Shot</th><th>Size</th><th>Angle</th><th>Move / Lens</th><th>In frame</th><th>Action</th><th>Composition</th></tr></thead>'
    + '<tbody>'+rows+'</tbody></table>'
    + '</body></html>';
  // in-app PREVIEW first (same overlay as the screenplay export) — print/download from there
  if(typeof window.docPreview==="function"){
    window.docPreview({ title:"Shot list preview", sub:title,
      fileName:(title||"shot_list").replace(/[^\w\-]+/g,"_").toUpperCase()+"_SHOT_LIST.html", html,
      hint:"Review the table, then print / save as PDF — or download the HTML." });
    return;
  }
  // fallback (overlay unavailable): the old auto-printing tab
  const w = window.open("", "_blank");
  if(w){ w.document.open();
    w.document.write(html.replace('</body>','<script>setTimeout(function(){try{window.print();}catch(e){}},350);<\/script></body>'));
    w.document.close(); }
}
window.exportShotList = exportShotList;
