/* shots-ui.jsx — The Art Room ▸ Shot List (React).
   Scene-grouped shot list. Each shot is ONE beat, carrying cinematographer grammar
   (size · angle · movement · lens), the subjects/location/props in frame, an action
   line and an editable composition note. The frame is generated by composing the
   scene's Style Bible grade + the location plate + the character/prop sheets as
   reference images (see buildShotPrompt). Reuses SheetFrame, useImageGen and the
   shared batch engine so it behaves exactly like the other Art Room tabs. */

const _el = React.createElement;

/* a labelled grammar dropdown (size / angle / move / lens) */
function GrammarSelect({ label, value, options, onChange }){
  return _el("label",{className:"shot-gsel"},
    _el("span",{className:"shot-gsel-lab"},label),
    _el("select",{className:"prop-select",value:value,onChange:e=>onChange(e.target.value)},
      options.map(o=>_el("option",{key:o.id,value:o.id,title:o.desc||""},o.label))));
}

/* a toggle chip row for choosing which cast / props are in frame */
function FrameToggles({ label, items, selected, onToggle, emptyHint }){
  if(!items.length) return _el("div",{className:"shot-frame-empty"},emptyHint);
  return _el("div",{className:"shot-frame-row"},
    _el("span",{className:"shot-frame-lab"},label),
    _el("div",{className:"shot-chips"},
      items.map(it=>{
        const on = selected.indexOf(it.id)>=0;
        return _el("button",{key:it.id,className:"shot-chip"+(on?" on":""),onClick:()=>onToggle(it.id)},
          on?_el(Icon.check,{s:11}):null, it.name);
      })));
}

function ShotCard({ sh, scene, ctx, characters, propsAvail, anchorShot, onSetAnchor, onUpdate, onDelete, onView, batchActiveId, onBatchDone }){
  const loc = ctx.location;
  const subjects = (sh.subjects||[]).map(id=>ctx.charById[id]).filter(Boolean);
  const finalPrompt = combinedShotPrompt(sh, ctx);
  const isAnchor = !!(anchorShot && anchorShot.id===sh.id);

  // reference images: the SCENE KEY FRAME (anchor) first, then the location plate +
  // each subject's sheet + each prop's sheet. The anchor is another shot in this scene
  // whose generated frame pins the scene's lighting/grade/world so every shot matches.
  const collectShotRefs = async ()=>{
    const grab = async (id)=>{ let u = (typeof nbGetImage==="function") ? nbGetImage(id) : "";
      if(!u && typeof nbLoadImage==="function"){ try{ u = await nbLoadImage(id); }catch(e){} } return u; };
    const out = [];
    if(anchorShot && anchorShot.id!==sh.id){ const u = await grab(anchorShot.id); if(u) out.push({ url:u, note:"scene key frame", anchor:true }); }
    if(loc){ const u = await grab(loc.id); if(u) out.push({ url:u, note:(loc.name||"location")+" location plate" }); }
    for(const c of subjects){ const u = await grab(c.id); if(u) out.push({ url:u, note:c.name+" character sheet" }); }
    for(const id of (sh.props||[])){ const p = ctx.propById[id]; if(!p) continue; const u = await grab(id); if(u) out.push({ url:u, note:p.name+" prop sheet" }); }
    return out;
  };

  const gen = useImageGen({
    id: sh.id, slotId: "shot-"+sh.id,
    buildFinal: ()=> finalPrompt,
    buildSimple: ()=> buildShotPrompt(sh, ctx),
    attachments: collectShotRefs,
    attachmentsText: (attach)=>{
      const hasAnchor = attach[0] && attach[0].anchor;
      let s = "Reference images provided, IN ORDER: "+attach.map(a=>a.note).join("; ")+". ";
      if(hasAnchor) s += "The FIRST image is this SCENE'S KEY FRAME — match its lighting, colour grade, atmosphere and the world/space EXACTLY, and keep every character's appearance consistent with it; only re-compose to THIS shot's size, angle and staging. ";
      s += "Match the corresponding character(s), location and prop(s) to these reference designs EXACTLY "
        +"(faces, wardrobe, geometry, materials) for cross-shot continuity; compose them into this one frame.";
      return s;
    },
    buildEdit: (instr)=>
      "Edit this film frame. Apply ONLY this change: "+instr+". Keep the same shot size, lens, staging, "
      +"the same characters (identical faces & wardrobe), the same location and the same colour grade. Do not re-imagine the frame.",
  });

  // batch auto-generate when this card is the active queue member
  const batchStarted = React.useRef(false);
  const wasGening = React.useRef(false);
  React.useEffect(()=>{
    const mine = batchActiveId===sh.id;
    if(!mine){ batchStarted.current=false; wasGening.current=gen.gening; return; }
    if(!batchStarted.current && !gen.gening){ batchStarted.current=true; wasGening.current=false; gen.generate(); return; }
    if(batchStarted.current && wasGening.current && !gen.gening){ batchStarted.current=false; onBatchDone && onBatchDone(sh.id); }
    wasGening.current = gen.gening;
  },[batchActiveId, gen.gening, sh.id]);

  const toggleIn = (key, id)=>{ const cur = sh[key]||[]; const next = cur.indexOf(id)>=0 ? cur.filter(x=>x!==id) : [...cur, id];
    const patch = { [key]: next }; if(key==="subjects") patch.subjectsSet = true; onUpdate(sh.id, patch); };

  const beatLabel = "Beat "+(sh.beatN||"\u2014");
  const initials = (sizeOf(sh.size).label||"SH");

  return _el("div",{className:"sheet-card shot-card"+(batchActiveId===sh.id?" batch-on":""),"data-shot-card":sh.id},
    _el(SheetFrame,{ gen, slotId:"shot-"+sh.id, name:beatLabel, avatarColor:"linear-gradient(135deg,#7a6cae,#2a2440)",
      initials, drafted:true, drafting:false, onDraft:()=>{}, entity:sh, onView,
      slotPlaceholder:"Generate or drop a frame", noun:"frame",
      extraMeta:[
        { k:"Size",  v: sizeOf(sh.size).label + (sizeOf(sh.size).name?(" — "+sizeOf(sh.size).name):"") },
        { k:"Angle", v: angleOf(sh.angle).label },
        { k:"Move",  v: moveOf(sh.move).label },
        { k:"Lens",  v: lensOf(sh.lens).label },
      ],
      onDelete:()=>onDelete(sh.id), deleteLabel:"Delete shot" }),
    _el("div",{className:"sheet-body"},
      _el("div",{className:"shot-head"},
        _el("div",{className:"shot-grammar-line"},shotGrammarLabel(sh)),
        _el("div",{className:"shot-head-right"},
          _el("button",{className:"shot-anchor-btn"+(isAnchor?" on":""),
            title:isAnchor
              ? "This shot is the scene's visual ANCHOR — every other shot in the scene references its frame to match lighting, grade and world. Generate it first."
              : "Make this the scene's visual anchor — other shots will match its look",
            onClick:()=>onSetAnchor&&onSetAnchor(sh)},
            _el(Icon.pin,{s:11}), isAnchor && _el("span",null,"Anchor")),
          _el("div",{className:"shot-beat-tag"},beatLabel))),

      // cinematographer grammar
      _el("div",{className:"shot-grammar-grid"},
        _el(GrammarSelect,{label:"Size",value:sh.size,options:SHOT_SIZES,onChange:v=>onUpdate(sh.id,{size:v})}),
        _el(GrammarSelect,{label:"Angle",value:sh.angle,options:SHOT_ANGLES,onChange:v=>onUpdate(sh.id,{angle:v})}),
        _el(GrammarSelect,{label:"Move",value:sh.move,options:SHOT_MOVES,onChange:v=>onUpdate(sh.id,{move:v})}),
        _el(GrammarSelect,{label:"Lens",value:sh.lens,options:SHOT_LENSES,onChange:v=>onUpdate(sh.id,{lens:v})})),

      // the action — what we see in this frame
      _el(SheetField,{label:"Action \u2014 what we see in this frame",value:sh.action,multiline:true,
        placeholder:"One vivid present-tense beat of on-screen action\u2026",onCommit:v=>onUpdate(sh.id,{action:v})}),

      // composition (the depth-grid "vary" layer) + dialogue
      _el(SheetField,{label:"Composition \u2014 framing, blocking, depth, eyeline",value:sh.composition,multiline:true,
        placeholder:"Where subjects sit in frame, foreground/background, eyeline\u2026",onCommit:v=>onUpdate(sh.id,{composition:v})}),
      _el(SheetField,{label:"Dialogue (optional)",value:sh.dialogue,multiline:false,
        placeholder:"A short line spoken in this beat\u2026",onCommit:v=>onUpdate(sh.id,{dialogue:v})}),

      _el(CardFold,{label:"In frame",defaultOpen:false},
        _el(FrameToggles,{label:"Characters",items:characters,selected:sh.subjects||[],
          onToggle:(id)=>toggleIn("subjects",id),emptyHint:"No cast in this story."}),
        _el(FrameToggles,{label:"Props",items:propsAvail,selected:sh.props||[],
          onToggle:(id)=>toggleIn("props",id),emptyHint:"No props mapped to this scene."}),
        _el("div",{className:"shot-loc-note"},
          _el(Icon.globe,{s:12}),
          loc ? _el("span",null,"Location: ",_el("b",null,loc.name),(typeof stagingHasContent==="function"&&stagingHasContent(loc))?" \u00b7 depth grid inherited":" \u00b7 no depth grid staged")
              : _el("span",null,"No location resolved for this scene \u2014 set the scene's slugline / pull locations."))),

      _el(CardFold,{label:"Shot prompt",defaultOpen:false},
        _el(CopyBox,{label:"Final frame prompt \u2014 master + grade + references",text:finalPrompt}),
        _el(SheetField,{label:"Negative prompt \u2014 exclude",value:sh.negativePrompt||"",multiline:true,
          placeholder:shotNegativePrompt({}),onCommit:v=>onUpdate(sh.id,{negativePrompt:v})}))));
}

const CONF_LABELS = ["Inner","Personal","Extra-personal"];
function SceneCtxItem({ k, v }){
  if(!v) return null;
  return _el("div",{className:"ssx-item"}, _el("div",{className:"ssx-k"},k), _el("div",{className:"ssx-v"},v));
}

function SceneShotGroup({ scene, shots, ctx, characters, propsAvail, beatsMap, onUpdate, onDelete, onView,
  onAddShot, onDraftScene, draftingScene, onSceneBatch, batchActiveId, onBatchDone, open, onToggle }){
  const loc = ctx.location;
  const driver = scene.driver ? ctx.charById[scene.driver] : null;
  // scene-level context (driver/reactor/antagonism/goal/conflict) — driver+goal+conflict from the
  // Scene inspector, reactor+antagonism from the beat-map, exactly as the Writers' Room shows them.
  const bm = (beatsMap||{})[scene.id] || {};
  const driverName = driver ? driver.name : (bm.driverLabel||"");
  const confLab = scene.conf ? CONF_LABELS[scene.conf-1] : "";
  // the scene's visual anchor: the shot flagged .anchor, else the first shot in order
  const anchorShot = shots.find(s=>s.anchor) || shots[0] || null;
  const setAnchor = (target)=> shots.forEach(s=> onUpdate(s.id, { anchor: s.id===target.id }));
  return _el("div",{className:"shot-scene-group"+(open?"":" collapsed")},
    _el("div",{className:"shot-scene-head"},
      _el("button",{className:"shot-scene-fold",onClick:onToggle,
        title:open?"Collapse this scene":"Expand this scene","aria-expanded":open?"true":"false"},
        _el(Icon.chevR,{s:15})),
      _el("div",{className:"shot-scene-no"},String(scene.no).padStart(2,"0")),
      _el("div",{className:"shot-scene-meta",onClick:onToggle,style:{cursor:"pointer"}},
        _el("div",{className:"shot-scene-title"},scene.title||"Untitled scene"),
        _el("div",{className:"shot-scene-sub"},
          (driver?("Driver: "+driver.name):"")+(driver&&loc?"  \u00b7  ":"")+(loc?("Location: "+loc.name):"")
          +"   \u00b7   "+shots.length+" shot"+(shots.length!==1?"s":""))),
      _el("div",{className:"shot-scene-acts"},
        _el("button",{className:"char-draft-btn ghost"+(draftingScene?" busy":""),disabled:!!draftingScene,onClick:()=>onDraftScene(scene),
          title:"Re-derive this scene's shot list from its beats (replaces the current shots)"},
          _el(Icon.layers,{s:12}), draftingScene?"Drafting\u2026":"Re-draft shots"),
        _el("button",{className:"char-draft-btn",onClick:()=>onAddShot(scene.id),
          title:"Add a shot to this scene by hand"},
          _el(Icon.plus,{s:12}),"Add shot"),
        _el("button",{className:"char-draft-btn",disabled:!!batchActiveId,onClick:()=>onSceneBatch(scene),
          title:"Generate the frame for every shot in this scene"},
          _el(Icon.sparkles,{s:12}), batchActiveId?"Generating\u2026":"Generate scene")),
    ),
    open && _el("div",{className:"shot-scene-ctx"},
      scene.summary && _el("div",{className:"ssx-desc"},scene.summary),
      _el("div",{className:"ssx-grid"},
        _el(SceneCtxItem,{k:"Driver",v:driverName}),
        _el(SceneCtxItem,{k:"Reactor",v:bm.reactorLabel}),
        _el(SceneCtxItem,{k:"Driver's goal",v:scene.objective}),
        _el(SceneCtxItem,{k:"Antagonism",v:bm.obstacle}),
        scene.conf && _el("div",{className:"ssx-item"},
          _el("div",{className:"ssx-k"},"Conflict level"),
          _el("div",{className:"ssx-conf"},
            confLab && _el("span",{className:"ssx-conf-lab"},confLab),
            _el("div",{className:"ssx-pips"},
              [1,2,3].map(i=>_el("span",{key:i,className:"ssx-pip"+(i<=scene.conf?" on":"")}))))))),
    open && _el("div",{className:"sheet-grid"},
      shots.map(sh=>_el(ShotCard,{key:sh.id,sh,scene,ctx,characters,propsAvail,anchorShot,onSetAnchor:setAnchor,onUpdate,onDelete,onView,
        batchActiveId,onBatchDone}))));
}

function ShotList({ project, scenes, characters, props, locations, shots, beatsMap,
  onUpdateShot, onAddShot, onDeleteShot, onDraftSceneShots, draftingSceneShots, onDraftAllShots, draftingAllShots }){
  const [view, setView] = React.useState(null);
  const batch = useBatchGen();
  const batchActiveId = batch.activeId;
  // per-scene fold state (persisted) so a long shot list isn't all-or-nothing scrolling
  const [collapsed, setCollapsed] = React.useState(()=>{ try{ return JSON.parse(localStorage.getItem("turn_shots_collapsed")||"{}")||{}; }catch(e){ return {}; } });
  React.useEffect(()=>{ try{ localStorage.setItem("turn_shots_collapsed", JSON.stringify(collapsed)); }catch(e){} },[collapsed]);
  const toggleScene = (id)=> setCollapsed(c=>({ ...c, [id]: !c[id] }));

  const charById = React.useMemo(()=>{ const m={}; (characters||[]).forEach(c=>m[c.id]=c); return m; },[characters]);
  const propById = React.useMemo(()=>{ const m={}; (props||[]).forEach(p=>m[p.id]=p); return m; },[props]);

  // one-time sanity pass: re-anchor each shot's subjects to the cast NAMED in its
  // action/composition text (earlier drafts could drift to background cast — e.g. a
  // beat about Amara getting tagged with other characters). Skips shots the user has
  // set by hand (subjectsSet), and only changes a shot when the text clearly names a
  // DIFFERENT set, so valid/pronoun-only shots are left alone.
  const subjFixed = React.useRef(false);
  React.useEffect(()=>{
    if(subjFixed.current || typeof scanTextForChars!=="function" || !(shots||[]).length) return;
    subjFixed.current = true;
    const beatActionOf = (sh)=>{ const b=(beatsMap||{})[sh.sceneId];
      const row = b && (b.rows||[]).find(r=>String(r.n)===String(sh.beatN));
      return row ? ((row.drive&&row.drive.d)||(row.react&&row.react.d)||"") : ""; };
    (shots||[]).forEach(sh=>{
      const patch = {};
      // backfill an empty action from its originating beat (a draft can leave it blank)
      let action = sh.action;
      if(!String(action||"").trim()){ const ba = beatActionOf(sh); if(ba){ action = ba; patch.action = ba; } }
      // re-anchor subjects to the (possibly backfilled) action text, unless set by hand
      if(!sh.subjectsSet){
        const named = scanTextForChars((action||"")+" "+(sh.composition||""), characters);
        if(named.length){ const cur = sh.subjects||[];
          const same = named.length===cur.length && named.every(id=>cur.indexOf(id)>=0);
          if(!same) patch.subjects = named; }
      }
      if(Object.keys(patch).length) onUpdateShot(sh.id, patch);
    });
  },[(shots||[]).length]);
  const ctxFor = (scene)=>({ scene, location:(typeof locationForScene==="function")?locationForScene(locations,scene.id):null,
    charById, propById, project });

  const ordered = React.useMemo(()=> (scenes||[]).slice().sort((a,b)=>(a.no||0)-(b.no||0)),[scenes]);
  const shotsByScene = React.useMemo(()=>{ const m={}; (shots||[]).forEach(s=>{ (m[s.sceneId]=m[s.sceneId]||[]).push(s); });
    Object.values(m).forEach(arr=>arr.sort((a,b)=>(a.order||0)-(b.order||0) || (a.beatN||0)-(b.beatN||0))); return m; },[shots]);
  const scenesWithShots = ordered.filter(s=>(shotsByScene[s.id]||[]).length);
  const anyOpen = scenesWithShots.some(s=>!collapsed[s.id]);
  const collapseAll = ()=> setCollapsed(()=>{ const m={}; scenesWithShots.forEach(s=>{ m[s.id]=true; }); return m; });
  const expandAll = ()=> setCollapsed({});

  // order a scene's shots with its anchor FIRST, so the anchor frame exists before the
  // other shots generate and reference it (the source of cross-shot consistency).
  const anchorFirstIds = (list)=>{ const arr=(list||[]).slice(); const i=arr.findIndex(s=>s.anchor);
    if(i>0){ const [a]=arr.splice(i,1); arr.unshift(a); } return arr.map(s=>s.id); };
  const startAll = ()=>{ if(batchActiveId) return; const ids=scenesWithShots.flatMap(s=>anchorFirstIds(shotsByScene[s.id]));
    if(!ids.length){ batch.setMsg("Draft the shots first \u2014 nothing to generate yet."); return; } batch.begin(ids, 0); };
  const startScene = (scene)=>{ if(batchActiveId) return; const ids=anchorFirstIds(shotsByScene[scene.id]);
    if(!ids.length) return; batch.begin(ids, 0); };

  // ---- empty state ----
  if(!scenesWithShots.length){
    return _el("div",{className:"art-scroll"},
      _el(NbKeyBar,null), _el(NbControls,null),
      _el("div",{className:"art-intro"},
        _el("div",{className:"art-intro-row"},
          _el("div",{style:{flex:1}},
            _el("div",{className:"art-intro-t",style:{display:"flex",alignItems:"center",gap:9}},"Shot List",
              _el(window.InfoTip,{label:"About the Shot List",
                text:"Every beat becomes a shot. \u201cDraft all shots\u201d breaks each scene into coverage \u2014 size, angle, movement and lens \u2014 then composes each frame from the scene's grade, the location plate and the character & prop sheets. Generate the frames here; the Storyboard lays them out next."}))),
          _el("div",{className:"art-intro-actions"},
            _el("button",{className:"art-draftall",disabled:draftingAllShots||!ordered.length,onClick:onDraftAllShots,
              title:"Break every scene into a shot list from its beats"},
              _el(Icon.sparkles,{s:14}), draftingAllShots?"Drafting shots\u2026":"Draft all shots")))),
      _el("div",{className:"prop-empty"},
        _el("div",{className:"art-soon-ic"},_el(Icon.film,{s:30})),
        _el("div",{className:"art-soon-t"},"No shots yet"),
        _el("div",{className:"art-soon-d"},"Break your scenes into shots \u2014 one shot per beat, with full coverage \u2014 then generate a frame for each."),
        _el("button",{className:"art-draftall",style:{marginTop:16},disabled:draftingAllShots||!ordered.length,onClick:onDraftAllShots},
          _el(Icon.sparkles,{s:14}), draftingAllShots?"Drafting shots\u2026":"Draft all shots")));
  }

  return _el("div",{className:"art-scroll"},
    view && _el(ImageLightbox,{url:view.url,character:view.character,onClose:()=>setView(null)}),
    _el(NbKeyBar,null), _el(NbControls,null),
    _el("div",{className:"art-intro"},
      _el("div",{className:"art-intro-row"},
        _el("div",{style:{flex:1}},
          _el("div",{className:"art-intro-t",style:{display:"flex",alignItems:"center",gap:9}},"Shot List",
            _el(window.InfoTip,{label:"About the Shot List",
              text:"One shot per beat, grouped by scene. Each frame composes the scene's Style Bible grade, the location plate and the character & prop sheets into a single image \u2014 so every shot stays on-model and on-palette."}))),
        _el("div",{className:"art-intro-actions"},
          _el("button",{className:"art-draftall ghost",onClick:anyOpen?collapseAll:expandAll,
            title:anyOpen?"Collapse every scene to its header":"Expand every scene"},
            _el(Icon.layers,{s:14}), anyOpen?"Collapse all":"Expand all"),
          _el("button",{className:"art-draftall ghost",onClick:()=>exportShotList(scenesWithShots, shotsByScene, ctxFor, project),
            title:"Export the shot list as a printable table (open & Save as PDF)"},
            _el(Icon.download,{s:14}),"Export shot list"),
          _el("button",{className:"art-draftall ghost",disabled:draftingAllShots||!ordered.length,onClick:onDraftAllShots,
            title:"Break any scene that has no shots yet into a shot list from its beats"},
            _el(Icon.sparkles,{s:14}), draftingAllShots?"Drafting shots\u2026":"Draft all shots"),
          _el("button",{className:"art-draftall",disabled:!!batchActiveId||!shots.length,onClick:startAll,
            title:"Generate (or regenerate) the frame for every shot \u2014 you choose whether to redo ones that already have a frame"},
            _el(Icon.sparkles,{s:14}), batchActiveId?"Generating\u2026":"Generate all shots")))),
    BatchBar && _el(BatchBar,{batch,noun:"shot"}),
    scenesWithShots.map(scene=>_el(SceneShotGroup,{key:scene.id,scene,shots:shotsByScene[scene.id]||[],
      ctx:ctxFor(scene),characters:characters||[],beatsMap,propsAvail:(typeof propsForScene==="function")?propsForScene(props,scene.id):[],
      onUpdate:onUpdateShot,onDelete:onDeleteShot,onView:(url,e)=>setView({url,character:e}),
      onAddShot,onDraftScene:onDraftSceneShots,draftingScene:draftingSceneShots===scene.id,
      onSceneBatch:startScene,batchActiveId,onBatchDone:batch.advance,
      open:!collapsed[scene.id],onToggle:()=>toggleScene(scene.id)})));
}
window.ShotList = ShotList;

/* ---- export: a printable shot-list table (open in a new tab → Save as PDF) ---- */
function exportShotList(scenesWithShots, shotsByScene, ctxFor, project){
  const esc = (s)=> String(s==null?"":s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
  const title = (project && project.title) || "Shot List";
  let rows = "";
  scenesWithShots.forEach(scene=>{
    const ctx = ctxFor(scene);
    const loc = ctx.location ? ctx.location.name : "";
    rows += '<tr class="scenehdr"><td colspan="7"><b>SC '+esc(String(scene.no).padStart(2,"0"))+'</b> &nbsp; '
      + esc(scene.title||"")+(loc?(' &nbsp;&middot;&nbsp; '+esc(loc)):"")+'</td></tr>';
    (shotsByScene[scene.id]||[]).forEach((sh,i)=>{
      const subs = (sh.subjects||[]).map(id=>ctx.charById[id]).filter(Boolean).map(c=>c.name).join(", ");
      rows += '<tr>'
        + '<td class="num">'+esc(scene.no)+'.'+esc(i+1)+'</td>'
        + '<td>'+esc(shotSizeOf(sh.size).label)+'</td>'
        + '<td>'+esc(shotAngleOf(sh.angle).label)+'</td>'
        + '<td>'+esc(shotMoveOf(sh.move).label)+' &middot; '+esc(shotLensOf(sh.lens).label)+'</td>'
        + '<td>'+esc(subs)+'</td>'
        + '<td class="act">'+esc(sh.action||"")+(sh.dialogue?(' <span class="dlg">&ldquo;'+esc(sh.dialogue)+'&rdquo;</span>'):"")+'</td>'
        + '<td class="comp">'+esc(sh.composition||"")+'</td>'
        + '</tr>';
    });
  });
  const html = '<!doctype html><html><head><meta charset="utf-8"><title>'+esc(title)+' \u2014 Shot List</title>'
    + '<style>'
    + 'body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#16181d;margin:40px;}'
    + 'h1{font-size:20px;margin:0 0 4px;} .sub{color:#666;font-size:12px;margin-bottom:20px;}'
    + 'table{border-collapse:collapse;width:100%;font-size:11.5px;}'
    + 'th,td{border:1px solid #d7dae0;padding:6px 8px;vertical-align:top;text-align:left;}'
    + 'th{background:#f3f4f6;font-size:10px;letter-spacing:.06em;text-transform:uppercase;color:#555;}'
    + 'tr.scenehdr td{background:#1b1e26;color:#fff;font-size:12px;padding:7px 8px;}'
    + 'td.num{font-variant-numeric:tabular-nums;white-space:nowrap;color:#666;} td.act{width:30%;} td.comp{width:24%;color:#444;}'
    + '.dlg{color:#7a5; font-style:italic;} @media print{body{margin:14mm;}}'
    + '</style></head><body>'
    + '<h1>'+esc(title)+' &mdash; Shot List</h1>'
    + '<div class="sub">'+(project&&project.format?esc(project.format)+' &middot; ':'')+'Generated by TURN</div>'
    + '<table><thead><tr><th>Shot</th><th>Size</th><th>Angle</th><th>Move / Lens</th><th>In frame</th><th>Action</th><th>Composition</th></tr></thead>'
    + '<tbody>'+rows+'</tbody></table>'
    + '<script>setTimeout(function(){try{window.print();}catch(e){}},350);<\/script>'
    + '</body></html>';
  const w = window.open("", "_blank");
  if(w){ w.document.open(); w.document.write(html); w.document.close(); }
}
window.exportShotList = exportShotList;
