/* shots-ui.jsx — The Art Room ▸ Shot List (React).
   Scene-grouped shot list. Each shot is ONE beat, carrying cinematographer grammar
   (size · angle · movement · lens), the subjects/location/props in frame, an action
   line and an editable composition note. The frame is generated by composing the
   scene's Style Bible grade + the location plate + the character/prop sheets as
   reference images (see buildShotPrompt). Reuses SheetFrame, useImageGen and the
   shared batch engine so it behaves exactly like the other Art Room tabs. */

const _el = React.createElement;

/* a labelled grammar dropdown (size / angle / move / lens) */
function GrammarSelect({ label, value, options, onChange }){
  return _el("label",{className:"shot-gsel"},
    _el("span",{className:"shot-gsel-lab"},label),
    _el("select",{className:"prop-select",value:value,onChange:e=>onChange(e.target.value)},
      options.map(o=>_el("option",{key:o.id,value:o.id,title:o.desc||""},o.label))));
}

function CameraSettingSelect({ label, value, options, onChange }){
  return _el("label",{className:"shot-gsel"},
    _el("span",{className:"shot-gsel-lab"},label),
    _el("select",{className:"prop-select",value:value||"auto",onChange:e=>onChange(e.target.value)},
      options.map(o=>_el("option",{key:o.id,value:o.id,title:o.desc||""},o.label))));
}

function AdvancedCameraSettings({ sh, onUpdate }){
  const c = { camera:"auto", lensType:"auto", focalLength:"auto", aperture:"auto", shutter:"auto", iso:"auto", ...(sh.cameraSettings||{}) };
  const patch = (key,val)=> onUpdate(sh.id,{ cameraSettings:{ ...c, [key]:val } });
  const active = typeof shotHasCameraSettings==="function" && shotHasCameraSettings(sh);
  const reset = ()=> onUpdate(sh.id,{ cameraSettings:{ camera:"auto", lensType:"auto", focalLength:"auto", aperture:"auto", shutter:"auto", iso:"auto" } });
  return _el(CardFold,{label:"Advanced cinematography"+(active?" · custom camera":" · Auto"),defaultOpen:false},
    _el("div",{className:"shot-camera-panel"},
      _el("div",{className:"shot-camera-head"},
        _el("div",{className:"shot-camera-note"},
          _el(Icon.info,{s:12}),"Leave controls on Auto unless you want this shot to carry explicit camera language into the frame prompt."),
        active && _el("button",{className:"shot-camera-reset",onClick:reset,title:"Reset all advanced camera settings to Auto"},"Reset to Auto")),
      _el("div",{className:"shot-camera-grid"},
        _el(CameraSettingSelect,{label:"Camera",value:c.camera,options:SHOT_CAMERA_BODIES,onChange:v=>patch("camera",v)}),
        _el(CameraSettingSelect,{label:"Lens type",value:c.lensType,options:SHOT_LENS_TYPES,onChange:v=>patch("lensType",v)}),
        _el(CameraSettingSelect,{label:"Focal length",value:c.focalLength,options:SHOT_FOCAL_LENGTHS,onChange:v=>patch("focalLength",v)}),
        _el(CameraSettingSelect,{label:"Aperture",value:c.aperture,options:SHOT_APERTURES,onChange:v=>patch("aperture",v)}),
        _el(CameraSettingSelect,{label:"Shutter",value:c.shutter,options:SHOT_SHUTTERS,onChange:v=>patch("shutter",v)}),
        _el(CameraSettingSelect,{label:"ISO / grain",value:c.iso,options:SHOT_ISO_GRAIN,onChange:v=>patch("iso",v)})),
      active && _el("div",{className:"shot-camera-preview"},
        (typeof shotCameraSettingsClause==="function") ? shotCameraSettingsClause(sh) : "")));
}

/* a toggle chip row for choosing which cast / props are in frame */
function FrameToggles({ label, items, selected, onToggle, emptyHint }){
  if(!items.length) return _el("div",{className:"shot-frame-empty"},emptyHint);
  return _el("div",{className:"shot-frame-row"},
    _el("span",{className:"shot-frame-lab"},label),
    _el("div",{className:"shot-chips"},
      items.map(it=>{
        const on = selected.indexOf(it.id)>=0;
        return _el("button",{key:it.id,className:"shot-chip"+(on?" on":""),onClick:()=>onToggle(it.id)},
          on?_el(Icon.check,{s:11}):null, it.name);
      })));
}

function ShotCard({ sh, scene, ctx, characters, propsAvail, beatText, prevShot, laterShots, isHead, isFirst, onToggleHead, onUpdate, onDelete, onView, batchActiveId, onBatchDone, onGenerateShot, onRegenDownstream, onStopChain, subLabel }){
  const loc = ctx.location;
  // who/what is in frame is DERIVED from the action text (single source of truth) — the
  // old manual tags are gone; this is what the prompt + references actually use.
  const _allChars = Object.values(ctx.charById||{});
  const inCastIds = (typeof inFrameCast==="function") ? inFrameCast(sh, scene, _allChars) : (sh.subjects||[]);
  const subjects = inCastIds.map(id=>ctx.charById[id]).filter(Boolean);
  const inPropIds = (typeof inFrameProps==="function") ? inFrameProps(sh, scene, ctx.charById, ctx.propById) : (sh.props||[]);
  // apply the SAME dressing filter the real attach path uses (collectShotRefs /
  // buildShotPrompt) — set-dressing sheets only ride on tight shots or when the
  // object leads the action; the plate delivers them in wides. Without this the
  // thumbnail strip SHOWS sheets that never actually attach.
  const inProps = inPropIds.map(id=>ctx.propById[id]).filter(Boolean)
    .filter(p=> (typeof shotPropAttachable!=="function") || shotPropAttachable(p, sh));
  const locWeight = (typeof locWeightForSize==="function") ? locWeightForSize(sh.size) : "primary";
  // the "Shot prompt" preview reflects what WILL generate: a non-head shot chains from the
  // previous frame (continuity_anchor present); the head renders fresh from the sheets.
  const promptCtx = { ...ctx, prevShot:prevShot||null, laterShots:laterShots||[] };
  const finalPrompt = combinedShotPrompt(sh, promptCtx);
  const chainPrompt = (typeof buildShotPrompt==="function") ? buildShotPrompt(sh, { ...promptCtx, prevFrameRole:true }) : finalPrompt;
  const previewPrompt = isHead ? finalPrompt : chainPrompt;

  // THE ROLLING SEED: a non-head shot generates as an image-edit off the PREVIOUS shot's
  // committed frame — it carries the colour grade AND the progressive physical state
  // (wetness, dirt, damage, wardrobe wear) forward, while this shot stages its own action.
  // A chain head renders from the sheets alone. ASYNC on purpose: in cloud mode
  // the previous frame often isn't in the sync cache
  // right after a reload — falling back to nbLoadImage keeps the chain intact.
  const deriveBase = async (gopts)=>{
    if(!prevShot || (gopts && (gopts.fresh || gopts.editInstruction))) return null;
    let u = (typeof nbGetImage==="function") ? nbGetImage(prevShot.id) : "";
    if(!u && typeof nbLoadImage==="function"){ try{ u = await nbLoadImage(prevShot.id); }catch(e){} }
    return u || null;
  };

  // reference SHEETS (the locked canon) — the seed frame rides separately as the base image.
  // Ordered by location weight: a wide leads with the set plate (geography reads); a tight
  // leads with the cast and demotes the plate to a background/grade anchor.
  const collectShotRefs = async (gopts)=>{
    const grab = async (id)=>{ let u = (typeof nbGetImage==="function") ? nbGetImage(id) : "";
      if(!u && typeof nbLoadImage==="function"){ try{ u = await nbLoadImage(id); }catch(e){} } return u; };
    const locSpec = loc ? [{ id:loc.id, note:(loc.name||"location")+" location coverage sheet (multiple views of ONE set)" }] : [];
    // identity anchors for the cast & props actually in THIS frame — derived from the
    // action text (inFrameCast/inFrameProps), never the fragile manual tags.
    const _chars = Object.values(ctx.charById||{});
    const inCast = (typeof inFrameCast==="function") ? inFrameCast(sh, scene, _chars) : (sh.subjects||[]);
    const inPr   = (typeof inFrameProps==="function") ? inFrameProps(sh, scene, ctx.charById, ctx.propById) : (sh.props||[]);
    const castSpec = inCast.map(id=>{ const c=ctx.charById[id]; return c?{ id, note:c.name+" character sheet" }:null; }).filter(Boolean);
    // dressing sheets attach only on tight shots / when the object is the action's
    // subject (shotPropAttachable) — MUST mirror buildShotPrompt's filter exactly,
    // or the prompt's image-map numbering mislabels the attached files
    const propSpec = inPr.map(id=>{ const p=ctx.propById[id];
      if(!p || (typeof shotPropAttachable==="function" && !shotPropAttachable(p, sh))) return null;
      return { id, note:p.name+" prop sheet" }; }).filter(Boolean);
    const ordered = (locWeight==="ambient") ? [...castSpec, ...locSpec, ...propSpec] : [...locSpec, ...castSpec, ...propSpec];
    const out = [];
    for(const s of ordered){ const u = await grab(s.id); if(u) out.push({ url:u, note:s.note, refId:s.id }); }
    return out;
  };

  const gen = useImageGen({
    id: sh.id, slotId: "shot-"+sh.id,
    buildFinal: ()=> finalPrompt,
    buildSimple: ()=> buildShotPrompt(sh, ctx),
    referenceFallback: deriveBase,
    buildFromBase: ()=> chainPrompt,
    attachments: collectShotRefs,
    // buildShotPrompt now names the reference stack in-prose (the spine + staging + References
    // block), so we don't append a second reference sentence here — that would just duplicate it.
    attachmentsText: ()=> "",
    buildEdit: (instr)=>
      "Edit this film frame. Apply ONLY this change: "+instr+". Keep the same shot size, lens, staging, "
      +"the same characters (identical faces & wardrobe), the same location and the same colour grade. Do not re-imagine the frame.",
    // Shot frames commonly carry a rolling seed plus several canon sheets. A
    // 640px reference is ample for identity/composition and keeps GPT Image 2
    // comfortably inside the proxy window. These are input references only:
    // generated quality and resolution always follow the user's selected controls.
    referenceMaxDim: 640,
  });

  // Every manual Generate / Regenerate enters the scene's ordered runner. If an earlier
  // shot in the chain isn't rendered yet, the runner asks the user to generate it first
  // (it's the anchor) rather than rendering out of order. Raw gen.generate() runs when active.
  const guardedGenerate = (gopts)=>{
    // An edit operates on THIS already-generated frame in place — it isn't a new chain
    // request, so it bypasses the ordered runner and edits the current frame directly.
    if(gopts && gopts.editInstruction){
      if(sh.locked) onUpdate(sh.id,{locked:false});
      return gen.generate(gopts);
    }
    return onGenerateShot ? onGenerateShot(sh.id) : gen.generate(gopts);
  };
  const genGuarded = Object.assign({}, gen, { generate: guardedGenerate });

  // batch auto-generate when this card is the active queue member
  // If this card remounts off-screen while its generation is already running
  // (the user navigated to another scene), resume watching that same run instead
  // of accidentally starting it again when it finishes.
  const batchStarted = React.useRef(batchActiveId===sh.id && gen.gening);
  const wasGening = React.useRef(gen.gening);
  React.useEffect(()=>{
    const mine = batchActiveId===sh.id;
    if(!mine){ batchStarted.current=false; wasGening.current=gen.gening; return; }
    if(!batchStarted.current && !gen.gening){ batchStarted.current=true; wasGening.current=false; gen.generate(); return; }
    if(batchStarted.current && wasGening.current && !gen.gening){ batchStarted.current=false; onBatchDone && onBatchDone(sh.id); }
    wasGening.current = gen.gening;
  },[batchActiveId, gen.gening, sh.id]);

  const toggleIn = (key, id)=>{ const cur = sh[key]||[]; const next = cur.indexOf(id)>=0 ? cur.filter(x=>x!==id) : [...cur, id];
    const patch = { [key]: next }; if(key==="subjects") patch.subjectsSet = true; onUpdate(sh.id, patch); };

  // REFERENCE IMAGES that influence this shot's frame — the scene KEY FRAME it derives
  // from, the LOCATION coverage plate, and the in-frame CHARACTER & PROP sheets. Shown as
  // small thumbnails (click to enlarge) so it's clear what canon art the generation locks
  // to. Recomputed from the live entity sheets (always displayable), keyed off the ids.
  const [refImgs, setRefImgs] = React.useState([]);    // seed frame + the canon sheets, ordered by location weight
  // the SEED is the previous shot's frame, whose image isn't part of this card's props — so when
  // it commits (uploaded OR generated), bump on its nb-gen-done so the seed thumb appears without a reload.
  const [prevSeedBump, setPrevSeedBump] = React.useState(0);
  React.useEffect(()=>{
    if(!prevShot) return;
    const pid = prevShot.id;
    const onDone = (e)=>{ if(e && e.detail && e.detail.id===pid) setPrevSeedBump(b=>b+1); };
    window.addEventListener("nb-gen-done", onDone);
    return ()=>window.removeEventListener("nb-gen-done", onDone);
  },[prevShot && prevShot.id]);
  const _refKey = [sh.id, prevShot&&prevShot.id, prevShot&&prevShot.locked?1:0, prevSeedBump, loc&&loc.id, locWeight,
    subjects.map(c=>c.id).join(","), inProps.map(p=>p.id).join(","), gen.genUrl||""].join("|");
  React.useEffect(()=>{
    let alive = true;
    (async ()=>{
      const grab = async (id)=>{ let u = (typeof nbGetImage==="function") ? nbGetImage(id) : "";
        if(!u && typeof nbLoadImage==="function"){ try{ u = await nbLoadImage(id); }catch(e){} } return u||""; };
      // the rolling SEED leads (the previous shot's frame), then the canon sheets ordered by weight
      const seedU = prevShot ? await grab(prevShot.id) : "";
      const seed = (prevShot && seedU) ? [{ url:seedU, label:"Previous shot · Beat "+(prevShot.beatN||"—"), kind:"seed", approved:!!prevShot.locked }] : [];
      const locItems = []; if(loc){ const u=await grab(loc.id); if(u) locItems.push({ url:u, label:(loc.name||"Location")+" plate", kind:"location" }); }
      const castItems = []; for(const c of subjects){ const u=await grab(c.id); if(u) castItems.push({ url:u, label:c.name, kind:"character" }); }
      const propItems = []; for(const p of inProps){ const u=await grab(p.id); if(u) propItems.push({ url:u, label:p.name, kind:"prop" }); }
      const sheetOrder = (locWeight==="ambient") ? [...castItems, ...locItems, ...propItems] : [...locItems, ...castItems, ...propItems];
      if(alive) setRefImgs([...seed, ...sheetOrder]);
    })();
    return ()=>{ alive=false; };
  },[_refKey]);

  const beatLabel = "Beat "+(sh.beatN||"\u2014");
  const initials = (sizeOf(sh.size).label||"SH");
  const waitingForShot = !!(batchActiveId && batchActiveId!==sh.id);

  return _el("div",{className:"sheet-card shot-card"+(batchActiveId===sh.id?" batch-on":""),"data-shot-card":sh.id},
    _el(SheetFrame,{ gen:genGuarded, slotId:"shot-"+sh.id, name:beatLabel, avatarColor:"linear-gradient(135deg,#7a6cae,#2a2440)",
      initials, drafted:true, drafting:false, onDraft:()=>{}, entity:sh, onView,
      slotPlaceholder:"Generate or drop a frame", noun:"frame", dropToImport:true, onStop:onStopChain,
      generateDisabled:waitingForShot,
      generateDisabledLabel:"Wait for current shot",
      generateDisabledTitle:"Another shot is generating. Wait for it to finish before starting this frame.",
      menuExtra: [
        onRegenDownstream ? {
          label:"Regenerate downstream",
          title:"Re-render every later shot in this scene in order, re-seeding each from the one before — use after changing this frame so propagated state stays current.",
          onClick:()=>onRegenDownstream(sh),
        } : null,
      ].filter(Boolean),
      extraMeta:[
        { k:"Size",  v: sizeOf(sh.size).label + (sizeOf(sh.size).name?(" — "+sizeOf(sh.size).name):"") },
        { k:"Angle", v: angleOf(sh.angle).label },
        { k:"Move",  v: moveOf(sh.move).label },
        { k:"Lens",  v: lensOf(sh.lens).label },
      ],
      onDelete:()=>onDelete(sh.id), deleteLabel:"Delete shot" }),
    _el("div",{className:"sheet-body"},
      // reference images this frame is built from — the rolling SEED (the previous shot's
      // frame) leads, then the in-frame Character, Prop & Location sheets, ordered by weight.
      // Click a thumb to enlarge. Read-only: who/what is in frame is auto-read from the Action.
      refImgs.length>0 && _el("div",{className:"shot-refs"},
        _el("div",{className:"shot-refs-row"},
          refImgs.map((r,i)=>_el("button",{key:"a"+i,className:"shot-ref-thumb "+r.kind+(r.kind==="seed"&&r.approved===false?" provisional":""),
            title:(r.kind==="seed" ? (r.label+" — "+(r.approved?"approved seed":"provisional seed (not yet approved)")) : r.label)+" — click to enlarge",
            onClick:()=>onView&&onView(r.url,{name:r.label})},
            _el("img",{src:r.url,alt:r.label,loading:"lazy"}),
            r.kind==="seed" && _el("span",{className:"shot-ref-seedtag"+(r.approved?" ok":"")}, r.approved?"✓":"·"))))),
      _el("div",{className:"shot-head"},
        // order, left-to-right: Beat · Clip · Head · (Approve, once a frame exists)
        _el("div",{className:"shot-head-right"},
          _el("div",{className:"shot-beat-tag"},beatLabel),
          subLabel && _el("div",{className:"shot-beat-tag sub",title:"This beat has multiple shots (coverage) — this is setup "+subLabel+" in cut order"},"Shot "+subLabel),
          sh.priority && _el("span",{className:"shot-priority-badge",
            title:"Priority — the setup carrying this beat's emotional core (the protected moment). Spend your regeneration attention here first, and approve it carefully as a seed."},
            _el(Icon.bolt,{s:10}),"Priority"),
          // chain head — the scene's first shot is always a head; flagging a later shot
          // starts a FRESH look (a hard cut that won't inherit the previous frame's state)
          _el("button",{className:"shot-anchor-btn"+(isHead?" on":""), disabled:isFirst,
            title: isFirst
              ? "This is the scene's first shot — always the chain head; the scene's whole look starts here."
              : (isHead
                ? "This shot is a FRESH START (chain break) — it won't be seeded by the previous frame. Click to rejoin the chain."
                : "Make this a fresh start — a hard cut that won't inherit the previous frame's look or state."),
            onClick:()=> !isFirst && onToggleHead && onToggleHead(sh)},
            _el(Icon.pin,{s:11}), isHead && _el("span",null, isFirst?"Head":"Fresh")),
          // approve / lock — marks this frame as the APPROVED seed the next shot chains from
          gen.genUrl && _el("button",{className:"shot-lock-btn"+(sh.locked?" on":""),
            title: sh.locked
              ? "Approved — this frame is the locked seed the next shot builds on. Click to unlock."
              : "Approve this frame as the seed the next shot chains from.",
            onClick:()=>onUpdate(sh.id,{ locked: !sh.locked })},
            _el(Icon.check,{s:11}), _el("span",null, sh.locked?"Approved":"Approve")),
          window.QaCheckButton && _el(window.QaCheckButton,{ gen, name:beatLabel, noun:"shot frame", className:"shot-lock-btn",
            specFields:()=>({ action:(sh.action||""), composition:(sh.composition||"") }),
            onApplySpec:(patch)=>onUpdate(sh.id, patch) }))),

      // the SCRIPT BEAT this shot covers — straight from the scene's beat map, so the
      // shot's source text is on the card (read-only; edit beats in the Writers' Room)
      beatText && _el("div",{className:"shot-beat-script",
        title:"The script beat this shot covers (drive — reaction), from this scene's beat map. Read-only here — edit beats in the Writers' Room inspector."},
        _el("span",{className:"shot-beat-script-lab"},"Script beat"),
        _el("span",{className:"shot-beat-script-body"},beatText)),

      // WHY this shot exists (the designer's purpose) + which micro-beats it covers
      (sh.purpose || (Array.isArray(sh.covers)&&sh.covers.length>0)) && _el("div",{className:"shot-purpose"},
        (Array.isArray(sh.covers)&&sh.covers.length>0) && _el("span",{className:"shot-covers-chip",
          title:"The micro-beats of this beat that this shot covers (see the numbered rail above the shots)"},
          "covers "+sh.covers.map(_circ).join(" ")),
        sh.purpose && _el("span",{className:"shot-purpose-t"},sh.purpose)),

      // cinematographer grammar
      _el("div",{className:"shot-grammar-grid"},
        _el(GrammarSelect,{label:"Size",value:sh.size,options:SHOT_SIZES,onChange:v=>onUpdate(sh.id,{size:v})}),
        _el(GrammarSelect,{label:"Angle",value:sh.angle,options:SHOT_ANGLES,onChange:v=>onUpdate(sh.id,{angle:v})}),
        _el(GrammarSelect,{label:"Move",value:sh.move,options:SHOT_MOVES,onChange:v=>onUpdate(sh.id,{move:v})}),
        _el(GrammarSelect,{label:"Lens",value:sh.lens,options:SHOT_LENSES,onChange:v=>onUpdate(sh.id,{lens:v})})),

      _el(AdvancedCameraSettings,{sh,onUpdate}),

      // the action — what we see in this frame
      _el(SheetField,{label:"Action \u2014 what we see in this frame",value:sh.action,multiline:true,
        placeholder:"One vivid present-tense beat of on-screen action\u2026",onCommit:v=>onUpdate(sh.id,{action:v})}),

      // composition (the depth-grid "vary" layer) + dialogue
      _el(SheetField,{label:"Composition \u2014 framing, blocking, depth, eyeline",value:sh.composition,multiline:true,
        placeholder:"Where subjects sit in frame, foreground/background, eyeline\u2026",onCommit:v=>onUpdate(sh.id,{composition:v})}),
      // multiline: dialogue lines routinely outgrow a single-line input, which clipped
      // them visually (the full text was stored, just unreadable/uneditable)
      _el(SheetField,{label:"Dialogue (optional)",value:sh.dialogue,multiline:true,
        placeholder:"A short line spoken in this beat\u2026",onCommit:v=>onUpdate(sh.id,{dialogue:v})}),

      _el(CardFold,{label:"In frame",defaultOpen:false},
        // read-only: derived from the action text, the single source the prompt uses —
        // no manual toggles to drift out of sync. Edit the ACTION to change who's in frame.
        _el("div",{className:"shot-inframe-auto"},
          _el("div",{className:"shot-inframe-row"},
            _el("span",{className:"shot-frame-lab"},"Characters"),
            subjects.length
              ? subjects.map(c=>_el("span",{key:c.id,className:"shot-inframe-chip"},c.name))
              : _el("span",{className:"shot-inframe-none"},"none named in the action")),
          _el("div",{className:"shot-inframe-row"},
            _el("span",{className:"shot-frame-lab"},"Props"),
            inProps.length
              ? inProps.map(p=>_el("span",{key:p.id,className:"shot-inframe-chip prop"},p.name))
              : _el("span",{className:"shot-inframe-none"},"none named in the action")),
          _el("div",{className:"shot-inframe-hint"},
            _el(Icon.sparkles,{s:11}),"Auto-read from the action — edit the Action line to change who/what is in frame.")),
        _el("div",{className:"shot-loc-note"},
          _el(Icon.globe,{s:12}),
          loc ? _el("span",null,"Location: ",_el("b",null,loc.name),(typeof stagingHasContent==="function"&&stagingHasContent(loc))?" \u00b7 depth grid inherited":" \u00b7 no depth grid staged")
              : _el("span",null,"No location resolved for this scene \u2014 set the scene's slugline / pull locations."))),

      _el(CardFold,{label:"Shot prompt",defaultOpen:false},
        _el(CopyBox,{label: isHead ? "Final frame prompt \u2014 master + grade + references" : "Final frame prompt \u2014 master + grade + continuity anchor + references",text:previewPrompt}),
        _el(SheetField,{label:"Negative prompt \u2014 exclude",value:sh.negativePrompt||"",multiline:true,
          placeholder:shotNegativePrompt({}),onCommit:v=>onUpdate(sh.id,{negativePrompt:v})}))));
}

const CONF_LABELS = ["Inner","Personal","Extra-personal"];
function SceneCtxItem({ k, v }){
  if(!v) return null;
  return _el("div",{className:"ssx-item"}, _el("div",{className:"ssx-k"},k), _el("div",{className:"ssx-v"},v));
}

function SceneStyleChip({ project, sceneId }){
  // Keep this live: Shots should never cache a scene's style on the shot card.
  // The Styles tab owns the scene→preset map, so every Shots render resolves the
  // current assignment from project.styleBible.
  const preset = (typeof scenePreset==="function") ? scenePreset(project, sceneId) : null;
  if(!preset) return _el("span",{className:"shot-style-chip empty",title:"No Style Bible preset assigned to this scene yet. Use the Styles tab / Light the film."},
    _el(Icon.layers,{s:11}),"No style preset");
  const pal = (preset.palette||[]).slice(0,3);
  const title = [
    preset.name || "Scene style",
    preset.grade,
    preset.lighting ? ("Lighting: "+preset.lighting) : "",
    preset.lens ? ("Lens: "+preset.lens) : "",
    preset.texture ? ("Texture: "+preset.texture) : "",
  ].filter(Boolean).join("\n");
  return _el("span",{className:"shot-style-chip",title},
    _el(Icon.layers,{s:11}),
    _el("span",{className:"shot-style-chip-text"},"Style: "+(preset.name||"Scene preset")),
    !!pal.length && _el("span",{className:"shot-style-swatches"},
      pal.map((c,i)=>_el("span",{key:i,className:"shot-style-swatch",style:{background:c}}))));
}

/* circled micro-beat numerals: 1..20 -> \u2460.. ; beyond that "#n" */
function _circ(n){ return (n>=1&&n<=20) ? String.fromCharCode(0x245F+n) : ("#"+n); }
function SceneShotGroup({ scene, shots, ctx, characters, propsAvail, beatsMap, pager, onUpdate, onDelete, onView,
  onAddShot, onSplitBeat, splittingBeat, onDraftScene, draftingScene, batchActiveId, onBatchDone, open, onToggle, onGenerateShot, onRegenDownstream,
  onRenderScene, renderBusy, onStopChain }){
  const loc = ctx.location;
  const driver = scene.driver ? ctx.charById[scene.driver] : null;
  // scene-level context (driver/reactor/antagonism/goal/conflict) — driver+goal+conflict from the
  // Scene inspector, reactor+antagonism from the beat-map, exactly as the Writers' Room shows them.
  const bm = (beatsMap||{})[scene.id] || {};
  const driverName = driver ? driver.name : (bm.driverLabel||"");
  const confLab = scene.conf ? CONF_LABELS[scene.conf-1] : "";
  // the rolling chain: shots render in order, each seeding from its predecessor. The first
  // shot is always the chain HEAD; a shot flagged .anchor is an explicit FRESH START (a hard
  // cut mid-scene that won't inherit the previous frame). toggleHead flips that flag.
  const ordered = (typeof sceneShotsOrdered==="function") ? sceneShotsOrdered(shots) : shots;
  // BEAT LANES model: contiguous chain-order groups by beat number
  const lanes = (()=>{ const Ls=[]; ordered.forEach(sh=>{ const n=sh.beatN||0;
    let L=Ls[Ls.length-1]; if(!L || L.n!==n){ L={ n, shots:[] }; Ls.push(L); } L.shots.push(sh); });
    return Ls; })();
  // ONE BEAT AT A TIME (user ruling 2026-07-20): the group shows a single beat
  // lane with a scene-pager-style ‹ › beat pager — no stacked lanes, no folding.
  // EXCEPTION: while a BATCH renders, ALL lanes mount — the scene runner advances
  // by watching MOUNTED cards, and an unmounted card would stall the queue.
  const [beatIdx, setBeatIdx] = React.useState(0);
  const stripRefs = React.useRef({});
  // merged scene navigator (user ruling 2026-07-19): the pager lives IN this header
  const [jumpOpen, setJumpOpen] = React.useState(false);
  // micro-beat <-> shot hover linking (per visible lane): hovering a micro chip
  // glows the shots that cover it; hovering a shot glows its micro chips
  const [hiMicro, setHiMicro] = React.useState(null);      // {laneN, n}
  const [hiCovers, setHiCovers] = React.useState(null);    // {laneN, covers:[..]}
  React.useEffect(()=>{ if(!jumpOpen) return;
    const close=(e)=>{ if(!e.target.closest || !e.target.closest(".ssg-jump")) setJumpOpen(false); };
    document.addEventListener("mousedown", close); return ()=>document.removeEventListener("mousedown", close); },[jumpOpen]);
  const showAllLanes = !!batchActiveId;
  const _bi = Math.max(0, Math.min(beatIdx, lanes.length-1));
  const pageShots = (n, dir)=>{
    const el = stripRefs.current[n]; if(!el) return;
    const cell = el.querySelector(".beat-shot-cell");
    const w = cell ? (cell.getBoundingClientRect().width + 18) : 420;
    try{ el.scrollBy({ left: dir*w, behavior:"smooth" }); }catch(e){ el.scrollLeft += dir*w; }
  };
  // ONE pair of side arrows per lane (the pager bar is gone — user ruling 2026-07-19):
  // they walk this beat's shots first, and at the strip's edge they STEP TO the
  // previous/next beat. While a batch mounts all lanes they only page shots.
  const stepSide = (L, dir)=>{
    const el = stripRefs.current[L.n];
    const canScroll = el && el.scrollWidth > el.clientWidth + 8;
    if(canScroll){
      const atEnd   = el.scrollLeft + el.clientWidth >= el.scrollWidth - 8;
      const atStart = el.scrollLeft <= 8;
      if(dir>0 ? !atEnd : !atStart) return pageShots(L.n, dir);
    }
    if(showAllLanes) return;
    setBeatIdx(dir>0 ? Math.min(lanes.length-1, _bi+1) : Math.max(0, _bi-1));
  };
  const firstId = ordered[0] && ordered[0].id;
  const toggleHead = (target)=> { if(target && target.id!==firstId) onUpdate(target.id, { anchor: !target.anchor }); };
  // the scene's clip sequences (shared partition — Storyboard clip boards + the Stage);
  // the per-clip budget comes from the project FORMAT (clipMaxFor)
  const clipMax = (typeof clipMaxFor==="function") ? clipMaxFor(ctx.project) : 15;

  // WHOLE-SCENE video prompt — the shared builder (shots.jsx sceneVideoPromptText):
  // the same text the Stage's whole-scene packing mode auto-fills its prompt box with.
  // Speaker attribution rides the Stage's resolver (no script drafts in this scope,
  // so it leans on the beat map + action-order fallback).
  const sceneVideoPrompt = ()=> (typeof window.sceneVideoPromptText==="function")
    ? window.sceneVideoPromptText(scene, ordered, { location:loc, project:ctx.project,
        speakerOf:(sh)=> (typeof stageDialogueSpeaker==="function")
          ? ((stageDialogueSpeaker(scene, null, beatsMap, sh, { characters, charById:ctx.charById })||{}).name||"")
          : "" })
    : "";
  const copyScenePrompt = async ()=>{
    const t = sceneVideoPrompt();
    if(!t){ if(window.appToast) window.appToast("No shot actions yet — draft this scene's shots first."); return; }
    // belt & braces: async clipboard API first, execCommand fallback second (covers
    // non-secure contexts), manual dialog last — and the toast only claims success
    // when a copy REALLY landed.
    let ok = false;
    try{ if(navigator.clipboard && navigator.clipboard.writeText){ await navigator.clipboard.writeText(t); ok = true; } }catch(e){}
    if(!ok){ try{
      const ta = document.createElement("textarea"); ta.value = t;
      ta.style.position = "fixed"; ta.style.opacity = "0";
      document.body.appendChild(ta); ta.select();
      ok = document.execCommand("copy");
      document.body.removeChild(ta);
    }catch(e){} }
    if(ok){ if(window.appToast) window.appToast("Scene "+String(scene.no).padStart(2,"0")+" video prompt copied — "+ordered.length+" shot"+(ordered.length===1?"":"s")+" combined"); }
    else window.prompt("Copy the scene video prompt:", t);
  };
  return _el("div",{className:"shot-scene-group"+(open?"":" collapsed")},
    // ONE merged card (user ruling 2026-07-19): scene navigator + title/style/meta +
    // context grid, redundancy removed (number/driver/location each said once).
    // "Copy video prompt" retired (clips live on the Stage); scene-level "Add shot"
    // retired (every beat lane header has its own "Add shot").
    _el("div",{className:"shot-scene-card"},
    _el("div",{className:"shot-scene-head merged"},
      pager && _el("button",{className:"scene-pager-arrow",disabled:pager.idx<=0,onClick:pager.onPrev,
        title:"Previous scene (\u2190)","aria-label":"Previous scene"},_el(Icon.chevL,{s:18})),
      _el("div",{className:"shot-scene-meta"},
        pager && _el("span",{className:"scene-pager-no ssg-jump",role:"button",tabIndex:0,title:"Jump to a scene",
          onClick:()=>setJumpOpen(o=>!o)},
          "Scene "+(pager.idx+1)+" of "+pager.total, _el(Icon.chevD,{s:10}),
          jumpOpen && _el("div",{className:"scene-pager-menu",onClick:(e)=>e.stopPropagation()},
            pager.scenes.map((sx,i)=>_el("button",{key:sx.id||i,className:"scene-pager-menu-item"+(i===pager.idx?" on":""),
              onClick:()=>{ pager.onJump(i); setJumpOpen(false); }},
              _el("span",{className:"scene-pager-menu-no"},String(sx.no||(i+1)).padStart(2,"0")),
              _el("span",{className:"scene-pager-menu-t"},sx.title||"Untitled scene"),
              i===pager.idx && _el(Icon.check,{s:13}))))),
        _el("div",{className:"shot-scene-title"},scene.title||"Untitled scene"),
        _el("div",{className:"shot-scene-style-row"},_el(SceneStyleChip,{project:ctx.project,sceneId:scene.id})),
        _el("div",{className:"shot-scene-sub"},
          (loc?("Location: "+loc.name+"   \u00b7   "):"")+shots.length+" shot"+(shots.length!==1?"s":""))),
      _el("div",{className:"shot-scene-acts"},
        onRenderScene && _el("button",{className:"char-draft-btn primary",disabled:!!renderBusy,onClick:()=>onRenderScene(scene),
          title:"Render this scene in order, each shot seeded by the previous frame, auto-approving each. Approved frames are retained as seeds."},
          _el(Icon.sparkles,{s:12}), renderBusy?"Rendering\u2026":("Render Scene "+String(scene.no).padStart(2,"0")+" in order")),
        _el("button",{className:"char-draft-btn ghost"+(draftingScene?" busy":""),disabled:!!draftingScene,onClick:()=>onDraftScene(scene),
          title:"Re-derive this scene's shot list from its beats (replaces the current shots)"},
          _el(Icon.layers,{s:12}), draftingScene?"Drafting\u2026":"Re-draft shots")),
      pager && _el("button",{className:"scene-pager-arrow",disabled:pager.idx>=pager.total-1,onClick:pager.onNext,
        title:"Next scene (\u2192)","aria-label":"Next scene"},_el(Icon.chevR,{s:18}))),
    open && _el("div",{className:"shot-scene-ctx"},
      scene.summary && _el("div",{className:"ssx-desc"},scene.summary),
      _el("div",{className:"ssx-grid"},
        _el(SceneCtxItem,{k:"Driver",v:driverName}),
        _el(SceneCtxItem,{k:"Reactor",v:bm.reactorLabel}),
        _el(SceneCtxItem,{k:"Driver's goal",v:scene.objective}),
        _el(SceneCtxItem,{k:"Antagonism",v:bm.obstacle}),
        scene.conf && _el("div",{className:"ssx-item"},
          _el("div",{className:"ssx-k"},"Conflict level"),
          _el("div",{className:"ssx-conf"},
            confLab && _el("span",{className:"ssx-conf-lab"},confLab),
            _el("div",{className:"ssx-pips"},
              [1,2,3].map(i=>_el("span",{key:i,className:"ssx-pip"+(i<=scene.conf?" on":"")})))))))),
    // (the separate beat-pager bar was REMOVED — user ruling 2026-07-19: the
    // lane's own side arrows walk the shots and then step beats)
    // BEAT LANES — the beat is the dramatic unit; each owns 1..N shots (coverage)
    // rendered as a HORIZONTAL strip with edge-pinned ‹ › shot arrows. Normally
    // only the paged beat renders; a running batch mounts every lane.
    open && _el(React.Fragment,null, (showAllLanes ? lanes : lanes.slice(_bi,_bi+1)).map(L=>{
      const beatRow = (bm.rows||[]).find(r=>String(r.n)===String(L.n));
      const beatText = beatRow
        ? [ (beatRow.drive&&beatRow.drive.d||"").trim(), (beatRow.react&&beatRow.react.d||"").trim() ].filter(Boolean).join(" — ")
        : "";
      const verbs = beatRow ? [ (beatRow.drive&&beatRow.drive.a||"").trim(), (beatRow.react&&beatRow.react.a||"").trim() ].filter(Boolean).join(" / ") : "";
      const isTurn = String(bm.turnAt||"")===String(L.n);
      const chg = beatRow && beatRow.charge!=null && beatRow.charge!=="" ? Number(beatRow.charge) : null;
      const busyKey = scene.id+"#"+L.n;
      return _el("div",{key:"lane-"+L.n,className:"beat-lane"+(isTurn?" turn":"")},
        _el("div",{className:"beat-lane-head"},
          _el("span",{className:"beat-lane-no"},"Beat "+L.n+(lanes.length>1?(" of "+lanes.length):"")),
          verbs && _el("span",{className:"beat-lane-verbs"},verbs),
          isTurn && _el("span",{className:"beat-lane-turn"},_el(Icon.bolt,{s:10}),"Turning point"),
          (chg!=null) && _el("span",{className:"beat-lane-chg "+(chg>0?"pos":chg<0?"neg":"")},(chg>0?"+":"")+chg),
          _el("span",{className:"beat-lane-count"},L.shots.length+" shot"+(L.shots.length!==1?"s":"")),
          _el("div",{className:"beat-lane-acts"},
            // per-beat design button retired (user ruling 2026-07-19): the beat-by-beat
            // mapping is AUTOMATIC — aiDraftShots designs 1-4 shots per beat on
            // "Design all shots" / "Re-draft shots". "Add shot" stays as the manual hatch.
            onAddShot && _el("button",{className:"beat-lane-btn ghost",
              title:"Add one manual shot to this beat — it joins the rolling chain after the beat's last shot",
              onClick:()=>onAddShot(scene.id, L.n)},
              _el(Icon.plus,{s:11}),"Add shot"))),
        // MICRO-BEAT LAYER (designed with the shots): what the camera must PROTECT,
        // then the beat's discrete filmable actions — amber = not covered by any shot
        (()=>{ const plan = L.shots.map(x=>x.beatPlan).find(Boolean);
          if(!plan || !plan.micro || !plan.micro.length) return null;
          return _el(React.Fragment,null,
            plan.protect && _el("div",{className:"beat-protect",
              title:"The beat's emotional core — the moment the coverage is built to protect. The \u2605 Priority shot carries it."},
              _el(Icon.bolt,{s:10}), _el("b",null,"Protect:"), " "+plan.protect),
            _el("div",{className:"beat-micro-rail"},
              plan.micro.map((m,i)=>{ const n=i+1;
                const covered = L.shots.some(x=>Array.isArray(x.covers)&&x.covers.includes(n));
                const on = (hiCovers && hiCovers.laneN===L.n && hiCovers.covers.includes(n))
                        || (hiMicro && hiMicro.laneN===L.n && hiMicro.n===n);
                return _el("span",{key:n,
                  className:"beat-micro-chip"+(covered?"":" uncovered")+(on?" on":""),
                  onMouseEnter:()=>setHiMicro({laneN:L.n,n}), onMouseLeave:()=>setHiMicro(null),
                  title: covered
                    ? "Micro-beat "+n+" \u2014 hover to see the shot(s) covering it"
                    : "No shot covers this action yet \u2014 add a shot to this beat or re-draft the scene's shots"},
                  _circ(n)+" "+String(m).replace(/^\s*\d+[\.\)]\s*/,"")); })));
        })(),
        // SIDE ARROWS (scene-navigator style): pinned at the lane's edges so the
        // eye stays in place while paging through this beat's shots
        (showAllLanes ? L.shots.length>1 : (lanes.length>1 || L.shots.length>1)) && _el("button",{
          className:"beat-lane-side prev", disabled:!showAllLanes && _bi<=0 && L.shots.length<=1,
          title:"Previous shot — at the first shot, steps to the previous beat",
          onClick:(e)=>{ e.stopPropagation(); stepSide(L,-1); }},
          _el(Icon.chevL,{s:16})),
        (showAllLanes ? L.shots.length>1 : (lanes.length>1 || L.shots.length>1)) && _el("button",{
          className:"beat-lane-side next", disabled:!showAllLanes && _bi>=lanes.length-1 && L.shots.length<=1,
          title:"Next shot — at the last shot, steps to the next beat",
          onClick:(e)=>{ e.stopPropagation(); stepSide(L,1); }},
          _el(Icon.chevR,{s:16})),
        _el("div",{className:"beat-lane-strip",ref:(el)=>{ stripRefs.current[L.n]=el; }},
          L.shots.map((sh,li)=>{
            const prevShot = (typeof prevShotOf==="function") ? prevShotOf(sh, ordered) : null;
            const _si = ordered.findIndex(x=>x.id===sh.id);
            const _hi = hiMicro && hiMicro.laneN===L.n && Array.isArray(sh.covers) && sh.covers.includes(hiMicro.n);
            return _el("div",{key:sh.id,className:"beat-shot-cell"+(_hi?" hi":""),
              onMouseEnter:()=>{ if(Array.isArray(sh.covers)&&sh.covers.length) setHiCovers({laneN:L.n,covers:sh.covers}); },
              onMouseLeave:()=>setHiCovers(null)},
              _el(ShotCard,{sh,scene,ctx,characters,propsAvail,beatText,
                prevShot, laterShots:(_si>=0?ordered.slice(_si+1):[]), isHead:!prevShot, isFirst:(sh.id===firstId), onToggleHead:toggleHead,
                onUpdate,onDelete,onView,batchActiveId,onBatchDone,onGenerateShot,onRegenDownstream,onStopChain,
                subLabel: L.shots.length>1 ? String.fromCharCode(65+li) : null })); })));
    })));
}

function ShotList({ project, scenes, characters, props, locations, shots, beatsMap,
  onUpdateShot, onAddShot, onDeleteShot, onSplitBeat, splittingBeat, onDraftSceneShots, draftingSceneShots, onDraftAllShots, draftingAllShots, onShoot }){
  const [view, setView] = React.useState(null);
  const batch = useBatchGen();
  const batchActiveId = batch.activeId;
  // the rolling-keyframe CHAIN: render a scene's shots in order, each seeded by the previous
  // frame. Each rendered frame auto-locks (becomes the approved seed) and the chain continues.
  const [chain, setChain] = React.useState(null);   // { ids, idx, total } | null while running
  const chainRef = React.useRef(null); chainRef.current = chain;
  const chainStartingRef = React.useRef(false);
  // small centered popup — e.g. "generate the earlier shot first" when a chain is clicked
  // out of order. Auto-dismisses; click X/the scrim or press Esc to close sooner.
  const [notice, setNotice] = React.useState("");
  React.useEffect(()=>{
    if(!notice) return;
    const t = setTimeout(()=>setNotice(""), 4000);
    const onKey = (e)=>{ if(e.key==="Escape"){ e.preventDefault(); setNotice(""); } };
    window.addEventListener("keydown", onKey, true);
    return ()=>{ clearTimeout(t); window.removeEventListener("keydown", onKey, true); };
  },[notice]);
  // "Design all shots" is non-destructive — it only breaks down scenes that have NO shots yet.
  // Track how many it set out to do so we can show a live progress bar (and tell the user when
  // there's nothing to do, instead of the click appearing to do nothing).
  const scenesNeedingShots = ()=>{ const have = new Set((shots||[]).map(s=>s.sceneId)); return (scenes||[]).filter(s=>!have.has(s.id)); };
  const [designTotal, setDesignTotal] = React.useState(0);
  React.useEffect(()=>{ if(!draftingAllShots) setDesignTotal(0); },[draftingAllShots]);   // clear the bar when the run ends
  const handleDesignAll = ()=>{
    if(draftingAllShots) return;
    const need = scenesNeedingShots().length;
    if(!need){ setNotice("Every scene already has shots. Open a scene and use ‘Re-draft shots’ to redesign just that one."); return; }
    setDesignTotal(need);
    onDraftAllShots && onDraftAllShots();
  };
  // per-scene fold state (persisted). DEFAULT: everything folded except the first
  // scene — a long shot list opens scannable, not as one endless scroll.
  const [collapsed, setCollapsed] = React.useState(()=>{ try{ return JSON.parse(localStorage.getItem("turn_shots_collapsed")||"{}")||{}; }catch(e){ return {}; } });
  React.useEffect(()=>{ try{ localStorage.setItem("turn_shots_collapsed", JSON.stringify(collapsed)); }catch(e){} },[collapsed]);
  const toggleScene = (id)=> setCollapsed(c=>({ ...c, [id]: !c[id] }));
  // seed the default fold once scenes hydrate (an empty saved map = never touched)
  const foldSeeded = React.useRef(false);
  React.useEffect(()=>{
    if(foldSeeded.current || !(scenes||[]).length) return;
    foldSeeded.current = true;
    if(Object.keys(collapsed).length) return;   // the user has a real fold state already
    const m = {};
    (scenes||[]).slice().sort((a,b)=>(a.no||0)-(b.no||0)).forEach((s,i)=>{ if(i>0) m[s.id]=true; });
    setCollapsed(m);
  },[(scenes||[]).length]);

  const charById = React.useMemo(()=>{ const m={}; (characters||[]).forEach(c=>m[c.id]=c); return m; },[characters]);
  const propById = React.useMemo(()=>{ const m={}; (props||[]).forEach(p=>m[p.id]=p); return m; },[props]);
  const shotById = React.useMemo(()=>{ const m={}; (shots||[]).forEach(s=>m[s.id]=s); return m; },[shots]);

  // one-time sanity pass: re-anchor each shot's subjects to the cast NAMED in its
  // action/composition text (earlier drafts could drift to background cast — e.g. a
  // beat about Amara getting tagged with other characters). Skips shots the user has
  // set by hand (subjectsSet), and only changes a shot when the text clearly names a
  // DIFFERENT set, so valid/pronoun-only shots are left alone.
  const subjFixed = React.useRef(false);
  React.useEffect(()=>{
    if(subjFixed.current || typeof scanTextForChars!=="function" || !(shots||[]).length) return;
    subjFixed.current = true;
    const beatActionOf = (sh)=>{ const b=(beatsMap||{})[sh.sceneId];
      const row = b && (b.rows||[]).find(r=>String(r.n)===String(sh.beatN));
      return row ? ((row.drive&&row.drive.d)||(row.react&&row.react.d)||"") : ""; };
    (shots||[]).forEach(sh=>{
      const patch = {};
      // backfill an empty action from its originating beat (a draft can leave it blank)
      let action = sh.action;
      if(!String(action||"").trim()){ const ba = beatActionOf(sh); if(ba){ action = ba; patch.action = ba; } }
      // re-anchor subjects to the (possibly backfilled) action text, unless set by hand
      if(!sh.subjectsSet){
        const named = scanTextForChars((action||"")+" "+(sh.composition||""), characters);
        if(named.length){ const cur = sh.subjects||[];
          const same = named.length===cur.length && named.every(id=>cur.indexOf(id)>=0);
          if(!same) patch.subjects = named; }
      }
      if(Object.keys(patch).length) onUpdateShot(sh.id, patch);
    });
  },[(shots||[]).length]);
  const ctxFor = (scene)=>({ scene, location:(typeof locationForScene==="function")?locationForScene(locations,scene.id):null,
    charById, propById, project, locations:locations||[] });

  const ordered = React.useMemo(()=> (scenes||[]).slice().sort((a,b)=>(a.no||0)-(b.no||0)),[scenes]);
  const shotsByScene = React.useMemo(()=>{ const m={}; (shots||[]).forEach(s=>{ (m[s.sceneId]=m[s.sceneId]||[]).push(s); });
    Object.values(m).forEach(arr=>arr.sort((a,b)=>(a.order||0)-(b.order||0) || (a.beatN||0)-(b.beatN||0))); return m; },[shots]);
  const scenesWithShots = ordered.filter(s=>(shotsByScene[s.id]||[]).length);

  // "Export shot list" moved into the top bar's ⋮ menu (user ruling 2026-07-19).
  // Register the trigger while this tab is mounted — no deps, so the closure
  // always sees the current shots; the menu shows the item only when this exists.
  React.useEffect(()=>{ window.turnExportShotList = ()=>exportShotList(scenesWithShots, shotsByScene, ctxFor, project, beatsMap);
    return ()=>{ delete window.turnExportShotList; }; });

  // Always show ONE user-selected scene. A generating scene may remain mounted
  // off-screen so its request can finish while the arrows browse elsewhere.
  const [pIdx, setPIdx] = useScenePager(scenesWithShots.length);
  const shotsForGroup = (sid)=> shotsByScene[sid]||[];
  const pIdxC = Math.min(pIdx, Math.max(0, scenesWithShots.length-1));
  const activeShotId = batchActiveId || (chain && chain.ids && chain.ids[chain.idx]) || null;
  const activeShot = activeShotId ? shotById[activeShotId] : null;
  const activeSceneIdx = activeShot ? scenesWithShots.findIndex(s=>s.id===activeShot.sceneId) : -1;
  const visibleIdx = pIdxC;
  const curScene = scenesWithShots[visibleIdx];
  const visibleScenes = [curScene].filter(Boolean);
  const renderBusy = !!batchActiveId || !!chain;
  const runnerScene = activeSceneIdx>=0 && activeSceneIdx!==visibleIdx ? scenesWithShots[activeSceneIdx] : null;
  const sceneNoOf = (sid)=>{ const s=(scenes||[]).find(x=>x.id===sid); return s ? s.no : sid; };

  // ---- the rolling-keyframe CHAIN runner ----------------------------------------
  // Render a scene's shots IN ORDER, each seeded by the previous one's frame. A LOCKED
  // (approved) shot is treated as done \u2014 it seeds the next but isn't re-rendered. Gate ON \u2192
  // pause after each shot for approval; OFF \u2192 auto-lock and continue. Drives the existing
  // sequential batch one shot at a time (useBatchGen is shared, so it isn't modified).
  const chainOrderIds = (list)=> ((typeof sceneShotsOrdered==="function")?sceneShotsOrdered(list):(list||[])).map(s=>s.id);
  const chainKeyOk = ()=> !(typeof nbHasKeyForCurrent==="function") || nbHasKeyForCurrent();
  // A shot counts as DONE (skipped on a non-forced run) only if it's locked AND actually has a
  // committed frame. A locked-but-FRAMELESS shot \u2014 e.g. one whose generation errored or timed
  // out before being approved \u2014 must still render, never be silently skipped as "done".
  const shotHasFrame = (id)=> (typeof nbGetImage==="function") ? !!nbGetImage(id) : false;
  const shotIsDone = (s)=> !!(s && s.locked && shotHasFrame(s.id));
  // Advance to the next shot. Normal scene/all runs retain shots that are already done
  // (locked + framed); manual card runs use force=true so the clicked frame can be regenerated.
  const stepChain = (ids, fromIdx, force)=>{
    let i = fromIdx;
    while(i<ids.length){ const s=shotById[ids[i]]; if(s && (force || !shotIsDone(s))) break; i++; }
    if(i>=ids.length){ setChain(null); batch.setMsg("Chain complete \u2014 every shot rendered in order."); return; }
    setChain({ ids, idx:i, total:ids.length, force:!!force });
    batch.run([ids[i]]); batch.setMsg("Rendering shot "+(i+1)+" of "+ids.length+" in order\u2026");
  };
  // a chain step finished. Did it actually produce a frame? A FAILED / timed-out / cancelled
  // render commits nothing (nbGetImage stays empty).
  const handleBatchDone = (id)=>{
    batch.advance(id);
    const c = chainRef.current;
    if(!c || c.ids[c.idx]!==id) return;           // a lone (non-chain) generation \u2014 just advance
    const hasFrame = (typeof nbGetImage==="function") ? !!nbGetImage(id) : true;
    if(!hasFrame){
      // STOP the chain here \u2014 do NOT advance. Every later shot is seeded by THIS frame as its
      // continuity anchor, so we can't render the next one without it. The shot is left UNLOCKED
      // so a re-run retries it; the frame's own card shows why it failed.
      setChain(null);
      const more = (c.idx+1) < c.ids.length;
      batch.setMsg("Stopped at shot "+(c.idx+1)+" \u2014 it didn't generate"
        + (more ? ", and the next shot needs it as its anchor. Fix the issue on that frame, then render again." : ". See the frame's error and try again."));
      return;
    }
    onUpdateShot(id, { locked:true });            // it's the approved seed for the next shot
    stepChain(c.ids, c.idx+1, c.force);
  };
  // Stop: abort the frame currently rendering (clears its spinner + discards its result),
  // then halt the queue so no further shots start.
  const stopChain = ()=>{
    if(batchActiveId && typeof nbCancelGen==="function") nbCancelGen(batchActiveId);
    setChain(null); batch.cancel();
  };

  const startScene = (scene)=>{ if(batchActiveId||chain) return; if(!chainKeyOk()){ batch.setMsg("Set your image-model API key first (top of this tab)."); return; }
    const ids = chainOrderIds(shotsByScene[scene.id]); if(!ids.length) return;
    setCollapsed(c=>({ ...c, [scene.id]:false }));   // keep the scene's cards mounted through the run
    stepChain(ids, 0, false); };
  const startAll = ()=>{ if(batchActiveId||chain) return; if(!chainKeyOk()){ batch.setMsg("Set your image-model API key first (top of this tab)."); return; }
    const ids = scenesWithShots.flatMap(s=>chainOrderIds(shotsByScene[s.id]));
    if(!ids.length){ batch.setMsg("Draft the shots first \u2014 nothing to generate yet."); return; }
    setCollapsed({});   // expand all so each card is mounted as the chain reaches it
    stepChain(ids, 0, false); };
  // re-run a scene's chain from the shot AFTER `sh` \u2014 used after re-rolling a frame so the
  // propagated state stays current. Unlocks the downstream shots so they actually re-render.
  const onRegenDownstream = (sh)=>{ if(batchActiveId||chain || !sh) return; if(!chainKeyOk()){ batch.setMsg("Set your image-model API key first (top of this tab)."); return; }
    const ids = chainOrderIds(shotsByScene[sh.sceneId]); const at = ids.indexOf(sh.id);
    if(at<0 || at>=ids.length-1){ batch.setMsg("No later shots in this scene to regenerate."); return; }
    ids.slice(at+1).forEach(id=> onUpdateShot(id,{ locked:false }));
    setCollapsed(c=>({ ...c, [sh.sceneId]:false }));
    stepChain(ids, at+1, true); };
  // Manual card generation. A shot seeds off the PREVIOUS shot's frame (its anchor), so
  // every earlier shot in this sub-chain must already be rendered. If one is missing we
  // DON'T silently render it \u2014 we ask the user to generate the earlier shot first, so
  // they stay in control of the chain order. Only the clicked shot renders here.
  const startShot = async (id)=>{
    if(batchActiveId || chain || chainStartingRef.current || !id) return;
    if(!chainKeyOk()){ batch.setMsg("Set your image-model API key first (top of this tab)."); return; }
    chainStartingRef.current=true;
    try{
      const target=shotById[id]; if(!target) return;
      const orderedShots=(typeof sceneShotsOrdered==="function")?sceneShotsOrdered(shotsByScene[target.sceneId]):shotsByScene[target.sceneId];
      const at=orderedShots.findIndex(s=>s.id===id); if(at<0) return;
      // A deliberately marked Fresh shot is a hard-cut head. It starts a new
      // sub-chain; otherwise find the nearest earlier Fresh boundary.
      let startAt=0;
      for(let i=at;i>0;i--){ if(orderedShots[i].anchor){ startAt=i; break; } }
      // which earlier shots in this sub-chain aren't rendered yet?
      const missing=[];
      for(let i=startAt;i<at;i++){
        const s=orderedShots[i];
        let u=(typeof nbGetImage==="function")?nbGetImage(s.id):"";
        if(!u && typeof nbLoadImage==="function"){ try{ u=await nbLoadImage(s.id); }catch(e){} }
        if(!u) missing.push(s);
      }
      if(missing.length){
        const shotNo = (s)=> Math.max(1, orderedShots.findIndex(x=>x.id===s.id)+1);
        const shotLab = (s)=> "Shot "+shotNo(s)+(s.beatN ? " (Beat "+s.beatN+")" : "");
        const near=missing[missing.length-1];   // the immediate anchor this shot builds on
        setNotice(missing.length===1
          ? shotLab(target)+" depends on "+shotLab(near)+". Generate "+shotLab(near)+" first so it can become the continuity anchor."
          : shotLab(target)+" depends on the previous frame, but earlier anchors are missing. Generate the chain in order starting with "+shotLab(missing[0])+".");
        return;
      }
      setCollapsed(c=>({ ...c, [target.sceneId]:false }));
      stepChain([id],0,true);
    } finally {
      chainStartingRef.current=false;
    }
  };

  // ---- empty state ----
  if(!scenesWithShots.length){
    return _el("div",{className:"art-scroll"},
      _el(NbKeyBar,null), _el(NbControls,null),
      _el("div",{className:"art-intro"},
        _el("div",{className:"art-intro-row"},
          _el("div",{style:{flex:1}},
            _el("div",{className:"art-intro-t",style:{display:"flex",alignItems:"center",gap:9}},"Shot List",
              _el(window.InfoTip,{label:"About the Shots tab",
                text:"Every beat becomes a shot. \u201cDesign all shots\u201d breaks each scene into coverage \u2014 size, angle, movement and lens \u2014 then composes each frame from the scene's grade, the location plate and the character & prop sheets. Generate the frames here; the Storyboards tab lays them out next."}))),
          _el("div",{className:"art-intro-actions"},
            _el("button",{className:"art-draftall",disabled:draftingAllShots||!ordered.length,onClick:handleDesignAll,
              title:"Break every scene into a shot list from its beats"},
              _el(Icon.sparkles,{s:14}), draftingAllShots?"Designing\u2026":"Design all shots")))),
      _el("div",{className:"prop-empty"},
        _el("div",{className:"art-soon-ic"},_el(Icon.film,{s:30})),
        _el("div",{className:"art-soon-t"},"No shots yet"),
        _el("div",{className:"art-soon-d"},"Break your scenes into shots \u2014 one shot per beat, with full coverage \u2014 then generate a frame for each."),
        _el("button",{className:"art-draftall",style:{marginTop:16},disabled:draftingAllShots||!ordered.length,onClick:handleDesignAll},
          _el(Icon.sparkles,{s:14}), draftingAllShots?"Designing\u2026":"Design all shots")));
  }

  return _el("div",{className:"art-scroll"},
    view && _el(ImageLightbox,{url:view.url,character:view.character,onClose:()=>setView(null)}),
    notice && _el("div",{className:"shot-notice-scrim",onMouseDown:()=>setNotice("")},
      _el("div",{className:"shot-notice",role:"status",onMouseDown:e=>e.stopPropagation()},
        _el(Icon.info,{s:17,className:"shot-notice-ic"}),
        _el("div",{className:"shot-notice-msg"},notice),
        _el("button",{type:"button",className:"shot-notice-x","aria-label":"Close message",
          title:"Close",onClick:()=>setNotice("")},"\u00d7"))),
    _el(NbKeyBar,null), _el(NbControls,null),
    _el("div",{className:"art-intro"},
      _el("div",{className:"art-intro-row"},
        _el("div",{style:{flex:1}},
          _el("div",{className:"art-intro-t",style:{display:"flex",alignItems:"center",gap:9}},"Cinematographer (Shot Designer)",
            _el(window.InfoTip,{label:"About the Shot List",
              text:"A BEAT owns 1\u2013N shots (coverage): every scene starts at one shot per beat, and any beat can be SPLIT INTO COVERAGE from its lane header \u2014 one shot per distinct visual event, labelled 3A/3B/3C in cut order. Shots are grouped by beat lane inside each scene. Every frame generation follows a rolling chain in scene order: the first shot renders from the locked sheets, and every later shot is seeded by the immediately previous generated frame. Generate the shots in order — if you click Generate on a later shot before an earlier one is rendered, TURN asks you to generate the earlier shot first (it's the anchor this frame builds on). 'Generate all shots' and 'Render Scene X in order' render the whole chain straight through, auto-approving each frame as the next shot's seed. Stage video clips are packed automatically from these shots \u2014 there is no manual clip grouping here; clips live on the Stage."}))),
        _el("div",{className:"art-intro-actions"},
          // "Export shot list" lives in the top bar's ⋮ menu now (window.turnExportShotList)
          _el("button",{className:"art-draftall ghost",disabled:draftingAllShots||!ordered.length,onClick:handleDesignAll,
            title:"Break any scene that has no shots yet into full coverage \u2014 size, angle, move and lens per beat"},
            _el(Icon.sparkles,{s:14}), draftingAllShots?"Designing\u2026":"Design all shots"),
          _el("button",{className:"art-draftall",disabled:!!batchActiveId||!!chain||!shots.length,onClick:startAll,
            title:"Render every shot in chain order, each seeded by the previous frame. Locked (approved) frames are kept and used as seeds; the rest render."},
            _el(Icon.sparkles,{s:14}), (batchActiveId||chain)?"Rendering\u2026":"Generate all shots", typeof window.nbCostChip==="function" && window.nbCostChip(1))))),
    // A chain already has its own progress + Stop bar below. Hiding the generic
    // batch bar here avoids duplicate Cancel/Stop controls for the same request.
    !chain && BatchBar && _el(BatchBar,{batch,noun:"shot"}),
    // "Design all shots" progress — determinate, driven by how many scenes still lack shots
    (draftingAllShots && designTotal>0) && (()=>{
      const remaining = scenesNeedingShots().length;
      const done = Math.max(0, designTotal - remaining);
      const pct = Math.round((done/designTotal)*100);
      return _el("div",{className:"shot-design-bar"},
        _el("div",{className:"shot-design-row"},
          _el("span",{className:"ns-spin"}),
          _el("span",{className:"shot-design-lab"},"Designing shots — scene "+Math.min(done+1,designTotal)+" of "+designTotal+"…")),
        _el("div",{className:"shot-design-track"}, _el("div",{className:"shot-design-fill",style:{width:pct+"%"}})));
    })(),
    // (standalone ScenePager removed — the navigator is merged into each scene card head)
    visibleScenes.map(scene=>_el(SceneShotGroup,{key:scene.id,scene,shots:shotsForGroup(scene.id),
      pager:{ idx:visibleIdx, total:scenesWithShots.length, scenes:scenesWithShots, onJump:setPIdx,
        onPrev:()=>setPIdx(i=>Math.max(0,i-1)), onNext:()=>setPIdx(i=>Math.min(scenesWithShots.length-1,i+1)) },
      ctx:ctxFor(scene),characters:characters||[],beatsMap,propsAvail:(typeof propsForScene==="function")?propsForScene(props,scene.id):[],
      onUpdate:onUpdateShot,onDelete:onDeleteShot,onView:(url,e)=>setView({url,character:e}),
      onAddShot,onSplitBeat,splittingBeat,onDraftScene:onDraftSceneShots,draftingScene:draftingSceneShots===scene.id,
      batchActiveId,onBatchDone:handleBatchDone,onGenerateShot:startShot,onRegenDownstream,
      onRenderScene:startScene,renderBusy,onStopChain:stopChain,
      open:true,onToggle:()=>toggleScene(scene.id)})),
    // Keep only the active runner mounted when the user browses away. display:none
    // preserves its generation/completion effects without showing a second scene.
    runnerScene && _el("div",{style:{display:"none"},"aria-hidden":"true"},
      _el(SceneShotGroup,{key:"runner-"+runnerScene.id,scene:runnerScene,shots:shotsForGroup(runnerScene.id),
        ctx:ctxFor(runnerScene),characters:characters||[],beatsMap,
        propsAvail:(typeof propsForScene==="function")?propsForScene(props,runnerScene.id):[],
        onUpdate:onUpdateShot,onDelete:onDeleteShot,onView:(url,e)=>setView({url,character:e}),
        onAddShot,onSplitBeat,splittingBeat,onDraftScene:onDraftSceneShots,draftingScene:draftingSceneShots===runnerScene.id,
        batchActiveId,onBatchDone:handleBatchDone,onGenerateShot:startShot,onRegenDownstream,
        onRenderScene:startScene,renderBusy,onStopChain:stopChain,open:true,onToggle:()=>{}})));
}
window.ShotList = ShotList;

/* ---- export: a printable shot-list table (open in a new tab → Save as PDF) ---- */
function exportShotList(scenesWithShots, shotsByScene, ctxFor, project, beatsMap){
  const esc = (s)=> String(s==null?"":s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
  const title = (project && project.title) || "Shot List";
  let rows = "";
  scenesWithShots.forEach(scene=>{
    const ctx = ctxFor(scene);
    const loc = ctx.location ? ctx.location.name : "";
    const beatRows = ((beatsMap||{})[scene.id]||{}).rows || [];
    rows += '<tr class="scenehdr"><td colspan="7"><b>SC '+esc(String(scene.no).padStart(2,"0"))+'</b> &nbsp; '
      + esc(scene.title||"")+(loc?(' &nbsp;&middot;&nbsp; '+esc(loc)):"")+'</td></tr>';
    (shotsByScene[scene.id]||[]).forEach((sh,i)=>{
      const subs = (sh.subjects||[]).map(id=>ctx.charById[id]).filter(Boolean).map(c=>c.name).join(", ");
      // the SCRIPT BEAT this shot covers (drive — reaction) rides under the action,
      // so the printed list carries the source text the coverage answers to
      const br = beatRows.find(r=>String(r.n)===String(sh.beatN));
      const beatText = br ? [ (br.drive&&br.drive.d||"").trim(), (br.react&&br.react.d||"").trim() ].filter(Boolean).join(" — ") : "";
      rows += '<tr>'
        + '<td class="num">'+esc(scene.no)+'.'+esc(i+1)+(sh.beatN?('<span class="bn">b'+esc(sh.beatN)+'</span>'):'')+'</td>'
        + '<td>'+esc(shotSizeOf(sh.size).label)+'</td>'
        + '<td>'+esc(shotAngleOf(sh.angle).label)+'</td>'
        + '<td>'+esc(shotMoveOf(sh.move).label)+' &middot; '+esc(shotLensOf(sh.lens).label)+'</td>'
        + '<td>'+esc(subs)+'</td>'
        + '<td class="act">'+esc(sh.action||"")+(sh.dialogue?(' <span class="dlg">&ldquo;'+esc(sh.dialogue)+'&rdquo;</span>'):"")
        + (beatText?('<div class="beat"><span class="beatlab">Beat '+esc(sh.beatN||"")+'</span> '+esc(beatText)+'</div>'):"")+'</td>'
        + '<td class="comp">'+esc(sh.composition||"")+'</td>'
        + '</tr>';
    });
  });
  const html = '<!doctype html><html><head><meta charset="utf-8"><title>'+esc(title)+' \u2014 Shot List</title>'
    + '<style>'
    + 'body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#16181d;margin:40px;}'
    + 'h1{font-size:20px;margin:0 0 4px;} .sub{color:#666;font-size:12px;margin-bottom:20px;}'
    + 'table{border-collapse:collapse;width:100%;font-size:11.5px;}'
    + 'th,td{border:1px solid #d7dae0;padding:6px 8px;vertical-align:top;text-align:left;}'
    + 'th{background:#f3f4f6;font-size:10px;letter-spacing:.06em;text-transform:uppercase;color:#555;}'
    + 'tr.scenehdr td{background:#1b1e26;color:#fff;font-size:12px;padding:7px 8px;}'
    + 'td.num{font-variant-numeric:tabular-nums;white-space:nowrap;color:#666;} td.act{width:30%;} td.comp{width:24%;color:#444;}'
    + '.dlg{color:#7a5; font-style:italic;}'
    + '.beat{margin-top:5px;padding:4px 7px;background:#f6f6f3;border-left:2px solid #c9ccd3;color:#555;font-style:italic;font-size:10.5px;line-height:1.4;}'
    + '.beatlab{font-style:normal;font-size:8.5px;letter-spacing:.07em;text-transform:uppercase;color:#999;margin-right:4px;}'
    + '.bn{margin-left:5px;font-size:8.5px;color:#aaa;}'
    + '@media print{body{margin:14mm;}}'
    + '</style></head><body>'
    + '<h1>'+esc(title)+' &mdash; Shot List</h1>'
    + '<div class="sub">'+(project&&project.format?esc(project.format)+' &middot; ':'')+'Generated by Cinema Machine</div>'
    + '<table><thead><tr><th>Shot</th><th>Size</th><th>Angle</th><th>Move / Lens</th><th>In frame</th><th>Action</th><th>Composition</th></tr></thead>'
    + '<tbody>'+rows+'</tbody></table>'
    + '</body></html>';
  // in-app PREVIEW first (same overlay as the screenplay export) — print/download from there
  if(typeof window.docPreview==="function"){
    window.docPreview({ title:"Shot list preview", sub:title,
      fileName:(title||"shot_list").replace(/[^\w\-]+/g,"_").toUpperCase()+"_SHOT_LIST.html", html,
      hint:"Review the table, then print / save as PDF — or download the HTML." });
    return;
  }
  // fallback (overlay unavailable): the old auto-printing tab
  const w = window.open("", "_blank");
  if(w){ w.document.open();
    w.document.write(html.replace('</body>','<script>setTimeout(function(){try{window.print();}catch(e){}},350);<\/script></body>'));
    w.document.close(); }
}
window.exportShotList = exportShotList;
