/* ============================================================
   story-data.jsx — sample story mapped to McKee structure
   "THE MATRIX" (1999) — structural breakdown / analysis
   (original paraphrased summaries, not screenplay text)
   ============================================================ */

const PROJECT = {
  title: "THE MATRIX",
  format: "Feature Film",
  runtime: "2h 16m",
  genre: "Science Fiction / Action",
  premise:
    "What would happen if the world you knew were a simulation built to enslave you, and one ordinary man were told he might be the one who can break it?",
  controllingIdea: {
    value: "We seize our freedom",
    cause: "when we let go of the comfortable lie and believe in who we truly are.",
    polarity: "idealistic",
  },
  setting: {
    period: "1999 \u2014 and 'the desert of the real,' c. 2199",
    duration: "A few days, subjective time",
    location: "A simulated city & the hovercraft Nebuchadnezzar",
    conflict: "Inner (doubt vs. belief) \u00b7 Personal (the crew) \u00b7 Extra-personal (the Machines)",
  },
};

const CHARACTERS = [
  {
    id: "neo", name: "NEO", role: "Protagonist",
    color: "linear-gradient(135deg,#3f8f5c,#163a24)",
    conscious: "Find out what the Matrix is \u2014 and free Morpheus.",
    unconscious: "To believe he is more than an ordinary man: The One.",
    arc: "Doubt \u2192 belief \u2192 self-realization",
  },
  {
    id: "morpheus", name: "MORPHEUS", role: "Mentor \u00b7 ally",
    color: "linear-gradient(135deg,#5a6470,#23282f)",
    conscious: "Find The One and end the war against the Machines.",
    unconscious: "To have his lifelong faith proven true.",
    arc: "Belief tested \u2192 vindicated",
  },
  {
    id: "trinity", name: "TRINITY", role: "Ally \u00b7 love",
    color: "linear-gradient(135deg,#6a6cae,#26243f)",
    conscious: "Protect Neo and the mission.",
    unconscious: "The Oracle told her she'd love The One.",
    arc: "Guarded \u2192 open",
  },
  {
    id: "smith", name: "AGENT SMITH", role: "Antagonist \u00b7 the Machines",
    color: "linear-gradient(135deg,#4a5560,#1c2128)",
    conscious: "Crush the resistance and erase Neo.",
    unconscious: "To escape the Matrix he despises.",
    arc: "Control \u2192 obsession \u2192 deletion",
  },
  {
    id: "cypher", name: "CYPHER", role: "Antagonist \u00b7 betrayer",
    color: "linear-gradient(135deg,#8a5a45,#3a2418)",
    conscious: "Return to the Matrix and forget the truth.",
    unconscious: "To be someone important \u2014 to matter.",
    arc: "Resentment \u2192 betrayal \u2192 fall",
  },
];

/* PROPS — continuity objects (worn or carried) tied to a character. Each gets its
   own reference sheet so the object looks identical in every shot it appears in.
   Seeded from the script; users add/edit/delete and generate sheets per prop. */
const PROPS = [
  { id:"redbluepill", name:"The Red & Blue Pills", kind:"carried", ownerId:"morpheus", ownerName:"MORPHEUS",
    form:"Two small gelatin capsules held in an open palm — one vivid red, one cool blue.",
    material:"Glossy translucent gelatin, faint internal glow, slightly soft to the touch.",
    detail:"The choice itself: red = the truth of the real world, blue = the comfort of the illusion.",
    renderStyle:"photoreal macro product shot, 100mm, shallow depth of field, dramatic single-source light",
    negativePrompt:"text, watermark, label, branding, blurry, low resolution, plastic toy look" },
  { id:"nokia8110", name:"Nokia 8110 \u2014 the lifeline phone", kind:"carried", ownerId:"neo", ownerName:"NEO",
    form:"A curved, slide-action mobile phone with a monochrome green screen.",
    material:"Charcoal moulded plastic, slightly worn matte finish, spring-loaded sliding cover.",
    detail:"The link between the Matrix and the real \u2014 how the crew calls in and out.",
    renderStyle:"photoreal product reference, 50mm, soft studio light, crisp edge detail",
    negativePrompt:"text, watermark, modern smartphone, touchscreen, blurry, low resolution" },
  { id:"morpheus-shades", name:"Morpheus's mirrored pince-nez", kind:"worn", ownerId:"morpheus", ownerName:"MORPHEUS",
    form:"Rimless oval mirror-lensed glasses that clip to the bridge of the nose, no arms.",
    material:"Gold-tinted mirror glass, fine metal nose-clip, flawless reflective surface.",
    detail:"His composure and authority; the reflective lenses hide his eyes, never his certainty.",
    renderStyle:"photoreal product reference, 85mm, controlled reflections, neutral grey sweep",
    negativePrompt:"text, watermark, temple arms, plastic frame, blurry, distorted reflection" },
];
window.PROPS_SEED = PROPS;

/* charge: integer -3..+3.  conf = conflict level 1..3 (inner/personal/extra) */
const SCENES = [
  // ---------- ACT ONE ----------
  { id:"s1", act:1, seq:"The Hunt", no:1, title:"Trinity's Escape",
    loc:"INT. HEART O' THE CITY HOTEL \u00b7 NIGHT",
    summary:"A cold open. Trinity outruns a squad of police and a near-unstoppable Agent across the rooftops, vanishing through a ringing phone. The sequence quietly establishes the lethal world and a search already underway \u2014 for someone.",
    openValue:"Power", openCharge:0, closeValue:"Threat", closeCharge:-1,
    conf:3, kind:"normal", plot:"Exposition", driver:"trinity",
    objective:"To escape the Agents and protect the search.",
    turningPoint:"The Agents announce the hunt is really for him \u2014 Neo." },

  { id:"s2", act:1, seq:"The Hunt", no:2, title:"Follow the White Rabbit",
    loc:"INT. ANDERSON'S APARTMENT / NIGHTCLUB \u00b7 NIGHT",
    summary:"By day a programmer, by night the hacker 'Neo,' Thomas Anderson is gnawed by the sense that something is wrong with the world. A cryptic message leads him to Trinity, who promises the question driving him \u2014 what is the Matrix? \u2014 has an answer.",
    openValue:"Purpose", openCharge:-1, closeValue:"Intrigue", closeCharge:1,
    conf:1, kind:"incite", driver:"neo",
    objective:"To find the source of the question that haunts him.",
    turningPoint:"INCITING INCIDENT \u2014 the question seizes him; his ordinary life is over." },

  { id:"s3", act:1, seq:"The Hunt", no:3, title:"The Interrogation",
    loc:"INT. METACORTEX / HOLDING ROOM \u00b7 DAY",
    summary:"Agents seize Neo at work. When he refuses to cooperate, the rules of reality break: his mouth seals over and a living 'bug' is forced into his body. He wakes in his bed certain it was a dream \u2014 until it isn't.",
    openValue:"Safety", openCharge:1, closeValue:"Violation", closeCharge:-2,
    conf:3, kind:"normal", plot:"Rising Action", driver:"smith",
    objective:"To make Neo cooperate \u2014 and to break his sense of the real.",
    turningPoint:"Reality itself proves unreliable; Neo's certainty shatters." },

  { id:"s4", act:1, seq:"The Choice", no:4, title:"Red Pill, Blue Pill",
    loc:"INT. THE ADAMS STREET BRIDGE / MORPHEUS'S ROOM \u00b7 NIGHT",
    summary:"Trinity's crew extracts the bug, then brings Neo to Morpheus, who offers him a choice: a blue pill and the comfortable story, or a red pill and the truth of how deep it goes. Neo chooses the truth.",
    openValue:"Truth", openCharge:-1, closeValue:"Truth", closeCharge:2,
    conf:1, kind:"act-climax", driver:"morpheus",
    objective:"To make Neo accept the truth and commit, of his own will.",
    turningPoint:"ACT I CLIMAX \u2014 the irreversible choice. He takes the red pill." },

  // ---------- ACT TWO ----------
  { id:"s5", act:2, seq:"Rebirth", no:5, title:"The Real World",
    loc:"INT. POWER PLANT / NEBUCHADNEZZAR \u00b7 CONTINUOUS",
    summary:"Neo wakes for the first time \u2014 hairless, wired into a pod in a vast machine farm of harvested humans. Flushed out and nearly drowned, he's hauled aboard the Nebuchadnezzar. The truth he chose is a horror.",
    openValue:"Reality", openCharge:2, closeValue:"Reality", closeCharge:-3,
    conf:1, kind:"normal", plot:"Reversal", driver:"neo",
    objective:"To survive being born into the real world.",
    turningPoint:"The promised truth lands as devastation \u2014 humanity is a crop." },

  { id:"s6", act:2, seq:"Rebirth", no:6, title:"The Desert of the Real",
    loc:"INT. THE CONSTRUCT \u00b7 LOADING PROGRAM",
    summary:"In the white void of the Construct, Morpheus walks Neo through the history: the rise of the machines, the scorched sky, the simulation that pacifies the enslaved. It is the film's great download of lore \u2014 pure exposition.",
    openValue:"Understanding", openCharge:-2, closeValue:"Understanding", closeCharge:-2,
    conf:1, kind:"normal", plot:"Exposition", driver:"morpheus",
    objective:"To explain the world so Neo can begin to function in it.",
    turningPoint:"" },

  { id:"s7", act:2, seq:"Becoming", no:7, title:"Training",
    loc:"INT. NEBUCHADNEZZAR \u00b7 TRAINING PROGRAMS",
    summary:"Combat and skills are uploaded straight to Neo's mind; he spars with Morpheus and learns the rules can be bent. He fails 'the Jump' the first time \u2014 belief still lags ability \u2014 but his power and confidence surge.",
    openValue:"Confidence", openCharge:-1, closeValue:"Confidence", closeCharge:2,
    conf:2, kind:"normal", plot:"Rising Action", driver:"neo",
    objective:"To master a world where the mind makes it real.",
    turningPoint:"Neo bends the rules \u2014 but 'everybody falls the first time.'" },

  { id:"s8", act:2, seq:"The Oracle", no:8, title:"The Oracle",
    loc:"INT. THE ORACLE'S APARTMENT \u00b7 DAY",
    summary:"Morpheus believes Neo is The One. The Oracle, warm and disarming, gently tells Neo he isn't \u2014 that he seems to be waiting for something, maybe his next life. She leaves him with a riddle that hollows out his self-belief.",
    openValue:"Identity", openCharge:2, closeValue:"Identity", closeCharge:-2,
    conf:1, kind:"midpoint", driver:"neo",
    objective:"To learn whether he is The One.",
    turningPoint:"MID-ACT CLIMAX \u2014 the prophecy is denied; Neo's deepest doubt." },

  { id:"s9", act:2, seq:"The Trap", no:9, title:"Cypher's Betrayal",
    loc:"INT. GOVERNMENT BUILDING / NEBUCHADNEZZAR \u00b7 NIGHT",
    summary:"Cypher, sick of the truth, has cut a deal with the Agents: re-insertion into the Matrix in exchange for Morpheus. The crew walks into an ambush. Inside the ship, Cypher begins pulling the plug on his sleeping shipmates.",
    openValue:"Trust", openCharge:-1, closeValue:"Trust", closeCharge:-3,
    conf:2, kind:"normal", plot:"Complication", driver:"cypher",
    objective:"To trade Morpheus for a comfortable lie.",
    turningPoint:"Betrayal from within \u2014 the crew is exposed and dying." },

  { id:"s10", act:2, seq:"The Trap", no:10, title:"Morpheus Sacrifices Himself",
    loc:"INT. WET-WALL HOTEL \u00b7 NIGHT",
    summary:"Cornered by Agents, Morpheus breaks free long enough to throw Neo and Trinity clear, then lets Smith take him so the others can live. His faith makes him spend himself for the man he believes is The One.",
    openValue:"Loyalty", openCharge:-3, closeValue:"Purpose", closeCharge:-1,
    conf:3, kind:"normal", plot:"Sacrifice", driver:"morpheus",
    objective:"To save Neo at any cost \u2014 even himself.",
    turningPoint:"Despair turns to a reason to act: Morpheus must be saved." },

  { id:"s11", act:2, seq:"The Trap", no:11, title:"They'll Break Him",
    loc:"INT. NEBUCHADNEZZAR \u00b7 CORE",
    summary:"With Cypher stopped, Tank delivers the math: the Agents will torture the access codes to Zion out of Morpheus's mind. The only way to protect the last human city may be to unplug \u2014 to kill \u2014 their captain.",
    openValue:"Stakes", openCharge:-1, closeValue:"Stakes", closeCharge:-3,
    conf:3, kind:"normal", plot:"Low Point", driver:"tank",
    objective:"To make the crew accept the math \u2014 one life against all of Zion.",
    turningPoint:"ALL IS LOST \u2014 saving Morpheus seems to mean dooming everyone." },

  { id:"s12", act:2, seq:"The Trap", no:12, title:"I'm Going In",
    loc:"INT. NEBUCHADNEZZAR \u00b7 CORE",
    summary:"Against every odd, Neo refuses to let Morpheus die. He still doesn't believe he's The One \u2014 but he chooses to act as if he could be. Trinity insists on going with him. They arm up.",
    openValue:"Resolve", openCharge:-3, closeValue:"Resolve", closeCharge:1,
    conf:1, kind:"act-climax", driver:"neo",
    objective:"To risk everything to save Morpheus.",
    turningPoint:"ACT II CLIMAX \u2014 despair becomes resolve; Neo commits to act." },

  // ---------- ACT THREE ----------
  { id:"s13", act:3, seq:"The Rescue", no:13, title:"The Lobby",
    loc:"INT. GOVERNMENT LOBBY \u00b7 DAY",
    summary:"Neo and Trinity breach the building in the film's iconic assault \u2014 guns, lots of guns \u2014 cutting through security to reach Morpheus on the roof. For the first time Neo's power is unleashed with intent.",
    openValue:"Power", openCharge:-1, closeValue:"Power", closeCharge:2,
    conf:3, kind:"normal", plot:"Rising Action", driver:"neo",
    objective:"To fight through to Morpheus and free him.",
    turningPoint:"Momentum swings \u2014 the rescue is on." },

  { id:"s14", act:3, seq:"The Rescue", no:14, title:"Dodge This",
    loc:"INT. ROOFTOP / SUBWAY STATION \u00b7 DAY",
    summary:"Neo dodges an Agent's bullets \u2014 something no one has done \u2014 and Morpheus is saved. But cornered alone in the subway, Neo chooses to stand and fight Smith, and the duel batters him to the edge of death.",
    openValue:"Courage", openCharge:2, closeValue:"Survival", closeCharge:-2,
    conf:3, kind:"normal", plot:"False Defeat", driver:"smith",
    objective:"To delete Neo before he can become what they fear.",
    turningPoint:"A false dawn \u2014 the hero's new power nearly gets him killed." },

  { id:"s15", act:3, seq:"The One", no:15, title:"Death & Resurrection",
    loc:"INT. APARTMENT 303 / NEBUCHADNEZZAR \u00b7 DAY",
    summary:"Smith guns Neo down inside the Matrix; on the ship, his body flatlines. Trinity tells his still form what the Oracle promised her \u2014 and that she loves him. Neo rises, finally sees the Matrix as raw code, and unmakes Smith from the inside.",
    openValue:"Belief", openCharge:-3, closeValue:"Liberation", closeCharge:3,
    conf:1, kind:"story-climax", driver:"neo",
    objective:"To stop running and become who he is.",
    turningPoint:"STORY CLIMAX \u2014 irreversible. Belief makes him The One." },

  { id:"s16", act:3, seq:"The One", no:16, title:"A World Without Rules",
    loc:"INT./EXT. THE MATRIX \u00b7 DAY",
    summary:"Neo makes a defiant call to the Machines: he'll show the enslaved a world without their control. He hangs up and flies straight up into the sky \u2014 free, and dangerous to the system that made him.",
    openValue:"Freedom", openCharge:3, closeValue:"Freedom", closeCharge:2,
    conf:1, kind:"resolution", driver:"neo",
    objective:"To carry the truth back to everyone still asleep.",
    turningPoint:"" },
];

/* Beat / subtext grids — the Casablanca-style action/reaction map for every scene.
   turnAt = the beat where the gap opens and the value flips (0 = scene does not turn). */
const BEATS = {
  s1: {
    driverLabel:"TRINITY", reactorLabel:"THE AGENTS",
    desire:"To break contact and reach the exit before the Agent does.",
    obstacle:"An Agent who moves faster than anything human.",
    turnAt:5,
    rows:[
      { n:1, drive:{a:"Holding the room",d:"Freezes a squad of police mid-raid."}, react:{a:"Sending the cleaner",d:"An Agent arrives, unbothered by the bodies."} },
      { n:2, drive:{a:"Breaking out",d:"Clears the rooftops in impossible leaps."}, react:{a:"Falling behind",d:"The police can't follow where she goes."} },
      { n:3, drive:{a:"Running the gap",d:"Sprints for a distant ringing phone."}, react:{a:"Commandeering a body",d:"The Agent takes a new form to cut her off."} },
      { n:4, drive:{a:"Making the jump",d:"Hurls herself across an alley through a window."}, react:{a:"Matching her",d:"The Agent keeps pace, inhuman."} },
      { n:5, drive:{a:"Vanishing",d:"Answers the phone and is gone."}, react:{a:"Conceding the round",d:"The Agents turn to the real target \u2014 him."} },
    ],
  },
  s2: {
    driverLabel:"NEO", reactorLabel:"THE SIGN / TRINITY",
    desire:"To name the wrongness he feels about the world.",
    obstacle:"A truth no one will say plainly \u2014 and his own caution.",
    turnAt:6,
    rows:[
      { n:1, drive:{a:"Searching",d:"Trawls the net for the name Morpheus."}, react:{a:"Answering him",d:"The screen addresses Neo directly."} },
      { n:2, drive:{a:"Hesitating",d:"A stranger invites him out into the night."}, react:{a:"Beckoning",d:"A white-rabbit tattoo says follow."} },
      { n:3, drive:{a:"Following the sign",d:"Goes to the club against his better judgment."}, react:{a:"Approaching",d:"Trinity finds him in the crowd."} },
      { n:4, drive:{a:"Playing it cool",d:"Pretends the legend doesn't move him."}, react:{a:"Seeing through him",d:"She already knows his question."} },
      { n:5, drive:{a:"Admitting the itch",d:"The question that won't let him sleep."}, react:{a:"Naming the stakes",d:"It's the question that drives him."} },
      { n:6, drive:{a:"Letting hope in",d:"Lets himself believe there's an answer."}, react:{a:"Promising the door",d:"The answer is out there, and it's looking for him."} },
    ],
  },
  s3: {
    driverLabel:"AGENT SMITH", reactorLabel:"NEO",
    desire:"To make Neo inform on Morpheus.",
    obstacle:"Neo's belief that this is just an ordinary bad day at work.",
    turnAt:5,
    rows:[
      { n:1, drive:{a:"Disarming",d:"Polite, almost paternal, across the table."}, react:{a:"Bristling",d:"Demands his phone call."} },
      { n:2, drive:{a:"Flattering",d:"Admires the cleverness of his double life."}, react:{a:"Stonewalling",d:"Gives them nothing."} },
      { n:3, drive:{a:"Tightening",d:"Offers to wipe the slate for Morpheus."}, react:{a:"Refusing",d:"Tells the Agent exactly where to go."} },
      { n:4, drive:{a:"Dropping the mask",d:"Neo's lips seal over his mouth."}, react:{a:"Panicking",d:"Claws at a face that won't open."} },
      { n:5, drive:{a:"Violating him",d:"A living bug burrows into his body."}, react:{a:"Waking changed",d:"He jolts up in bed \u2014 'a dream' he can't trust."} },
    ],
  },
  s4: {
    driverLabel:"MORPHEUS", reactorLabel:"NEO",
    desire:"To make Neo accept the truth \u2014 and choose it freely.",
    obstacle:"Neo's fear, doubt, and his pull toward the comfortable world he knows.",
    turnAt:7,
    rows:[
      { n:1, drive:{a:"Disarming",d:"Greets Neo as someone who already feels the world is wrong."}, react:{a:"Guarding",d:"Admits the splinter in his mind he can't name."} },
      { n:2, drive:{a:"Naming it",d:"Tells him the feeling has a name: the Matrix."}, react:{a:"Leaning in",d:"Wants to know what that means \u2014 the hook is set."} },
      { n:3, drive:{a:"Warning",d:"Calls it a prison for the mind, built to blind him."}, react:{a:"Recoiling",d:"The scale of it is too much; he hesitates."} },
      { n:4, drive:{a:"Offering the choice",d:"Presents the two pills \u2014 the story, or the truth."}, react:{a:"Weighing",d:"Comfort versus the unknown; he stalls at the threshold."} },
      { n:5, drive:{a:"Stating the cost",d:"Makes clear there is no going back after this."}, react:{a:"Steeling",d:"Fights down the fear and steadies his hand."} },
      { n:6, drive:{a:"Extending the truth",d:"Promises nothing more, and nothing less, than the truth."}, react:{a:"Reaching",d:"His desire to know finally outweighs his fear."} },
      { n:7, drive:{a:"Affirming",d:"Welcomes him forward \u2014 'follow me.'"}, react:{a:"Choosing",d:"Takes the red pill. Comfortable ignorance becomes committed truth."} },
    ],
  },
  s5: {
    driverLabel:"NEO", reactorLabel:"THE MACHINE WORLD",
    desire:"To survive being born out of the simulation.",
    obstacle:"A body never used, and a truth too vast to hold.",
    turnAt:5,
    rows:[
      { n:1, drive:{a:"Crossing over",d:"The red pill takes hold; reality liquefies."}, react:{a:"Letting go",d:"The mirror swallows him."} },
      { n:2, drive:{a:"Waking",d:"Opens real eyes for the first time."}, react:{a:"Revealing him",d:"He's wired into a tower of harvested bodies."} },
      { n:3, drive:{a:"Tearing free",d:"Rips the cables and fights the cradle."}, react:{a:"Discarding him",d:"The machine flushes the defective unit."} },
      { n:4, drive:{a:"Drowning",d:"Sucked down the drain, lungs failing."}, react:{a:"Snatching him",d:"A hovercraft's hook hauls him up."} },
      { n:5, drive:{a:"Seeing it whole",d:"The human farm, the dead sky."}, react:{a:"Crushing him",d:"'Welcome to the real world.'"} },
    ],
  },
  s6: {
    driverLabel:"MORPHEUS", reactorLabel:"NEO",
    desire:"To download the whole history of the world into Neo at once.",
    obstacle:"None in the room \u2014 it is a lecture; nothing is at stake here.",
    turnAt:0,
    flat:true,
    rows:[
      { n:1, drive:{a:"Setting the stage",d:"The blank white Construct loads."}, react:{a:"Listening",d:"Takes it in."} },
      { n:2, drive:{a:"Explaining the war",d:"How man and machine came to blows."}, react:{a:"Absorbing",d:"Numb."} },
      { n:3, drive:{a:"Showing the ruin",d:"A sky scorched to block the sun."}, react:{a:"Recoiling",d:"Quietly."} },
      { n:4, drive:{a:"Naming the prison",d:"The Matrix as a pacifier for a crop."}, react:{a:"Understanding",d:"Intellectually, not yet in the gut."} },
      { n:5, drive:{a:"Apologizing",d:"'Welcome to the desert of the real.'"}, react:{a:"Overwhelmed",d:"Informed \u2014 but wanting nothing new."} },
    ],
  },
  s7: {
    driverLabel:"NEO", reactorLabel:"MORPHEUS",
    desire:"To make the rules of the Matrix bend to his will.",
    obstacle:"A mind that still believes the old limits are real.",
    turnAt:4,
    rows:[
      { n:1, drive:{a:"Loading skills",d:"Combat uploaded straight to the brain."}, react:{a:"Raising the bar",d:"Challenges him to spar."} },
      { n:2, drive:{a:"Showing off",d:"Faster, stronger, eager."}, react:{a:"Schooling him",d:"Speed and strength aren't the point."} },
      { n:3, drive:{a:"Trying harder",d:"Throws everything he has."}, react:{a:"Exposing the lag",d:"'You're not using all you can.'"} },
      { n:4, drive:{a:"Catching on",d:"Lands a real strike, free of doubt."}, react:{a:"Approving",d:"'Better.' The competence turns."} },
      { n:5, drive:{a:"Attempting the Jump",d:"The leap between rooftops."}, react:{a:"Believing for him",d:"'Free your mind.'"} },
      { n:6, drive:{a:"Falling",d:"Doesn't make it \u2014 yet."}, react:{a:"Reassuring",d:"'Everybody falls the first time.'"} },
    ],
  },
  s8: {
    driverLabel:"NEO", reactorLabel:"THE ORACLE",
    desire:"To be told he is The One.",
    obstacle:"An oracle who tells the truth sideways.",
    turnAt:4,
    rows:[
      { n:1, drive:{a:"Arriving hopeful",d:"Expects his confirmation."}, react:{a:"Disarming him",d:"Baking cookies, warm and ordinary."} },
      { n:2, drive:{a:"Bracing",d:"Ready to be measured."}, react:{a:"Deflecting",d:"'Don't worry about the vase.'"} },
      { n:3, drive:{a:"Breaking the vase",d:"Knocks it over, exactly as foretold."}, react:{a:"Making her point",d:"What'll really bake your noodle is whether you would have without her."} },
      { n:4, drive:{a:"Asking straight",d:"'Am I The One?'"}, react:{a:"Letting him down easy",d:"'Sorry, kid. You've got the gift, but you're waiting for something.'"} },
      { n:5, drive:{a:"Deflating",d:"The prophecy, denied."}, react:{a:"Reframing it",d:"Morpheus believes \u2014 enough to die for it."} },
      { n:6, drive:{a:"Leaving hollowed",d:"Doubt where belief used to be."}, react:{a:"Planting the seed",d:"'You'll have to make a choice.'"} },
    ],
  },
  s9: {
    driverLabel:"CYPHER", reactorLabel:"THE CREW / TRINITY",
    desire:"To trade Morpheus for a return to blissful ignorance.",
    obstacle:"Shipmates who still trust him.",
    turnAt:5,
    rows:[
      { n:1, drive:{a:"Dining the enemy",d:"Cuts a deal with Smith over a steak he knows isn't real."}, react:{a:"Setting terms",d:"Deliver Morpheus."} },
      { n:2, drive:{a:"Leading them in",d:"Guides the op into the building."}, react:{a:"Trusting him",d:"The crew follows the plan."} },
      { n:3, drive:{a:"Springing the trap",d:"A wall opens onto Agents."}, react:{a:"Closing the net",d:"The team is pinned under fire."} },
      { n:4, drive:{a:"Slipping away",d:"Jacks out, back to the ship, alone."}, react:{a:"Caught in it",d:"The crew scrambles to survive."} },
      { n:5, drive:{a:"Pulling the plug",d:"Kills shipmates in their chairs, one by one."}, react:{a:"Realizing the betrayal",d:"Trinity sees who it is."} },
    ],
  },
  s10: {
    driverLabel:"MORPHEUS", reactorLabel:"AGENT SMITH",
    desire:"To spend his own life to save the man he believes is The One.",
    obstacle:"Agents who want him alive and breakable.",
    turnAt:5,
    rows:[
      { n:1, drive:{a:"Shielding Neo",d:"Orders him to run."}, react:{a:"Pressing in",d:"Agents flood the room."} },
      { n:2, drive:{a:"Buying time",d:"Charges Smith head-on through a wall."}, react:{a:"Overpowering him",d:"Stronger, faster, certain."} },
      { n:3, drive:{a:"Holding the line",d:"Takes the beating to keep them busy."}, react:{a:"Letting them slip",d:"Neo and Trinity drop to safety."} },
      { n:4, drive:{a:"Going down",d:"Subdued at last."}, react:{a:"Taking the prize",d:"'We have him.'"} },
      { n:5, drive:{a:"Surrendering himself",d:"Lets them carry him off."}, react:{a:"Vowing",d:"Neo swears this won't be the end."} },
    ],
  },
  s11: {
    driverLabel:"TANK", reactorLabel:"NEO / THE CREW",
    desire:"To make the crew accept the unthinkable arithmetic.",
    obstacle:"Their love for their captain.",
    turnAt:5,
    rows:[
      { n:1, drive:{a:"Laying out the threat",d:"They'll read the codes out of his mind."}, react:{a:"Refusing it",d:"There has to be another way."} },
      { n:2, drive:{a:"Naming the cost",d:"The access to every soul in Zion."}, react:{a:"Going silent",d:"The stakes land hard."} },
      { n:3, drive:{a:"Stating the math",d:"One life against every life."}, react:{a:"Looking away",d:"Trinity can't meet it."} },
      { n:4, drive:{a:"Reaching for the plug",d:"The only 'rescue' left."}, react:{a:"Stopping him",d:"'Wait.'"} },
      { n:5, drive:{a:"Forcing the choice",d:"It has to be now."}, react:{a:"Staring into it",d:"The impossible call settles on Neo."} },
    ],
  },
  s12: {
    driverLabel:"NEO", reactorLabel:"TRINITY / THE CREW",
    desire:"To save Morpheus even without believing he's The One.",
    obstacle:"The odds, and his own unproven faith.",
    turnAt:5,
    rows:[
      { n:1, drive:{a:"Deciding",d:"'I'm going back in.'"}, react:{a:"Doubting",d:"It's suicide."} },
      { n:2, drive:{a:"Owning the risk",d:"'The Oracle said I'm not The One.'"}, react:{a:"Warning",d:"Agents will kill him."} },
      { n:3, drive:{a:"Choosing anyway",d:"Morpheus believed in him; that's enough."}, react:{a:"Stepping up",d:"'Then I'm going too.'"} },
      { n:4, drive:{a:"Accepting the help",d:"They do it together."}, react:{a:"Committing",d:"No argument from Trinity."} },
      { n:5, drive:{a:"Gearing up",d:"'Guns. Lots of guns.'"}, react:{a:"Falling in",d:"Despair hardens into a plan."} },
    ],
  },
  s13: {
    driverLabel:"NEO", reactorLabel:"SECURITY / AGENTS",
    desire:"To punch through the building to the roof and Morpheus.",
    obstacle:"An army of guards and the building's defenses.",
    turnAt:5,
    rows:[
      { n:1, drive:{a:"Walking in armed",d:"Sets off the metal detector on purpose."}, react:{a:"Challenging him",d:"A guard asks him to disarm."} },
      { n:2, drive:{a:"Opening fire",d:"The assault begins."}, react:{a:"Swarming",d:"Security pours into the lobby."} },
      { n:3, drive:{a:"Cutting through",d:"Impossible, balletic gunplay with Trinity."}, react:{a:"Falling back",d:"The defenders are overwhelmed."} },
      { n:4, drive:{a:"Taking the wall",d:"Runs it horizontally to flank them."}, react:{a:"Failing to pin",d:"Nothing holds the two."} },
      { n:5, drive:{a:"Reaching the lift",d:"Breaks through toward the roof."}, react:{a:"Yielding",d:"The path to Morpheus opens."} },
    ],
  },
  s14: {
    driverLabel:"AGENT SMITH", reactorLabel:"NEO",
    desire:"To delete Neo before he becomes what the Machines fear.",
    obstacle:"A man whose power is waking up \u2014 but isn't awake yet.",
    turnAt:6,
    rows:[
      { n:1, drive:{a:"Cornering him",d:"Traps Neo on the rooftop."}, react:{a:"Standing firm",d:"Won't run this time."} },
      { n:2, drive:{a:"Firing point-blank",d:"Empties the clip."}, react:{a:"Dodging bullets",d:"Bends back; only grazed."} },
      { n:3, drive:{a:"Losing the host",d:"Trinity ends that body."}, react:{a:"Saving Morpheus",d:"The rescue lands; the captain is free."} },
      { n:4, drive:{a:"Reasserting",d:"A new body waits in the subway."}, react:{a:"Choosing to fight",d:"Neo stops running and turns."} },
      { n:5, drive:{a:"Grinding him down",d:"Relentless, machine-tireless."}, react:{a:"Trading blows",d:"Holds his own for a while."} },
      { n:6, drive:{a:"Pinning him on the tracks",d:"A train roars in."}, react:{a:"Slipping free",d:"Escapes by a hair \u2014 spent and hunted."} },
    ],
  },
  s15: {
    driverLabel:"NEO", reactorLabel:"TRINITY / AGENT SMITH",
    desire:"To stop running and become who he is.",
    obstacle:"Agents who can kill the body \u2014 and his own unbelief.",
    turnAt:6,
    rows:[
      { n:1, drive:{a:"Falling",d:"Smith guns him down in room 303."}, react:{a:"Flatlining",d:"His body goes still on the ship."} },
      { n:2, drive:{a:"Lying dead",d:"No pulse, no breath."}, react:{a:"Declaring victory",d:"Smith calls it over."} },
      { n:3, drive:{a:"Hearing her",d:"Trinity speaks to his still body."}, react:{a:"Confessing",d:"The Oracle said she'd love The One \u2014 and she does."} },
      { n:4, drive:{a:"A heartbeat",d:"A flicker answers her."}, react:{a:"Calling him back",d:"'Now get up.'"} },
      { n:5, drive:{a:"Standing up",d:"Rises in the Matrix, unafraid."}, react:{a:"Faltering",d:"The Agents empty their guns \u2014 he stops the bullets midair."} },
      { n:6, drive:{a:"Seeing the code",d:"The Matrix resolves into raw green."}, react:{a:"Unmade",d:"Neo ends Smith from the inside. Belief becomes power."} },
    ],
  },
  s16: {
    driverLabel:"NEO", reactorLabel:"THE MACHINES",
    desire:"To carry the truth back to everyone still asleep.",
    obstacle:"A system that will fight to keep its hold.",
    turnAt:0,
    flat:true,
    rows:[
      { n:1, drive:{a:"Calling the system",d:"Picks up a line into the Matrix."}, react:{a:"Tracing",d:"The machines listen."} },
      { n:2, drive:{a:"Promising change",d:"A world without their controls or borders."}, react:{a:"Saying nothing",d:"Threatened, silent."} },
      { n:3, drive:{a:"Hanging up",d:"Done explaining himself."}, react:{a:"Watching",d:"He's loose inside their world now."} },
      { n:4, drive:{a:"Flying up",d:"Straight into the sky."}, react:{a:"Opening",d:"Free \u2014 and dangerous to the system that made him."} },
    ],
  },
};

/* Screenplay drafts — the TEXT layer that realizes each scene's beat SUBTEXT.
   Each block is tagged with the beat (n) it expands. type: scene|action|char|paren|dia.
   Original beat-aligned prose for every scene — paraphrased so each block realizes
   its beat in order (NOT the shooting script). */
const SCREENPLAY = {
  s1: {
    blocks: [
      { beat:1, type:"scene", text:"INT. HEART O' THE CITY HOTEL \u2014 NIGHT" },
      { beat:1, type:"action", text:"Flashlights carve the burned-out dark. FOUR COPS bottle a lone figure in black against the far wall \u2014 TRINITY, hands rising slowly from a humming laptop." },
      { beat:1, type:"action", text:"Outside, a black sedan noses through the cruisers. AGENT SMITH steps out, unhurried, and tells the lieutenant his men are already dead." },
      { beat:2, type:"action", text:"The lead cop reaches for his cuffs. Trinity moves \u2014 faster than the eye will accept. Three heartbeats later the squad is down and she is gone out the window." },
      { beat:3, type:"action", text:"She crosses the rooftops in long, impossible strides. A cop swears it cannot be done \u2014 then Smith drops into a patrolman's body and matches her, step for step." },
      { beat:4, type:"action", text:"A forty-foot gap yawns between buildings. Trinity does not slow. She launches, hangs, lands rolling. The Agent clears the same jump without effort." },
      { beat:5, type:"action", text:"A phone booth glows at the end of the block. A truck guns straight for it. She dives for the receiver \u2014" },
      { beat:5, type:"action", text:"\u2014 and is gone the instant she answers. The booth bursts into plastic. Smith stares at the empty wreckage. A name passes between the Agents: their next target. Neo." },
    ],
  },
  s2: {
    note: "This unit is a short sequence \u2014 it spans 2 sluglines (the apartment, the club).",
    blocks: [
      // BEAT 1 — Searching / Answering him
      { beat:1, type:"scene", text:"INT. ANDERSON'S APARTMENT \u2014 NIGHT" },
      { beat:1, type:"action", text:"A cramped room drowned in hardware. NEO is slumped asleep before a wall of monitors, their glow twitching across his face." },
      { beat:1, type:"action", text:"The screens blink to black. One by one, a line of text types itself out \u2014 unprompted." },
      { beat:1, type:"char", text:"ON SCREEN" },
      { beat:1, type:"dia", text:"You've been looking for me, Thomas." },
      { beat:1, type:"action", text:"Neo jerks awake. He hammers the keys; nothing he types interrupts it. The words are answering him." },
      // BEAT 2 — Hesitating / Beckoning
      { beat:2, type:"action", text:"A new line resolves on the glass: an address, a time, and a small icon \u2014 a white rabbit." },
      { beat:2, type:"action", text:"A KNOCK at the door. He flinches. When he looks back, the screens are ordinary again." },
      { beat:2, type:"char", text:"CHOI (O.S.)" },
      { beat:2, type:"dia", text:"You alive in there? We're heading out." },
      { beat:2, type:"action", text:"Neo opens up. CHOI and a few friends crowd the hall. Pinned to a girl's jacket: a white rabbit \u2014 the same as the screen. He stares at it a beat too long." },
      // BEAT 3 — Following the sign / Approaching
      { beat:3, type:"scene", text:"INT. NIGHTCLUB \u2014 LATER" },
      { beat:3, type:"action", text:"Black walls, industrial bass you feel in your teeth. Neo hangs at the edge with a beer he isn't drinking, already regretting this." },
      { beat:3, type:"action", text:"A woman crosses the room straight to him \u2014 as if she knew exactly where he'd be standing. This is TRINITY." },
      { beat:3, type:"char", text:"TRINITY" },
      { beat:3, type:"dia", text:"I know your name. I've wanted to meet you for a long time." },
      // BEAT 4 — Playing it cool / Seeing through him
      { beat:4, type:"char", text:"NEO" },
      { beat:4, type:"dia", text:"People know my name. Doesn't mean I know them." },
      { beat:4, type:"char", text:"TRINITY" },
      { beat:4, type:"dia", text:"You don't. But I know why you don't sleep. I know the thing you sit up chasing every night." },
      { beat:4, type:"action", text:"That lands harder than he'll let her see." },
      // BEAT 5 — Admitting the itch / Naming the stakes
      { beat:5, type:"char", text:"NEO" },
      { beat:5, type:"paren", text:"(quiet)" },
      { beat:5, type:"dia", text:"...And what's that." },
      { beat:5, type:"char", text:"TRINITY" },
      { beat:5, type:"dia", text:"A question. The one underneath all the others. It's the reason you're standing here instead of asleep." },
      // BEAT 6 — Letting hope in / Promising the door
      { beat:6, type:"action", text:"For the first time the noise of the room seems to fall away. He wants \u2014 badly \u2014 to believe her." },
      { beat:6, type:"char", text:"TRINITY" },
      { beat:6, type:"dia", text:"The answer is real, and it's closer than you think. But you have to come and find it." },
      { beat:6, type:"action", text:"She's swallowed by the crowd before he can ask how. Neo stands alone, the question wide awake in him now." },
    ],
  },
  s3: {
    blocks: [
      { beat:1, type:"scene", text:"INT. METACORTEX \u2014 HOLDING ROOM \u2014 DAY" },
      { beat:1, type:"action", text:"SMITH slides a thick file across the steel table, all courtesy. NEO, cuffed, asks for his phone call." },
      { beat:1, type:"char", text:"SMITH" },
      { beat:1, type:"dia", text:"Mr. Anderson. You live two lives, and only one of them has a future." },
      { beat:2, type:"char", text:"SMITH" },
      { beat:2, type:"dia", text:"By night you break into anything you please. Frankly, we have admired the work." },
      { beat:2, type:"action", text:"Neo gives him nothing." },
      { beat:3, type:"char", text:"SMITH" },
      { beat:3, type:"dia", text:"Help us reach a known terrorist and your record vanishes. Refuse, and so does the man behind it." },
      { beat:3, type:"char", text:"NEO" },
      { beat:3, type:"dia", text:"Then I want my phone call." },
      { beat:4, type:"action", text:"The door is suddenly gone. So is Neo's mouth \u2014 skin sealing where his lips were. He claws at a face that will not open, a scream with nowhere to go." },
      { beat:5, type:"action", text:"The Agents pin him. Something alive is forced into his navel and burrows deep." },
      { beat:5, type:"action", text:"Neo bolts upright in his own bed, gasping. A nightmare \u2014 except he is no longer sure the word means anything." },
    ],
  },
  s4: {
    note: null,
    blocks: [
      { beat:1, type:"scene", text:"EXT. ADAMS STREET BRIDGE \u2014 NIGHT" },
      { beat:1, type:"action", text:"Trinity's crew pulls the bug out of Neo in the back of a car, then delivers him to a derelict hotel room where MORPHEUS waits." },
      { beat:1, type:"char", text:"MORPHEUS" },
      { beat:1, type:"dia", text:"You came tonight because part of you already believes what I'm about to tell you." },
      { beat:2, type:"char", text:"MORPHEUS" },
      { beat:2, type:"dia", text:"All your life something about the world has felt off. You can't name it, but it never lets you rest." },
      { beat:2, type:"action", text:"Neo leans in despite himself." },
      { beat:3, type:"char", text:"MORPHEUS" },
      { beat:3, type:"dia", text:"It's the story laid over everything you see, so you never think to ask what's underneath." },
      { beat:4, type:"action", text:"Morpheus opens both hands. A blue capsule in one, a red one in the other." },
      { beat:4, type:"char", text:"MORPHEUS" },
      { beat:4, type:"dia", text:"Blue, and you wake in your bed and believe whatever you like. Red, and you stay \u2014 and I show you how far down this really goes." },
      { beat:5, type:"char", text:"MORPHEUS" },
      { beat:5, type:"dia", text:"Understand me: I'm offering nothing but the truth. And once you choose, there is no way back." },
      { beat:6, type:"action", text:"Neo's hand hovers, trembling, between the two." },
      { beat:7, type:"action", text:"He takes the red pill and swallows. Morpheus almost smiles." },
      { beat:7, type:"char", text:"MORPHEUS" },
      { beat:7, type:"dia", text:"Follow me." },
    ],
  },
  s5: {
    blocks: [
      { beat:1, type:"scene", text:"INT. POWER PLANT \u2014 POD FIELD \u2014 CONTINUOUS" },
      { beat:1, type:"action", text:"The red pill hits. The room behind Neo runs like wet paint; the mirror he touches gives way and pours up his arm." },
      { beat:2, type:"action", text:"He wakes \u2014 truly wakes \u2014 bald, naked, suspended in a gel-filled pod. Around him, past the limit of sight, towers of identical pods. A farm of sleeping bodies." },
      { beat:3, type:"action", text:"He tears the cables from his flesh. A spider-machine registers the defective unit and lets the pod purge." },
      { beat:4, type:"action", text:"He slides down a black drain toward drowning \u2014 until a hovercraft's hook catches him and hauls him up into the light." },
      { beat:5, type:"action", text:"Later, weak and re-grown, Neo sees the truth entire: the dead sky, the machines, the human crop. Morpheus tells him, quietly, that this is the world as it really is. It nearly breaks him." },
    ],
  },
  s6: {
    blocks: [
      { beat:1, type:"scene", text:"INT. THE CONSTRUCT \u2014 ENDLESS WHITE" },
      { beat:1, type:"action", text:"A void with no walls. Two worn leather chairs and an old television blink into being. MORPHEUS gestures for Neo to sit." },
      { beat:2, type:"char", text:"MORPHEUS" },
      { beat:2, type:"dia", text:"When the war turned against us, we burned the sky ourselves to starve them of the sun. It wasn't enough." },
      { beat:2, type:"action", text:"Neo listens, numb." },
      { beat:3, type:"action", text:"The television floods with a ruined Earth, ash where the sun used to be. Neo flinches from it." },
      { beat:4, type:"char", text:"MORPHEUS" },
      { beat:4, type:"dia", text:"What they grew to feed on us is this \u2014 a dream you can't taste or touch or smell. A cage built for the mind." },
      { beat:4, type:"action", text:"He understands the words. They have not reached his gut yet." },
      { beat:5, type:"char", text:"MORPHEUS" },
      { beat:5, type:"dia", text:"I am sorry to have to do this to you." },
      { beat:5, type:"action", text:"Neo sits with all of it \u2014 informed, and hollow. The scene has told him everything and changed nothing in him." },
    ],
  },
  s7: {
    blocks: [
      { beat:1, type:"scene", text:"INT. NEBUCHADNEZZAR \u2014 SPARRING PROGRAM" },
      { beat:1, type:"action", text:"TANK jacks a stack of disks into Neo. His eyes flutter; a lifetime of martial arts loads in seconds. Morpheus invites him to spar." },
      { beat:2, type:"action", text:"Neo comes in fast and proud. Morpheus slips every strike without trying." },
      { beat:2, type:"char", text:"MORPHEUS" },
      { beat:2, type:"dia", text:"Speed and strength mean nothing in here. Quit aiming and just move." },
      { beat:3, type:"action", text:"Neo throws everything he has. Morpheus stands him up mid-swing." },
      { beat:3, type:"char", text:"MORPHEUS" },
      { beat:3, type:"dia", text:"You are quicker than this. Stop holding yourself back." },
      { beat:4, type:"action", text:"Something clicks. Neo lands a clean blow that knocks Morpheus back a step. Watching from the core, the crew sits up." },
      { beat:4, type:"char", text:"MORPHEUS" },
      { beat:4, type:"dia", text:"Better." },
      { beat:5, type:"scene", text:"EXT. JUMP PROGRAM \u2014 ROOFTOP" },
      { beat:5, type:"action", text:"Two towers, a lethal gap between them. Morpheus clears it in a single bound and turns back." },
      { beat:5, type:"char", text:"MORPHEUS" },
      { beat:5, type:"dia", text:"Stop believing the gap is real." },
      { beat:6, type:"action", text:"Neo runs, leaps \u2014 and drops. The grid catches him like concrete. Back on the ship, blood on his lip." },
      { beat:6, type:"char", text:"MOUSE" },
      { beat:6, type:"dia", text:"Nobody makes the first jump." },
    ],
  },
  s8: {
    blocks: [
      { beat:1, type:"scene", text:"INT. THE ORACLE'S APARTMENT \u2014 KITCHEN \u2014 DAY" },
      { beat:1, type:"action", text:"Warm light, the smell of baking. THE ORACLE, an old woman in oven mitts, waves Neo in like a neighbor's kid." },
      { beat:2, type:"char", text:"NEO" },
      { beat:2, type:"dia", text:"Aren't you going to tell me?" },
      { beat:2, type:"char", text:"ORACLE" },
      { beat:2, type:"dia", text:"Don't worry about the vase." },
      { beat:3, type:"action", text:"He turns \u2014 and knocks a vase off the counter. It shatters." },
      { beat:3, type:"char", text:"ORACLE" },
      { beat:3, type:"dia", text:"What will really bother you is whether you would have broken it if I had said nothing." },
      { beat:4, type:"char", text:"NEO" },
      { beat:4, type:"dia", text:"Am I the one?" },
      { beat:4, type:"char", text:"ORACLE" },
      { beat:4, type:"paren", text:"(kindly)" },
      { beat:4, type:"dia", text:"Sorry, hon. You have the gift \u2014 but it looks like you are waiting for something. Maybe the next life." },
      { beat:5, type:"action", text:"The floor drops out of him. She softens." },
      { beat:5, type:"char", text:"ORACLE" },
      { beat:5, type:"dia", text:"Morpheus believes in you. He will lay down his life for you \u2014 that is the part you should fear." },
      { beat:6, type:"char", text:"ORACLE" },
      { beat:6, type:"dia", text:"One day you will have to choose: his life, or yours." },
      { beat:6, type:"action", text:"Neo leaves with the certainty he came for gone, and a worse question in its place." },
    ],
  },
  s9: {
    blocks: [
      { beat:1, type:"scene", text:"INT. A RESTAURANT THAT ISN'T REAL \u2014 NIGHT" },
      { beat:1, type:"action", text:"CYPHER cuts into a steak he knows is only code. Across the table, an Agent waits." },
      { beat:1, type:"char", text:"CYPHER" },
      { beat:1, type:"dia", text:"Put me back in. Someone important. Someone who remembers none of this. Give me that, and you can have Morpheus." },
      { beat:2, type:"scene", text:"INT. DERELICT BUILDING \u2014 DAY" },
      { beat:2, type:"action", text:"Cypher leads the crew into the wired-up ruin for a routine jack-in. They trust him at their backs." },
      { beat:3, type:"action", text:"It is a trap. A wall peels open onto Agents. Gunfire pins the team; one of them is dead before he understands why." },
      { beat:4, type:"action", text:"Cypher slips out early and jacks back to the ship \u2014 alone with the sleeping bodies of his crew." },
      { beat:5, type:"scene", text:"INT. NEBUCHADNEZZAR \u2014 CORE" },
      { beat:5, type:"action", text:"He works the plugs one at a time, killing them where they lie. Over the line, TRINITY's voice cracks as she realizes who the traitor is." },
    ],
  },
  s10: {
    blocks: [
      { beat:1, type:"scene", text:"INT. WET-WALL HOTEL \u2014 NIGHT" },
      { beat:1, type:"action", text:"Plaster and pipes burst as Agents flood the room. MORPHEUS shoves Neo toward the others." },
      { beat:1, type:"char", text:"MORPHEUS" },
      { beat:1, type:"dia", text:"Go. Get him out of here." },
      { beat:2, type:"action", text:"He throws himself at SMITH to buy seconds. Smith is stronger, faster, certain." },
      { beat:3, type:"action", text:"Morpheus absorbs the beating without a sound while TRINITY hauls Neo down through the wall to safety." },
      { beat:4, type:"action", text:"At last he is pinned, broken, still." },
      { beat:4, type:"char", text:"SMITH" },
      { beat:4, type:"dia", text:"You see? There was never any other way." },
      { beat:5, type:"action", text:"Morpheus lets them carry him off. On the ledge above, Neo watches \u2014 and silently swears this is not the end." },
    ],
  },
  s11: {
    blocks: [
      { beat:1, type:"scene", text:"INT. NEBUCHADNEZZAR \u2014 CORE \u2014 NIGHT" },
      { beat:1, type:"char", text:"TANK" },
      { beat:1, type:"dia", text:"They will crack his mind open and read the codes to Zion right out of it." },
      { beat:1, type:"char", text:"NEO" },
      { beat:1, type:"dia", text:"There has to be another way." },
      { beat:2, type:"char", text:"TANK" },
      { beat:2, type:"dia", text:"Every ship, every soul still free \u2014 all of it gone. That is what he is carrying." },
      { beat:2, type:"action", text:"The crew goes quiet." },
      { beat:3, type:"char", text:"TANK" },
      { beat:3, type:"dia", text:"One man against the whole of Zion. The math only solves one way." },
      { beat:3, type:"action", text:"Trinity cannot look at the chair where Morpheus's body lies." },
      { beat:4, type:"action", text:"Tank reaches for the plug \u2014 the only mercy left." },
      { beat:4, type:"char", text:"NEO" },
      { beat:4, type:"dia", text:"Wait." },
      { beat:5, type:"char", text:"TANK" },
      { beat:5, type:"dia", text:"It has to be now." },
      { beat:5, type:"action", text:"The impossible choice settles onto Neo's face." },
    ],
  },
  s12: {
    blocks: [
      { beat:1, type:"scene", text:"INT. NEBUCHADNEZZAR \u2014 CORE \u2014 CONTINUOUS" },
      { beat:1, type:"char", text:"NEO" },
      { beat:1, type:"dia", text:"I'm going back in for him." },
      { beat:1, type:"char", text:"TANK" },
      { beat:1, type:"dia", text:"That's insane. No one has ever done it." },
      { beat:2, type:"char", text:"NEO" },
      { beat:2, type:"dia", text:"The Oracle says I'm not the one. So there's nothing to lose." },
      { beat:2, type:"char", text:"TANK" },
      { beat:2, type:"dia", text:"Agents will be waiting. You will die." },
      { beat:3, type:"char", text:"NEO" },
      { beat:3, type:"dia", text:"He was ready to die for me. I'm not trading his life for mine." },
      { beat:3, type:"char", text:"TRINITY" },
      { beat:3, type:"dia", text:"Then I'm going with you." },
      { beat:4, type:"char", text:"NEO" },
      { beat:4, type:"dia", text:"You don't have to do this." },
      { beat:4, type:"char", text:"TRINITY" },
      { beat:4, type:"dia", text:"I'm not asking." },
      { beat:5, type:"action", text:"They drop into the loading program and call up an arsenal that runs to the horizon. Despair has hardened into a plan." },
      { beat:5, type:"char", text:"NEO" },
      { beat:5, type:"dia", text:"We're going to need a lot of guns." },
    ],
  },
  s13: {
    blocks: [
      { beat:1, type:"scene", text:"INT. GOVERNMENT BUILDING \u2014 LOBBY \u2014 DAY" },
      { beat:1, type:"action", text:"Neo strolls through the metal detector. It SHRIEKS. A GUARD pulls open his coat onto an armory." },
      { beat:1, type:"char", text:"GUARD" },
      { beat:1, type:"dia", text:"Hold it right there \u2014" },
      { beat:2, type:"action", text:"The lobby erupts. Marble columns chew apart under automatic fire as soldiers pour in." },
      { beat:3, type:"action", text:"Neo and Trinity move through them like a single weapon \u2014 impossible, balletic. The defenders fall back." },
      { beat:4, type:"action", text:"Neo runs straight up a pillar and across the wall; no one can hold a bead on either of them." },
      { beat:5, type:"action", text:"They blow the doors and reach the elevator. The way up \u2014 to Morpheus \u2014 is open." },
    ],
  },
  s14: {
    blocks: [
      { beat:1, type:"scene", text:"EXT. ROOFTOP \u2014 DAY" },
      { beat:1, type:"action", text:"SMITH steps from a stairwell, pistol level. Neo does not run." },
      { beat:2, type:"action", text:"Smith empties the clip. Neo arches back, hands tracking the rounds; the bullets slow, hang, and drop. Only a graze." },
      { beat:3, type:"action", text:"Trinity ends the host body point-blank. Below, Morpheus is hauled to freedom \u2014 the rescue holds." },
      { beat:4, type:"scene", text:"INT. SUBWAY STATION \u2014 DAY" },
      { beat:4, type:"action", text:"Smith re-forms inside a commuter. Alone on the platform, Neo stops running and turns to face him." },
      { beat:5, type:"action", text:"They collide. Neo holds his own through a brutal exchange while Smith never tires." },
      { beat:6, type:"action", text:"Smith pins him across the rails as a train screams in. At the last instant Neo twists free \u2014 spent, hunted, alive." },
    ],
  },
  s15: {
    blocks: [
      { beat:1, type:"scene", text:"INT. APARTMENT 303 \u2014 DAY" },
      { beat:1, type:"action", text:"Smith catches Neo in the hallway and fires until the gun is empty. Neo folds to the floor." },
      { beat:1, type:"action", text:"INTERCUT \u2014 NEBUCHADNEZZAR: on the ship, the monitors flatline." },
      { beat:2, type:"char", text:"SMITH" },
      { beat:2, type:"dia", text:"Check him. It's finished." },
      { beat:2, type:"action", text:"The crew stares at a body with no pulse." },
      { beat:3, type:"scene", text:"INT. NEBUCHADNEZZAR \u2014 CORE" },
      { beat:3, type:"action", text:"TRINITY leans to Neo's ear and tells him what the Oracle once promised her \u2014 that she would fall for the one." },
      { beat:3, type:"char", text:"TRINITY" },
      { beat:3, type:"dia", text:"So you can't be dead. You can't. Because I love you." },
      { beat:4, type:"action", text:"A single beat answers on the monitor." },
      { beat:4, type:"char", text:"TRINITY" },
      { beat:4, type:"dia", text:"So get on your feet." },
      { beat:5, type:"scene", text:"INT. APARTMENT 303 \u2014 DAY" },
      { beat:5, type:"action", text:"Neo opens his eyes and stands. The Agents unload into him \u2014 and he lifts one hand and stops every round in the air." },
      { beat:6, type:"action", text:"The corridor dissolves into falling green code; Neo reads the world as it is written. He steps into Smith and unmakes him from the inside." },
    ],
  },
  s16: {
    blocks: [
      { beat:1, type:"scene", text:"INT. PHONE BOOTH \u2014 DAY" },
      { beat:1, type:"action", text:"Neo lifts a receiver and speaks to the thing on the other end \u2014 the system itself, listening, already tracing the call." },
      { beat:2, type:"char", text:"NEO" },
      { beat:2, type:"dia", text:"I know you can hear me. And I know what frightens you \u2014 not me, but what people become once they stop believing your version of things." },
      { beat:2, type:"action", text:"The line says nothing." },
      { beat:3, type:"char", text:"NEO" },
      { beat:3, type:"dia", text:"I'm going to show them what you've kept from them. After that, where they take it is up to them." },
      { beat:3, type:"action", text:"He hangs up." },
      { beat:4, type:"action", text:"He steps into the street, slides on his glasses, and rockets straight up into the sky \u2014 free, and a danger to everything that built him." },
    ],
  },
};

/* Continuity model — what each scene ESTABLISHES (plants) and REFERENCES (relies on).
   The checker flags references with no prior setup, premature references, and
   setups (setup:true) that never pay off. Drives the continuity-conflict report. */
const FACTS = {
  redpill:          { label:"Neo takes the red pill" },
  realworld:        { label:"the real world behind the Matrix" },
  matrix_prison:    { label:"the Matrix as a prison for the mind" },
  rules:            { label:"the rules of the Matrix can be bent" },
  prophecy:         { label:"the prophecy of The One", setup:true },
  oracle_verdict:   { label:"the Oracle's verdict that Neo isn't The One" },
  trinity_prophecy: { label:"the Oracle's promise that Trinity would love The One" },
  zion_codes:       { label:"Morpheus carries the access codes to Zion", setup:true },
  cypher_deal:      { label:"Cypher's deal with the Agents" },
  neo_powers:       { label:"Neo's power to bend the Matrix" },
};

const CONTINUITY = {
  s1:  { establishes:[], references:[] },
  s2:  { establishes:[], references:[] },
  s3:  { establishes:[], references:[] },
  s4:  { establishes:["redpill"], references:[] },
  s5:  { establishes:["realworld"], references:["redpill"] },
  s6:  { establishes:["matrix_prison"], references:["realworld"] },
  s7:  { establishes:["rules"], references:[] },
  s8:  { establishes:["prophecy","oracle_verdict"], references:[] },
  s9:  { establishes:["cypher_deal"], references:[] },
  s10: { establishes:[], references:["cypher_deal"] },
  s11: { establishes:["zion_codes"], references:[] },
  s12: { establishes:[], references:["oracle_verdict"] },
  s13: { establishes:[], references:[] },
  s14: { establishes:["neo_powers"], references:["rules"] },
  s15: { establishes:[], references:["trinity_prophecy","prophecy","neo_powers"] },
  s16: { establishes:[], references:["neo_powers"] },
};

window.TURN_DATA = { PROJECT, CHARACTERS, PROPS, SCENES, BEATS, SCREENPLAY, FACTS, CONTINUITY };
